src/www/vpn_openvpn_client.php

SImple fix. The edit button in the interface does not actually open up the edit form. I have corrected this by adding the appropriate parameter to the href.

Fixed broken OpenVPN client edit href

---

src/share/locale/ja/LC_MESSAGES/OPNsense.pot

This PR may be a bit early, but it may show other languages how easy it is to get going!
Japanese translation is now officially going, with some way to go...

jp .pot file kickoff

---

src/share/locale/ja_JP/LC_MESSAGES/OPNsense.po

Login page items, as requested, I'm so excited!!!

はじじぇまして OPNsense!

---

src/share/locale/ja_JP/LC_MESSAGES/OPNsense.po

more lines from Chie-san

---

src/www/status_rrd_graph.php

Removed width=100% and set inline style="max-width:100%; height:auto"

RRD graphs are obnoxiously large #55

---

src/www/diag_logs_filter.php

contains fix for #269 and some language issues in the file
NOTE: Was not able to test it because I get this when I put this into my VM with the stable release:
Fatal error: Cannot redeclare get_port_with_service() (previously declared in /usr/local/www/diag_logs_filter.php:380) in /usr/local/etc/inc/filter_log.inc on line 278

work on #269

---

lang/de_DE.po

Thanks to @DokuKaefer to provide a list of mistakes in the german translation.
See #261 for conversation

Fixes in german translation from @DokuKaefer

---

src/www/diag_logs_filter.php
src/www/diag_logs_filter_dynamic.php

I found the GUI Error also in the dynamic view and fixed it

fixed issue also in dynamic view and corrected comment

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php
src/www/system_authservers.php
src/www/system_usermanager.php
src/www/system_usermanager_import_ldap.php

usermanager: disable username and descr field for ldap users
usermanager: hide password field for ldap users
import ldap user: fixed a bug on Active Directory where the name attribute isn't handled correctly
import ldap user: sort entries by name
import ldap user: add scrollbars on IE, Firefox & Opera
auth servers: move bind credentials up on the screen

minor LDAP fixes

---

src/www/protochart/prototype.js

fix blank chart on the diag_logs_filter_summary page.

missing prototype.js in protochart directory

---

src/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml

fix menu collapses when select DHCP Server interfaces tab 

---

lang/ja_JP.po

fix: botched the header with gettext merges

---

lang/de_DE.po

created a diff and patched the file for the commit on this branch so there is no dependency

the changeset of the other 4% of #285

---

lang/de_DE.po

this is the first branch containing the first commit - the second depends on it

Translation #285 Part1

---

src/www/graph.php

change color

---

src/www/crash_reporter.php

added user agent to crash reporter

---

src/www/diag_authentication.php
src/www/diag_dns.php
src/www/diag_limiter_info.php
src/www/diag_logs_dhcp.php
src/www/diag_logs_settings.php
src/www/diag_packet_capture.php

The beginning of my modest contribution, I am not high level PHP. Tell me if it's good? I try to help as I can ...

Update Missing translations

---

src/www/firewall_rules.php

Adopt style of RFC 1918 rule and reserved IANA rule to match user created
rules in style.
That tiny style inconsistency makes me crazy since using OPNsense the first time... :wink:

firewall: adopt formatting of RFC 1918 and IANA rules

---

src/www/status_services.php

unbound could not be started via Status: Services.

unbound: fix starting of unbound via Status: Services

---

src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
src/opnsense/www/js/opnsense.js

Adds password and textbox (textarea) fields.

Additional fields in MVC library

---

src/www/load_balancer_pool.php

translation fix

---

src/www/vpn_ipsec_keys.php
src/www/vpn_ipsec_mobile.php

Fix ipsec page

---

src/www/services_dnsmasq.php

Fix dnsmasq page

---

src/www/status_dhcp_leases.php

DHCP: change column of lease table from "Online" to "Status"

---

src/www/system_usermanager.php

@8191 should test this before it should be merged.
If it works this closes #623

changed file type

---

src/wizard/openvpn.xml

OpenVPN wizard: remove incorrect legacy text

---

src/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml

VPN: IPsec: Mobile Clients looses menu hierarchy after clicking "Apply"

Menu: fixed menu for IPsec Mobile Clients after apply

---

src/etc/inc/certs.inc
src/etc/inc/openvpn-client-export.inc
src/etc/inc/system.inc
src/opnsense/scripts/OPNsense/CaptivePortal/generate_certs.php

pull in work for https://github.com/opnsense/core/issues/664

certs: refactor ca_chain for #664

---

src/www/vpn_ipsec.php

Solves #650 
Change columns of IPsec tunnels as follows:
* P1 Protocol, P1 Transforms --> Phase 1 Proposal to show Enc. Alg. + Auth
Alg. + DH Group
* Add column Authentication for P1 to show "RSA" or "PSK" (or Xauth for IPsec
mobile)
* Move P2 Protocol, Mode --> Type to show IP version + enc. + mode
* P2 Transforms --> Encryption Algorithms
* P2 Auth Methods --> Authenticity Algorithms
* Add column PFS for P2

IPsec tunnels: enhance table of configured tunnels

---

Makefile
src/opnsense/scripts/interfaces/list_arp.py
src/opnsense/scripts/interfaces/list_ndp.py

net/py-netaddr package required

use netaddr to lookup mac address in list_arp.py and list_ndp.py

---

src/www/system_advanced_network.php

The changes won't happen until the interface is re-configured, just like for the other settings.

"device polling" changes also require a reboot

---

src/www/load_balancer_monitor.php
src/www/load_balancer_pool.php
src/www/load_balancer_setting.php
src/www/load_balancer_virtual_server.php

fix filter reload with invalid relayd config, fixes #780

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.conf

i think it works now but it needs some additional testing

Icap support

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Added ability to change the hostname and admin email in Proxy
_(Small addition for me to test if things are well done?)_

Added ability to change the hostname and admin email in Proxy

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml

@AdSchellevis add a link to more easily create a CA

add a link to create a CA

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ModelRelationField.php

support multiple values in ModelRelationField, fixes #868

---

lang/ja_JP.po

Simple names to complete drop-down

---

src/opnsense/service/modules/template.py

Please :) This enables the break/continue loop controls in jinja. I'll need it for a plugin...

enable jinja2 loopcontrols extension

---

src/www/interfaces.php

was not able to test this (I do not have a ppp interface) -> requires additional check

translation

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml

Fixed some typos in the help text for the proxy page.

Fixed typos

---

Makefile
src/etc/inc/openvpn-client-export.inc

created a fix for 914 (openvpn-client-export.inc)

---

src/opnsense/www/js/jquery.qrcode.js
src/opnsense/www/js/jquery.qrcode.js.LICENSE
src/opnsense/www/js/qrcode.js
src/www/system_usermanager.php

do not use an external service for authentication secrets

create qrcode in the browser instead of an external service

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt

In base form dialog add translate for buttons.

Add translatable template

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Some users just want to block https urls by transparent https proxy

Filter URL Only at HTTPS Filter

---

src/www/vpn_ipsec_phase1.php

forgot this in the commit before

Camellia can only be used with IKEv2

---

src/www/services_unbound_advanced.php

* translation fixes (for example submit button)
* create some options in a function
* remove some not operators
* make short echo tags look more like a template

changes in services_unbound_advanced.php

---

src/etc/inc/interfaces.inc
src/etc/inc/system.inc
src/etc/rc.carpbackup
src/etc/rc.carpmaster
src/etc/rc.linkup
src/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml
src/www/carp_status.php

Multiple issues in using carp, mainly caused by not using the BSD standards.

Carp improvements

---

src/opnsense/mvc/app/views/OPNsense/CaptivePortal/vouchers.volt

just add a message if the validation fails to the commit of @AdSchellevis

add validation message

---

src/www/services_ntpd_pps.php

only checked via `php -l` but it should work ;)

translation fix in services_ntpd_pps.php

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml

just fix some spelling before 17.1 is released.

fix proxy strings 'X-Forwarded-For'

---

src/www/firewall_nat_edit.php

Followup from #1316. Completely untested!

Note that src and dst ports only apply to TCP and UDP

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php
src/www/system_authservers.php

ignore the implementation in #1348 since it is a non-used replication

Implement startTLS for ldap #1346

---

src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml

the person who reported it, confirmed that this patch works

fix for https://forum.opnsense.org/index.php?topic=4309.0;topicseen

---

src/opnsense/firmware-message

just because this should not be in the final release ;)

fix spelling issue in firmware message

---

src/www/status_dhcp_leases.php

DHCP leases: do not link to WOL page if WOL plugin is missing (2nd attempt)

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound.php

This should provide a good compromise to solve #1400

Add option to do not register ipv6 link-local addresses in the DNS Resolver

---

src/etc/inc/dyndns.class
src/etc/inc/services.inc

Addresses issue https://github.com/opnsense/core/issues/1353

Dynamic DNS: Support Google Domains

---

src/etc/inc/auth.inc

Seems this was copied from pfSense

Changed paths to change Referrer

---

src/www/system_hasync.php

Added help for setting up a backup machine

---

src/etc/inc/gwlb.inc

fix logic error in the behaviour of fixup_default_gateway()

---

src/www/vpn_openvpn_export.php

Fix Tunnelblick link

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerRoot.php

After [this comit](https://github.com/opnsense/tools/commit/e9882554428519b38fd95ddb92604ee63737cd32) setting locale from Phalcon works fine.

Restore setLocale from Phalcon

---

src/opnsense/mvc/app/views/layouts/default.volt

patch it into the library in the template so it will be applied to all templates.
Strings used from the original pull request.
closes #1633

patch translations into bootgrid at runtime, based on the work of kekek2

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.acl.conf

Exclude domains from antivirus check.

Icap whitelist

---

src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt

Add in missing property and fix typo.

---

src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt

Really fix the typo this time!

---

src/opnsense/www/js/opnsense_bootgrid_plugin.js

Include an "info" action variant for bootgrid.

---

src/opnsense/mvc/app/views/layout_partials/base_form.volt

Fix form header

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerRoot.php

https://github.com/opnsense/core/issues/1218

User-based language in MVC

---

src/opnsense/www/js/opnsense.js
src/opnsense/www/js/opnsense_ui.js
src/www/head.inc

Disables some features to keep the rest working if the browser has some features disabled.

fix the localStorage issue from #1915

---

src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/Api/SettingsController.php
src/opnsense/mvc/app/views/OPNsense/TrafficShaper/index.volt

probably not the cleanest solution but it works. -> ticket #2004

traffic shaper: add a ! for negated fields

---

src/etc/inc/plugins.inc.d/webgui.inc

lighttpd: add mime type for WPAD/PAC

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt
src/opnsense/mvc/app/views/layout_partials/base_form.volt
src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt

A new PR containing rolled up changes and suggestions.
-=david=-

Allow input fields to render as readonly.

---

src/www/license.php

Error: Stray end tag span.
Error: No p element in scope but a p end tag seen.
The ordered list makes paragraph tag unnecessary.

HTML Compliance - Lobby: License

---

src/www/vpn_openvpn_export.php

fix: add js code to open links in a new tab

---

src/etc/inc/authgui.inc
src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/scripts/OPNsense/CaptivePortal/htdocs_default/index.html
src/www/head.inc

Viewport User Scalable

---

src/www/widgets/widgets/gateways.widget.php

do some code optimisation and use label instead of font color. It looks like this now:

use label instead of font color

---

src/www/status_gateways.php

ref: opnsense/plugins#508
don't use hardcoded colors in status_gateway.php
requested by @marjohn56

fix: themes in System: Gateways: Status page

---

src/www/status_interfaces.php

The chevron down icon is problematic to touch select here.  Extend selection area to entire vertical and horizontal row space.

Touch Friendlyize - Interface Overview Interface Selection

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php

some DRY for Plugin Controllers this makes CRUD actions one liners (tested with tor acl).

add CRUD action helpers to ApiMutableModelControllerBase

---

src/www/status_interfaces.php

Create opportunistic word breaks between raw and unit-ized (KB/MB/GB) In/Out Packets for better portrait mobile view line wrap formating.
These are not necessarily ISP DNS servers.
Error: script element between head and body.

HTML Compliance - Interfaces Overview

---

src/www/widgets/widgets/log.widget.php

Add update interval configuration option.

Firewall Logs Widget - Add Update Interval Option

---

src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
src/opnsense/www/js/opnsense.js
src/opnsense/www/js/opnsense_ui.js

/usr/core/src/mvc/app/views/layout_partials/form_input_tr.volt
Error: Attribute "for' not allowed on element <tr> at this point.
Error: Attribute "for" not allowed on element <div> at this point.
Error: Attribute "for" not allowed on element <a> at this point.
Error: Attribute "for" not allowed on element <small> at this point.
Error: Attribute "for" not allowed on element <span> at this point.
Error: Duplicate ID "clear-options".

HTML Compliance - MVC Form Input - Attribute "for" on Element <tr,div,a,small,span>

---

src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/VoucherController.php
src/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php
src/opnsense/mvc/app/views/OPNsense/CaptivePortal/vouchers.volt

adding expiry time so that a voucher can only be used til that time. Default is no expiry.

Captive portal: add expiry time

---

Scripts/development/crawl_legacy_deps.py
src/etc/rc.subr.d/livemode

Propose fix some typos

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css
src/www/widgets/widgets/log.widget.php

Options labeling and arrangement
Space utilization

Firewall Logs Widget - Settings Form Layout

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound.php

Expose system domain unbound local-zone type to be configurable.

Services - Unbound DNS - General - System Domain Local Zone Type Option

---

src/etc/inc/services.inc

Forum message
https://forum.opnsense.org/index.php?topic=7304.0
No one else has complained of this which is odd, @fichtner  you have pppoe with a link local I  thought.

RADVD Problem on PPPeO link without public IPv6 address

---

src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

As discussed with @AdSchellevis in IRC

traffic shaper: respect mask in queue config

---

src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogPipe.xml
src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml
src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

Add delay option to pipe in Traffic Shaper

---

src/www/status_dhcpv6_leases.php

Delegated Prefixes display was incorrect.

Fix incorrect display

---

src/etc/inc/interfaces.inc

Make use of updated dhcp6c clients config re-read. Also don't launch dhcp6c if it's already running.

Send HUP to dhcp6c

---

src/www/system_gateways.php
src/www/system_gateways_edit.php
src/www/widgets/api/plugins/gateway.inc
src/www/widgets/widgets/gateways.widget.php

Hide STDEV from GUI when Dpinger not enabled

dpinger STDEV GUI Additions

---

src/www/widgets/widgets/monit.widget.php

* poll time is in seconds of course :innocent:
* polling was running twice
possibly due to the `<script>` tag location within `<body>`
once while parsing the `<body>` and once when DOM was ready

monit: fix widget issues

---

src/www/interfaces.php

I think it should be dhcpdv6 not dhcpv4, :)

Typo in interfaces.php

---

src/www/widgets/widgets/system_information.widget.php

Remove tool tip from small CPU load system info widget.

Remove CPU Load Tooltip

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/alerts.xml
src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/services.xml

monit: fix UI issues

---

src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php

fix nextcloud file format:
closes #2527

fix nextcloud file name format

---

src/opnsense/mvc/app/views/layouts/default.volt
src/www/fbegin.inc

Sidebar Collapsible Menus
Requires changes to existing themes - seperate PR's issued.

Sidebar Menus

---

src/opnsense/www/themes/opnsense/assets/stylesheets/bootstrap/_responsive-utilities.scss
src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

Patch Opnsense theme for Sidebar

Opnsense_theme_patch

---

src/www/firewall_rules.php

I posted about this on the forum at opnsense.org and ended up finding and fixing the problem.
[https://forum.opnsense.org/index.php?topic=9373.0](https://forum.opnsense.org/index.php?topic=9373.0)
This is tested to work on 18.7.

Fix disabled Reject action icon display code

---

src/etc/inc/services.inc
src/www/services_dhcp.php
src/www/services_dhcp_edit.php

I tried my luck and opened my first pull request. Please let me know if anything further has do be done. Here are some open points I couldn't figure out:
- Do I need to add translations for the description of the drop-down list?
- Do I need to handle dhcpv6 as well?
This pull request tries to solve my feature request #2650.
Regards
Ingo

Add DHCP Dynamic DNS key algorithm drop-down list

---

src/opnsense/service/modules/addons/template_helpers.py

fixes the issue that if the element does not exist, I will get an array with a single element which is null element, which again breaks for loops

core: fix configd asList helper

---

src/opnsense/mvc/app/views/layouts/default.volt
src/www/fbegin.inc

tooltip for sidebar

---

src/opnsense/www/js/opnsense_theme.js
src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

Opnsense theme sidebar mod

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

deleted expansion delay / animation -> https://github.com/opnsense/core/issues/2554
sidebar toggle-button ->  animation definition is not needed anymore

opnsense theme (no expansion delay / animation)

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

@franco you are to fast;-)
This are the last things for the css modification!
".collapsing" not needed anymore!
grouping classes for optimisation!

Navigation optimisation

---

src/opnsense/www/js/opnsense_theme.js

fix for -> hover in and out resets same elements instead of reopening them (https://github.com/opnsense/core/issues/2554)

sidebar - hover in and out fix

---

src/etc/inc/plugins.inc.d/openvpn/auth-user.php
src/www/vpn_openvpn_server.php

Openvpn option to select with between CN and username must be check as CSO

openvpn, option to match CSO against common_name or login

---

src/www/interfaces.php

Add the missing FTI/ to the start of the $username

Add FTI/ to password - tidy end of useridhex

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

opnsense theme chrome browser outline fix
@fichtner

opnsense theme chrome browser outline fix

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

a few entries that are no longer needed

---

src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogPipe.xml
src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogQueue.xml
src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml
src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

Add basic PIE support for PIPE and QUEUE. 
Needs https://github.com/opnsense/core/commit/89802d77b6cd1cc68c567086214b1f3d6080965b

trafficshaper: add FQ_PIE and PIE to shaper

---

src/opnsense/service/templates/OPNsense/Proxy/wpad.dat

* jinja cannot update variables -> workaround via an hash
* typo up/downcase
* dependency missing for match

www/squid: fix pac template

---

src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/SessionController.php

Added a connect action to the CaptivePortal API as discussed here https://forum.opnsense.org/index.php?topic=2028.msg6402

Added CaptivePortal API connect action

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

@fichtner opnsense theme - sidebar - cut off modification fix

opnsense theme - sidebar - cut off modification fix

---

src/opnsense/www/js/opnsense_theme.js

@fichtner small correction changing ".list-group-items:last-child" to "a:last-child"

sidebar - change ".list-group-items:last-child" to "a:last-child"

---

src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php

If string is "0,1,2,3" result is "01,2,3"
empty($row[$fieldname]) return true if $row[$fieldname] is "0"

Fix checking empty string.

---

src/www/system_general.php

Fix small typo

---

.gitignore

(Discussed with @AdSchellevis .)

Add src/opnsense/www/.htrouter.php to .gitignore

---

src/www/firewall_schedule_edit.php
src/www/firewall_scrub_edit.php
src/www/firewall_virtual_ip_edit.php

This fixes a duplicated closing tag and two instances of incorrect CSS usage to what was intended.

Fix some HTML errors

---

src/etc/inc/legacy_bindings.inc
src/wizard/openvpn.xml
src/wizard/system.xml
src/www/diag_confbak.php
src/www/diag_logs_dhcp.php
src/www/guiconfig.inc
src/www/status_openvpn.php
src/www/wizard.php

Change tabs to spaces

---

src/opnsense/www/js/opnsense_theme.js

@fichtner sidebar - short fix -> forgot a variable here!

sidebar - short fixes

---

src/www/status_dhcpv6_leases.php

Doing the quotation marks as well where we're at it, which hopefully pleases @fichtner ;)

Fix undefined variable

---

src/etc/inc/gwlb.inc
src/etc/inc/interfaces.lib.inc
src/etc/inc/notices.inc
src/etc/inc/plugins.inc.d/unbound.inc
src/etc/inc/util.inc
src/www/fbegin.inc
src/www/services_unbound.php
src/www/services_unbound_acls.php
src/www/services_unbound_host_edit.php
src/www/system_certmanager.php

I have attempted to make sure that if I touched a line, all occurrences on that line were fixed. Hopefully, I didn't miss any.

Replace some double quoted strings with single quotes ones

---

src/www/services_unbound_advanced.php

Added help text for verbosity from https://nlnetlabs.nl/documentation/unbound/unbound.conf/

Updated help text for verbosity level

---

src/etc/inc/interfaces.inc
src/etc/inc/plugins.inc.d/ipsec.inc
src/etc/inc/plugins.inc.d/openvpn.inc
src/etc/inc/plugins.inc.d/unbound.inc
src/etc/inc/services.inc
src/etc/inc/system.inc
src/opnsense/scripts/shell/setaddr.php
src/www/interfaces.php
src/www/interfaces_lagg.php
src/www/interfaces_lagg_edit.php
src/www/interfaces_wireless.php
src/www/interfaces_wireless_edit.php
src/www/vpn_ipsec_settings.php
src/www/vpn_openvpn_client.php
src/www/widgets/widgets/gateways.widget.php
src/www/wizard.php

Change foreach loops that don't use values to use array_keys()

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt

Add hostname lookup to live view, closes #2287

---

src/www/status_dhcpv6_leases.php

Taken Ad's version as it's much cleaner and works on both my live system with multiple leases and my test system that has only one lease.

dhcpd6 leases not always correctly displayed

---

src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php

if $row[$fieldname] is "0", it changed to empty string.

Fix checking empty value.

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/arp.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/networkinsight.volt
src/opnsense/mvc/app/views/OPNsense/Proxy/index.volt
src/opnsense/www/js/opnsense.js
src/www/firewall_schedule_edit.php
src/www/interfaces.php

This most importantly involves duplicate case statement labels, declaration errors and empty if/catch blocks.

Fix some JS errors

---

src/www/interfaces.php

Small typo in GUI:
> muti-WAN interface

fix typo 'muti-WAN' interface

---

src/etc/ssl/opnsense.cnf
src/www/system_certmanager.php

Confirmed to work by the OP of #2800.

Add option to create combined client and server certificate, closes #2800

---

src/www/firewall_nat_1to1_edit.php
src/www/firewall_nat_edit.php
src/www/firewall_nat_out_edit.php

Fix input groups with selectpicker in legacy pages

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Don't merge as long as we are using v3

core: update config for squid version 4

---

src/www/system_gateways_edit.php

Time period needs to be greater than 2.1 times the probe interval.

Add validation check for time period for Dpinger

---

src/opnsense/mvc/app/models/OPNsense/Base/Constraints/ComparedToFieldConstraint.php

fixes #3219
See also: https://forum.opnsense.org/index.php?topic=11572.0;topicseen

rspamd: fix constraint

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/parentproxy.conf

Proxy: add auth to parent proxy

---

src/www/widgets/widgets/ipsec.widget.php

core/vpn/ipsec: allow easier override of colors in themes

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php
src/www/system_usermanager.php
src/www/system_usermanager_import_ldap.php

* Load user email when available
* Update descr and email if available when updating existing local user
* Add all the necessary search attributes while making LDAP query
NB: This is a followup of opnsense#3322

Auth/LDAP: More reliable load and syncup for LDAP attributes

---

Scripts/development/lib/legacy_deps.py
src/etc/inc/gwlb.inc
src/etc/inc/interfaces.inc
src/etc/inc/services.inc
src/etc/inc/xmlrpc.inc
src/etc/rc.d/configd
src/opnsense/mvc/app/library/OPNsense/Auth/AuthenticationFactory.php
src/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/AutoNumberField.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php
src/opnsense/mvc/app/models/OPNsense/Base/Menu/MenuItem.php
src/www/firewall_virtual_ip_edit.php
src/www/status_dhcp_leases.php
src/www/system_usermanager_import_ldap.php
src/www/xmlrpc.php

its = possessive (like 'his'/'her'), it's = it is

Fix some typos in comments

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/dialogEditPACRule.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml

www/squid: add proxy sortable support for proxy lists (PAC)

---

src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml

www/squid: add dash to allowed characters

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec.php
src/www/vpn_ipsec_mobile.php
src/www/vpn_ipsec_phase1.php
src/www/vpn_ipsec_phase2.php

curve 25519 is supported in strongswan 5.7.1 and newer

ipsec: added ikev2 dh group 31 / curve 25519

---

src/www/diag_logs_common.inc
src/www/diag_logs_proxy.php

Squid log webUI in readable date format #1831

---

src/www/services_dhcp_edit.php
src/www/services_dhcpv6_edit.php

@AdSchellevis 
Pull request for https://github.com/opnsense/core/issues/2946#issuecomment-493211786
Also edited IPv6 assuming same issue applies there.

Fix dhcp leases help text

---

src/www/interfaces_ppps_edit.php

Only IP-address allowed in PPTP gateway.

---

src/www/firewall_rules.php

This is a proposed solution for:
Feature request: Option to enable logging for all firewall rules at once #3124
I propose this as a superior solution to a single button that enables logging on all policies at once.
Having a logging toggle on each firewall rule allows a nice overview of what policies have logging enabled and which don't, as well as giving the admin the ability to quickly enable logging for all policies that don't currently have it enabled.

Added logging toggle for firewall rules

---

src/www/system_hasync.php

I'd love to rename the label also but this would break all translations so at first only help text :)

High Availablity: update helptext to reality

---

src/etc/rc.d/netflow
src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/forms/netflow_capture.xml
src/opnsense/mvc/app/models/OPNsense/Diagnostics/Netflow.xml
src/opnsense/service/templates/OPNsense/Netflow/netflow.conf

This PR adds active and inactive timout settings for the NetFlow exporter.
Solves #3650

netflow: set active/inactive timeout

---

src/etc/rc.d/netflow

This PR splits the ngctl batch into single commands to have a better error handling.

netflow: improve error handling in rc.d script

---

plist
src/etc/inc/interfaces.inc
src/etc/inc/interfaces.lib.inc
src/etc/inc/plugins.inc.d/core.inc
src/etc/inc/plugins.inc.d/vxlan.inc
src/opnsense/mvc/app/controllers/OPNsense/Interfaces/Api/VxlanSettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Interfaces/VxlanController.php
src/opnsense/mvc/app/controllers/OPNsense/Interfaces/forms/dialogVxlan.xml
src/opnsense/mvc/app/models/OPNsense/Interfaces/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/Interfaces/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/Interfaces/VxLan.php
src/opnsense/mvc/app/models/OPNsense/Interfaces/VxLan.xml
src/opnsense/mvc/app/views/OPNsense/Interface/vxlan.volt
src/opnsense/service/conf/actions.d/actions_interface.conf

Add VXLAN support, hook into newwanip event, skip type in `interfaces_configure()` and move interface configuration into device setup `vxlan_configure_interface()`

VXLAN support

---

src/www/services_router_advertisements.php

Fix range check for advanced radvd options

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/www/services_dhcpv6.php

Follows PR #3909 and fixes #3908

Implement working DHCPv6 DDNS (Dynamic DNS)

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php
src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ArrayField.php

e.g. SORT_NATURAL: 9, 20, 80 rather than 20, 80, 9
Default, SORT_REGULAR, is unchanged.

ArrayField - Add sort_flags optional parameter support

---

src/etc/inc/interfaces.inc

We need to get all of the router info from rtsold so need to add multiple interfaces. Something like this, it works but maybe not the best way.

Add multiple interfaces to rtsold call

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Proxy: add connect_timeout

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt

Update text in Aliases to be more intuitive

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/generalSettings.xml
src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml
src/opnsense/mvc/app/views/OPNsense/IDS/index.volt
src/opnsense/service/templates/OPNsense/IDS/suricata.yaml

https://github.com/opnsense/core/pull/4116

IDPS: Adding Profile Detection

---

src/www/status_graph.php

Add traffic filter for private IPv4 networks.
This is useful if OPNsense in sitting in-front of a layer 3 switch and the networks are defined in the layer 3 switch and not in OPNsense.

Add Traffic Filter for Private IPv4 Networks

---

src/opnsense/scripts/filter/pfinfo.py
src/www/diag_pf_info.php

Hi!
Please, can you add "Nat" tab to pfInfo firewall diagnostics?
Thanks!

Add  "Nat" tab to Firewall->Diagnostics->pfInfo menu

---

src/opnsense/service/conf/actions.d/actions_ipsec.conf

This is a follow-up to https://github.com/opnsense/core/pull/3755.
It was requested in https://github.com/opnsense/plugins/issues/2019.

ipsec: add description to reconfigure action

---

src/www/widgets/widgets/system_information.widget.php

refers to FR: https://github.com/opnsense/core/issues/4480

SysInfo widget: add current CPU load progress-bar

---

src/etc/inc/plugins.inc.d/openvpn.inc
src/www/vpn_openvpn_server.php

https://github.com/opnsense/core/issues/4422#issuecomment-730555859

OpenVPN: added block-outside-dns - ref. issue #4422

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Migrations/M1_0_0.php
src/www/vpn_ipsec_phase2.php

closes https://github.com/opnsense/core/issues/4460

NAT in IPsec with multiple Phase2

---

src/www/services_dhcpv6.php
src/www/system_advanced_network.php

Fix DUID - LL description in Settings | Interfaces

---

src/www/widgets/widgets/log.widget.php

Display the destination port number. V6 not working, according to existing code comments, but it is...

Display dest port number in filter log widget

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasUtilController.php
src/opnsense/scripts/filter/list_table.py

Hi!
PR for https://github.com/opnsense/core/issues/4577
(with minimal changes to the original files)

Diagnostics->pfTables: display zeros, sort columns

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/categoryEdit.xml
src/opnsense/mvc/app/views/OPNsense/Firewall/category.volt

Uppercase of first letter in names.

Filter: Categories: Fixed spelling issues

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/general.xml
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/opnsense/service/templates/OPNsense/Monit/monitrc

* Do not render "stop command" of services to config if not configured
* Add missing service description to model and view
* Clarify various mail server settings in settings view
* Fix spelling in settings view

Monit: minor bugfixes and UI changes

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/networkinsight.volt

Sidebar menu collapsed when clicking link to netflow configuration.

Fix sidebar menu collapse

---

src/opnsense/www/js/opnsense_theme.js

if there is not enough space in a list of links upwards, the list moves down by the number of menu entries. so the problem with too many entries should now be solved. I hope that suits you. if so, please test. Thank you

Sidebar - fix for too long a-link list

---

src/opnsense/scripts/suricata/lib/rulecache.py

Hi!
make manual rules status boolean for comparison results consistency

rulecache.py: make manual rule status boolean

---

src/etc/inc/certs.inc
src/www/system_certmanager.php

Hi.
replaces https://github.com/opnsense/core/pull/4755
closes https://github.com/opnsense/core/issues/4675 i hope

system_certmanager: take extensions out of a DN

---

src/www/firewall_rules.php

Hi.
block\reject rules get wrong color on toggle

firewall_rules.php: Icon color after toggle fix

---

README.md
src/etc/inc/IPv6.inc
src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/SettingsController.php
src/opnsense/scripts/ipsec/vici/compat.py
src/opnsense/scripts/system/ssl_ciphers.py
src/opnsense/service/templates/OPNsense/IDS/reference.config
src/www/diag_packet_capture.php
src/www/interfaces.php
src/www/services_dhcp.php
src/www/services_dhcpv6.php
src/www/services_opendns.php
src/www/status_ntpd.php
src/www/system_hasync.php
src/www/widgets/widgets/ntp_status.widget.php

Ref: https://github.com/EFForg/https-everywhere
```Shell
~/src/EFForg/https-everywhere/utils/rewriter/rewriter.js .
```
A few changes where reset/fixed manually before the commit.

Use HTTPS everywhere (mechanical edit using util from https-everywhere)

---

src/opnsense/mvc/app/views/layouts/default.volt

Hi
it turned out that the translation does not work on IE
https://forum.opnsense.org/index.php?topic=21981.0
thanks!

default.volt: let translation work on IE11

---

src/www/vpn_openvpn_csc.php
src/www/vpn_openvpn_server.php

OpenVPN: remove checks for NTP servers 3 and 4 since only two optional
NTP servers are exposed through the GUI.

OpenVPN: remove checks for NTP servers 3 and 4.

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
src/opnsense/www/js/opnsense_ui.js

Hi
possibly closes https://github.com/opnsense/core/issues/4788
I'm not sure about the separator: I made a `\n`  because I use https://github.com/opnsense/core/issues/4497. Before FR review and in case of refusal, we can make a `,`
Thanks!

MVC View: add copy to mutliselects

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
src/opnsense/www/js/opnsense_ui.js

Hi!
a variant of https://github.com/opnsense/core/pull/4789 with pasting
I do it as a draft so as not to be confused
Thanks!

MVC View: copy|paste on multiselect

---

src/opnsense/scripts/dns/unbound_dhcpd.py

Changes:
* Add PTR records for DHCP endpoints in the correct format
* Delete PTR records when A records are deleted
* Use bulk add/remove requests to unbound-control to improve performance
Testing:
* Created new endpoint and confirmed hostname and reverse lookup worked
* After DHCP entry timed out and DNS entry is removed lookups for hostname and IP fail.
Fixes #4597

unbound: Fix PTR records for DHCP endpoints

---

src/etc/inc/plugins.inc.d/webgui.inc
src/etc/lighttpd_webgui/conf.d/README
src/etc/lighttpd_webgui/conf.d/extforward.conf.example

This PR is to replace #4833 and reflects the feedback as to the preferred approach outlined there. It is intended to address #4638 but in a more generic way that will allow configuration of other lighttpd modules

webgui: lighttpd include directory for configuration

---

src/etc/inc/plugins.inc.d/webgui.inc

Fix syntax error introduced in #4837

webgui.inc: fix syntax error

---

src/www/javascript/opnsense_legacy.js

Hi
javascript throws an error if rule is in one category and category name is a number
Thanks!

fw categories: error if the category name is a number

---

src/www/widgets/widgets/thermal_sensors.widget.php

Allow CPU temp display in Farenheit

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/LvtemplatesController.php
src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/LvtemplatesController.php
src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/forms/dialogTemplate.xml
src/opnsense/mvc/app/models/OPNsense/Diagnostics/Lvtemplates.php
src/opnsense/mvc/app/models/OPNsense/Diagnostics/Lvtemplates.xml
src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt

Hi!
may close https://github.com/opnsense/core/issues/4859
- simple model for storing templates
- managing templates directly on Live View page via api
- MVC view is added but not used in menu. for MVC work debug only
- SORT_FLAG_CASE flag added in API to return case insensitive sorted results (or maybe it makes sense to add this directly to the ApiMutableModelControllerBase?)

Firewall Live View: stored filters templates

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt

Hi!
replaces https://github.com/opnsense/core/pull/4912

Live View: set url-filters after templates load

---

plist
src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.xml
src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/scripts/filter/lib/alias.py
src/opnsense/scripts/filter/lib/interface.py
src/opnsense/service/templates/OPNsense/Filter/filter_tables.conf

supersedes https://github.com/opnsense/core/pull/4941 (incorporating both @marjohn56 and @AdSchellevis additions)
closes https://github.com/opnsense/core/issues/4923

Dynamic Ipv6 fw rules handling Mk II

---

src/opnsense/service/conf/actions.d/actions_webgui.conf

webgui: make restart action usable in cron jobs

---

src/www/diag_dns.php

- query AAAA + A records
- display 'PTR' in type field for reverse lookups
- remove unused `$ipaddr`
- filter SOA record

Diagnostics / DNS Lookup, small improvements

---

src/etc/inc/plugins.inc.d/openvpn/wizard.inc

Hi!
may close https://github.com/opnsense/core/issues/5106 i think
i can add this to https://github.com/opnsense/core/pull/5108

Openvpn: wizard rules creation fix

---

src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasField.php

Fixed the misspelling of limitting to limiting.

Update AliasField.php to fix misspelling of limitting

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/scripts/filter/pftablecount.py

Hi
just small suggestions for https://github.com/opnsense/core/pull/5142#issuecomment-894704862
thanks!

Aliases progress bar: small suggestions

---

src/root/boot/lua/brand-opnsense.lua
src/root/boot/lua/logo-hourglass.lua.in

Note that this is currently dependent on some functionality in upstream e19d9a9b6e44 and ed107537b43c being MFC'd; I'll issue an opnsense/tools PR after I MFC those to stop forcing forthloader.

root: add lualoader brand and logo

---

src/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml

Hi!
Im sorry, completely forgot about it when preparing (
Closes https://github.com/opnsense/core/issues/5326 i hope
Thanks!

Firewall/Live View: add templates ACL

---

src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogPipe.xml
src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogQueue.xml
src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogRule.xml

Some small textual changes which clarify the use of the shaper

Patch traffic shaper texts

---

src/opnsense/scripts/suricata/lib/downloader.py

* minor syntax tweaks
* modified `is_supported` to use a tuple and return the result directly.
* changed conditional.

downloader.py updates

---

src/opnsense/www/js/opnsense_ui.js

Hi!
probably close https://github.com/opnsense/core/issues/5407 
uses `MutationObserver` API to monitor style changes within striped tables. when row visibility changes, the parity of visible rows is adjusted for correct stripes display.
although it may seem horrible from a performance standpoint (observe for any "style" attribute changes in all `.table-striped` tables on the page for the sake of row parity control), no performance impact was noticed.
Thanks!

MVC - initFormAdvancedUI: universal stripes adjustment

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt

Hi!
simplified version of Live View html special chars display support
(ref. https://github.com/opnsense/core/issues/5432#issuecomment-1003353407)
Thanks!

Firewall: Log Files: Live View - simplify previous

---

src/etc/inc/plugins.inc.d/ntpd.inc
src/www/services_ntpd.php
src/www/widgets/api/plugins/system.inc

Hi @fichtner,
This is the PR to address [issue #5470](https://github.com/opnsense/core/issues/5470)
I am not a regular github user so I hope that you can extract something useful from this PR.

services/ntp - detach limited from kod, correct help text

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php

resolves https://github.com/opnsense/core/issues/5496

BaseField: Overload __isset() magic method

---

src/opnsense/mvc/app/library/OPNsense/Firewall/FilterRule.php
src/www/firewall_rules_edit.php

https://github.com/opnsense/core/pull/5492

Fr5487 adaptive timeouts

---

src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/mvc/app/views/OPNsense/Unbound/overrides.volt

Addresses the change in https://github.com/opnsense/core/commit/308b31dfa84943c0d3487f23c53e8bb10a819222

Unbound: overrides: fixup UI and validation due to model change

---

src/opnsense/www/js/opnsense_theme.js

sidebar - 2nd submenu view fix

---

src/opnsense/www/js/opnsense_theme.js

Removed unnecessary code for better performance

sidebar - optimization

---

src/opnsense/www/js/opnsense_theme.js

i can´t get all code optimizatied (please it´s important to merge this, because of big trouble with scrolling) - no more fixes after this needed. sorry

sidebar - refresh optimization last fix

---

src/etc/inc/util.inc

Hi!
as discussed at https://github.com/opnsense/core/pull/5541
thanks!

util: change log_msg default severity level

---

src/opnsense/scripts/systemhealth/logformats/squid.py

Hi!
looks like a little typo?
ref. https://forum.opnsense.org/index.php?topic=26593.msg130828#msg130828
thanks!

squidExtLogFormat: typo

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/LogController.php
src/opnsense/mvc/app/views/OPNsense/Diagnostics/log.volt

Hi!
replaces https://github.com/opnsense/core/pull/5587
Hope I got the idea right.
Although I still see some race condition when changing the severity filter quickly (without locking it on change), at least it doesn't completely block gui and doesn't drain php memory.
Thanks!

Logs: limit rowCount

---

src/etc/inc/filter.lib.inc

firewall: dont log localhost rule

---

src/etc/inc/auth.inc
src/opnsense/mvc/app/library/OPNsense/Auth/API.php
src/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php
src/www/system_advanced_network.php
src/www/system_usermanager.php
src/www/system_usermanager_passwordmg.php

As mentioned in #5658, this pull request additionally simplifies the voucher generation.

Optional addition to #5658, simplifies the voucher generation

---

src/opnsense/service/templates/OPNsense/Unbound/core/blocklists.conf

---
name: Issue Report
about: Blocklist in Unbound
title: ''
labels: ''
assignees: ''
---
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
**Describe the bug**
The old blocklist isn't up to date anymore.
**To Reproduce**
Check here: https://github.com/keraf/NoCoin
**Describe alternatives you considered**
New list or remove NoCoin as most browsers implement technologies against mining.

Update blocklists.conf (NoCoin)

---

src/opnsense/mvc/app/library/OPNsense/Core/Config.php

Fixes https://github.com/opnsense/plugins/issues/2958

Config::save : call microtime(true) once

---

src/www/system_general.php

Grammatical error - period missing.

Fix grammar. Missing period.

---

src/etc/inc/filter.inc
src/etc/inc/plugins.inc.d/core.inc
src/etc/inc/plugins.inc.d/pf.inc
src/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml
src/opnsense/scripts/filter/update_tables.py

Facilitates https://github.com/opnsense/core/pull/5875 to notify users in a better defined context.

Firewall: redirect alias syslog messages to new general firewall log

---

src/etc/inc/plugins.inc.d/dhcpd.inc

https://github.com/opnsense/core/issues/5919

core/radvd - do not advertise DNS domain when DNS advertisments are disabled

---

src/etc/inc/certs.inc

Hi!
sorry, my bad.
revoked cert validating at this point, not CA
Thanks!

certs.inc: misleading message

---

contrib/simplepie/library/SimplePie/Parse/Date.php

Hi
should close https://github.com/opnsense/core/issues/6043 imho
Thanks!

simplepie: type cast

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/OverviewController.php
src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
src/opnsense/scripts/unbound/stats.py
src/opnsense/service/conf/actions.d/actions_unbound.conf
src/opnsense/service/templates/OPNsense/Unbound/core/dnsbl_module.py
src/opnsense/www/css/dns-overview.css

Include the option to set all charts to a logarithmic scale as well to better visualize outliers.

unbound: add client activity chart

---

src/opnsense/scripts/unbound/blocklists.py

Hi!
just updating the total record count source )
thanks!

unbound: typo

---

src/opnsense/mvc/app/views/OPNsense/Core/firmware.volt

fixes Updates tab behavior after checking for updates.
ref. https://github.com/opnsense/core/issues/5635#issuecomment-1396823926
sorry for the inattention (

firmware.volt: fix regression in previous. typo

---

src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
src/opnsense/www/css/dns-overview.css

Hi!
ref (FR). https://forum.opnsense.org/index.php?topic=32127.msg155337#msg155337
Grid truncate fqdn with ellipsis if it does not fit.
pr tries to add tooltip to fqdn ('Domain') cell.
fix buttons tooltips also.
Thanks!

Reporting: Unbound - add tooltip to Domain cell

---

src/etc/inc/filter.lib.inc
src/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php
src/opnsense/mvc/app/library/OPNsense/Firewall/Rule.php
src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml
src/www/firewall_rules.php

closes https://github.com/opnsense/core/issues/6258

Firewall/Rules - show all applicable rules when showing an interface

---

src/www/widgets/widgets/openvpn.widget.php

Hi!
https://github.com/opnsense/core/pull/6438 backport
(cherry picked from commit 9473b40e9a8df5b11082e6aa4450562044948a2e)

Dashboard / widgets / OpenVPN - typo (#6438)

---

src/www/firewall_schedule.php
src/www/firewall_schedule_edit.php

Firewall Schedules - Resolves #6348 & #6349

---

src/www/system_groupmanager.php

Hi!
ref. https://forum.opnsense.org/index.php?topic=33413.0
looks like a typo
Thanks

system_groupmanager.php: typo

---

SECURITY.md
src/www/javascript/opnsense_legacy.js
src/www/system_advanced_firewall.php
src/www/system_certmanager.php

I read quickly all www files with vscode spell checker enabled and found some minor typos. One is in a translation string

Fix some typos

---

plist
src/etc/rc.syshook.d/start/90-openvpn
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ServiceController.php
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogInstance.xml
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml
src/opnsense/mvc/app/views/OPNsense/OpenVPN/status.volt
src/opnsense/scripts/openvpn/ovpn_service_control.php
src/opnsense/scripts/openvpn/tls_verify.php

bugfixes and additions:
o fix lookup in tls_verify.php
o add auth attribute
o fix connection status reporting non existing clients
o add missing syshook for startup at boot
o show instances in connection states when not connected

VPN: OpenVPN: Instances (MVC)

---

src/www/widgets/widgets/system_log.widget.php

Hi!
FR ref (sort of) : https://forum.opnsense.org/index.php?topic=31560.msg152374#msg152374
System Log widget can be used to monitor and react to important events. Probably an additional Severity filter would be useful (especially since the data is already coming from the backend)?
PR tries to add the severity filter.
plus:
fixed weird typos in tags.
use selectpicker for selects
a uniform code is used to fill the selects.
empty result message is aligned with the same in log grids
Thanks!

Lobby/Dashboard/System Log widget - add severity filter

---

plist
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseListField.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Migrations/M1_0_5.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Migrations/M1_0_8.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/mvc/tests/app/models/OPNsense/Base/FieldTypes/OptionFieldTest.php

unbound: migrate active/outgoing interfaces discarding invalid values

---

src/etc/inc/filter.inc
src/etc/inc/xmlrpc.inc
src/etc/rc.filter_synchronize
src/man/man8/ifctl.8
src/man/man8/opnsense-crypt.8
src/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/DHCPv6/Api/LeasesController.php
src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasUtilController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogConnection.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogSPD.xml
src/opnsense/mvc/app/controllers/OPNsense/Syslog/forms/dialogDestination.xml
src/opnsense/mvc/app/library/OPNsense/Auth/AuthenticationFactory.php
src/opnsense/mvc/app/library/OPNsense/Auth/Base.php
src/opnsense/mvc/app/library/OPNsense/Auth/TOTP.php

Corrected some typos on several files

Corrected some typos

---

src/opnsense/mvc/tests/app/models/OPNsense/Base/Constraints/UniqueConstraintTest.php

Since UniqueConstraint was worked on recently, some test cases to accomodate all scenarios

UniqueConstraint: add test cases

---

src/opnsense/mvc/app/models/OPNsense/Base/Constraints/DependConstraint.php
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/mvc/tests/app/models/OPNsense/Base/FieldTypes/TextFieldTest.php
src/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py
src/opnsense/scripts/filter/lib/alias/pf.py
src/opnsense/scripts/firmware/health.sh
src/opnsense/scripts/interfaces/mpd.script
src/opnsense/scripts/openvpn/ovpn_service_control.php
src/opnsense/scripts/openvpn/user_pass_verify.php
src/opnsense/scripts/suricata/lib/metadata.py
src/opnsense/service/templates/OPNsense/IDS/suricata.yaml
src/opnsense/service/templates/OPNsense/Syslog/local/README
src/opnsense/www/js/bootstrap-select.js
src/opnsense/www/js/bootstrap3-typeahead.js
src/opnsense/www/js/jquery-sortable.js
src/opnsense/www/js/jquery.bootgrid.js
src/opnsense/www/js/tokenize2.js
src/opnsense/www/themes/opnsense/assets/stylesheets/bootstrap/_forms.scss
src/www/services_ntpd.php

Multiple text corrections

---

src/opnsense/mvc/app/models/OPNsense/Routing/Gateways.php
src/opnsense/mvc/app/models/OPNsense/Routing/Migrations/M1_0_0.php

dpinger: improve validation for 'time period'

---

src/opnsense/service/templates/OPNsense/Unbound/core/access_lists.conf

Fixes https://github.com/opnsense/core/issues/6986

Remove localhost from automatically created Unbound ACL (#6986)

---

src/opnsense/scripts/suricata/metadata/rules/sslbl.xml

Use ruleset using sticky buffers coming with performance increase compared to the standard ruleset currently set.
See https://urlhaus.abuse.ch/api/#ids
Change tested on my device and working

urlhaus suricata ruleset update

---

src/opnsense/mvc/app/views/OPNsense/OpenVPN/status.volt
src/www/widgets/widgets/openvpn.widget.php

This patch adds support for displaying IPv6 addresses for OpenVPN in the OpenVPN widget as well as on the OpenVPN Connection Status page

Add IPv6 to OpenVPN widget and status page

---

plist
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/IPPortField.php
src/opnsense/mvc/app/models/OPNsense/Diagnostics/Netflow.xml
src/opnsense/mvc/tests/app/models/OPNsense/Base/FieldTypes/IPPortFieldTest.php

Useful for Netflow and plugins. Tests included.

MVC: Add IPPortField type

---

src/www/interfaces.php

@AdSchellevis what do you think about this wording tweak?

interfaces: tweak wording in interface gateway selection

---

src/opnsense/mvc/app/controllers/OPNsense/Core/Api/DashboardController.php
src/opnsense/www/js/widgets/IpsecLeases.js
src/opnsense/www/js/widgets/IpsecTunnels.js

- Adds a new Dashboard widget that shows current online mobile users, sorted by online status, with all of their IP addresses.
- When one of these IP addresses for a user has an online lease status, the user will be shown online
- When IPsec is disabled, an error message with embedded link is shown
Some Data to test it:
```
/usr/local/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/LeasesController.php
```
<details>
```
/**
* list pools
* Returns static test data for leases and pools.
* @return array
*/
public function poolsAction()
{
$this->sessionClose();
// Static test data for pools and leases
$testData = [
"pools" => [
"pool-rw-ipv4" => [
"name" => "pool-rw-ipv4",
"net" => "172.16.203.0",
"online" => 1,
"offline" => 0,
"size" => 254
],
"pool-rw-ipv6" => [
"name" => "pool-rw-ipv6", …
```

Dashboard: Add IPsec Leases Widget

---

src/www/system_usermanager.php

Adding aria-label attribute to buttons in users table.

users: Add accessibility labels to user manager table

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt

removes aria-hidden from add/edit alias modal.

firewall: removed aria-hidden on add/edit alias

---

src/opnsense/www/js/opnsense_theme.js

@fichtner everytime i tried to update a few things i get in an error and had to fork the whole repro againg to get rid of this . don´t know why. so i decided a last time with all fixes to reupload the whole pr again. thats it no more fixes needed. all testet all works. im really really sorry for that. regards rené

Sidebar - optimisation and fixes

---

src/opnsense/www/js/widgets/IpsecTunnels.js
src/opnsense/www/js/widgets/Metadata/Core.xml

Requires: https://github.com/opnsense/core/commit/809e3be395a5681480fc5dcb5c67a692613546c1
Fixes: https://github.com/opnsense/core/issues/7708

dashboard: IpsecTunnels.js - Add aggregated information about connected children.

---

src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt

PR: https://forum.opnsense.org/index.php?topic=42004.0

wireguard: Change add button to btn-primary

---

src/opnsense/www/js/widgets/Metadata/Core.xml
src/opnsense/www/js/widgets/Monit.js

Fixes: https://github.com/opnsense/core/issues/7719

dashboard: Monit.js - Change status code handling

---

src/opnsense/mvc/app/controllers/OPNsense/BootEnvironments/Api/GeneralController.php

check boot environment to delete is not in any active state

System: Boot Environments - Addtional cleanups and restructures

---

src/opnsense/www/js/widgets/BaseWidget.js
src/opnsense/www/js/widgets/IpsecLeases.js
src/opnsense/www/js/widgets/IpsecTunnels.js
src/opnsense/www/js/widgets/Metadata/Core.xml
src/opnsense/www/js/widgets/Wireguard.js

Fixes: https://github.com/opnsense/core/issues/7739

dashboard: Improve Wireguard and IPsec Widgets

---

src/opnsense/mvc/app/controllers/OPNsense/Routing/forms/dialogEditGateway.xml

Changed in  https://github.com/opnsense/core/commit/044b0d9ad909b7b8ed85d57996693292d999a907

Fix Data Length help text to reflect the current default value

---

src/opnsense/www/js/opnsense_theme.js

Fixes the problem that the submenu does not remain expanded if the focus remains on the menu item.

Sidebar - submenu expand problem

---

plist
src/etc/inc/interfaces.inc
src/opnsense/mvc/app/controllers/OPNsense/Core/forms/hasyncSettings.xml
src/opnsense/mvc/app/models/OPNsense/Core/Hasync.xml
src/opnsense/mvc/app/models/OPNsense/Core/Migrations/MHA1_0_1.php

PR: https://forum.opnsense.org/index.php?topic=42549.0
I did not test this yet so for immediate review only.

system: handle stale "pfsyncinterfaces" and improve workflow

---

src/etc/inc/plugins.inc.d/ntpd.inc
src/www/services_ntpd.php
src/www/status_ntpd.php

See https://github.com/opnsense/core/issues/7832

Enable restrict noquery by default for ntpd

---

src/opnsense/www/js/widgets/Wireguard.js

... to ensure uniqueness when public keys are reused.
Fixes: https://github.com/opnsense/core/issues/7812

dashboard: Construct Wireguard.js row ID from if+public-key

---

src/etc/inc/plugins.inc.d/dpinger.inc
src/etc/inc/system.inc

Same as https://github.com/opnsense/core/commit/a85bd197c2d2179d80b9f528ddda5f8799351748 really, this callout also seems to gobble up a lot of unnecessary time on bigger systems.

system: make dpinger_configure_do map aware

---

src/opnsense/scripts/firmware/repos/OPNsense.php

Parking this as a PR for next week.

firmware: remove escaped slashes workaround, works since 24.7.5

---

src/opnsense/service/modules/addons/template_helpers.py

fix: Correct template helper exists() return type

---

src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/settings.xml

Fixes: https://forum.opnsense.org/index.php?topic=43303

ipsec: Fix advanced option max_ikev1_exchanges, changed checkbox to text and general to charon

---

src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CrlController.php

Fix check empty condition before populate the variable.

Fix crt condition in setCRL

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/treeview.volt

Fixes: https://github.com/opnsense/core/issues/7938

diagnostics/treeview: Fix style targeting elements outside this view

---

src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/PreSharedKeysController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogPSK.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml
src/opnsense/mvc/app/views/OPNsense/IPsec/pre_shared_keys.volt

Fixes: https://github.com/opnsense/core/issues/8014

vpn: ipsec: Add description field to pre-shared-keys

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/log.volt
src/opnsense/mvc/app/views/OPNsense/IPsec/sessions.volt

Requires the plumping of the following PR to work: https://github.com/opnsense/core/pull/8115

vpn/ipsec: Add log search button in sessions

---

src/opnsense/mvc/app/controllers/OPNsense/DHCRelay/RelayController.php
src/opnsense/mvc/app/controllers/OPNsense/DHCRelay/forms/dialogRelay.xml
src/opnsense/mvc/app/views/OPNsense/DHCRelay/relay.volt

Requires: https://github.com/opnsense/core/issues/8187

dhcp/dhcrelay: Integrate layout_partials/base_bootgrid_table

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/AclController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/DotController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/ForwardController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/OverridesController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogAcl.xml
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogDot.xml
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogHostAlias.xml
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogHostOverride.xml
src/opnsense/mvc/app/views/OPNsense/Unbound/acl.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/dot.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/overrides.volt

Requires: https://github.com/opnsense/core/issues/8187
Will be one commit per changed volt page.

dns/unbound: Integrate layout_partials/base_bootgrid_table

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/DhcpController.php
src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet4.xml
src/opnsense/mvc/app/views/OPNsense/Kea/dhcpv4.volt

Requires: https://github.com/opnsense/core/issues/8187

dhcp/kea: Integrate layout_partials/base_bootgrid_table

---

src/opnsense/mvc/app/controllers/OPNsense/DHCRelay/RelayController.php
src/opnsense/mvc/app/views/OPNsense/DHCRelay/relay.volt

Requires: https://github.com/opnsense/core/issues/8284

dhcp/dhcrelay: Integrate layout_partials/base_apply_button

---

src/opnsense/mvc/app/views/OPNsense/Core/tunables.volt

Requires: https://github.com/opnsense/core/issues/8284

core/tunables: Integrate layout_partials/base_apply_button

---

src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServiceController.php
src/opnsense/mvc/app/views/OPNsense/Wireguard/diagnostics.volt
src/opnsense/www/js/widgets/Metadata/Core.xml
src/opnsense/www/js/widgets/Wireguard.js

...to calculate if tunnel is online in backend. Implement it in wireguard.js widget and diagnostics.volt
Fixes: https://github.com/opnsense/core/issues/8335

vpn/wireguard: Change tracking of wg peer status, improve widget and diagnostics

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/AclController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/DotController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/ForwardController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/OverridesController.php
src/opnsense/mvc/app/views/OPNsense/Unbound/acl.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/advanced.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/dnsbl.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/dot.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/general.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/overrides.volt

Requires: https://github.com/opnsense/core/issues/8284

dns/unbound: Integrate layout_partials/base_apply_button

---

src/opnsense/mvc/app/views/OPNsense/DHCRelay/relay.volt

Regression from: https://github.com/opnsense/core/commit/a556e10d06b16576b2c98bbba6014242d5854441

dhcrelay: Add missing status column

---

src/opnsense/mvc/app/controllers/OPNsense/Interfaces/forms/dialogVip.xml

Fixes: https://github.com/opnsense/core/issues/8387

interface/vip: Adjust help text for nosync option

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/health.volt

Granularity default selector item consistency with other items.

reporting: granularity default item label tweak

---

src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml
src/opnsense/service/templates/OPNsense/IDS/suricata.yaml

Suricata: Add JA4 support

---

src/opnsense/mvc/app/views/OPNsense/Interface/vip.volt

Fixes: https://github.com/opnsense/core/issues/8451

interfaces/vip: Fix advanced mode visibility

---

src/opnsense/www/js/widgets/OpenVPNClients.js

I added simple comments for the changes in #8476 for better code documentation.

add comments for #8476

---

src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt
src/opnsense/www/css/jquery.bootgrid.css
src/opnsense/www/js/jquery.bootgrid.js
src/opnsense/www/themes/opnsense-dark/build/css/jquery.bootgrid.css

Bootgrid option: `resizableColumns`: `true` (default false)

bootgrid: resizable columns

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8499

dnsmasq: Change add_mac OptionValue from default to standard to satisfy lint

---

src/opnsense/mvc/app/models/OPNsense/Kea/ACL/ACL.xml

Fixes: https://github.com/opnsense/core/issues/8518

kea: Fix missing ACL privileges

---

src/opnsense/www/js/widgets/Certificates.js

A few minor adjustments for: https://github.com/opnsense/core/commit/f90e5445db69de5177f97048e440400a1393b424
The current hidden certificate configuration will be invalidated due to this change as the key/value pair was description, an oversight by my earlier me.

dashboard: Certificates.js adjustments for f90e544

---

src/etc/inc/plugins.inc.d/dpinger.inc
src/etc/rc.syshook.d/monitor/20-recover
src/opnsense/mvc/app/controllers/OPNsense/Routing/forms/dialogEditGateway.xml
src/opnsense/mvc/app/models/OPNsense/Routing/Gateways.xml

for https://github.com/opnsense/core/issues/6803
This is usually practical for "metered" connections where traffic is expensive.

System: Gateways - kill opposite states when a gateway "up" is triggered

---

src/opnsense/mvc/app/config/config.php
src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/CountryField.php
src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php
src/opnsense/mvc/tests/app/config/config.php
src/www/getserviceproviders.php

Add contribDir to app config

---

src/opnsense/mvc/app/controllers/OPNsense/Routing/forms/dialogEditGateway.xml

system: work on states kill wording

---

src/opnsense/mvc/app/views/OPNsense/Dnsmasq/leases.volt
src/opnsense/scripts/dhcp/get_dnsmasq_leases.py

For: https://github.com/opnsense/core/issues/8643

dnsmasq: Split up hwaddr and iaid for dhcpv6 leases, expose iaid and duid in leases overview

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/LeasesController.php
src/opnsense/mvc/app/views/OPNsense/Dnsmasq/leases.volt

For: https://github.com/opnsense/core/issues/8643

dnsmasq: Add protocol selectpicker to leases view

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8671

dnsmasq: Allow lease_time 0 to set it infinite

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8675

dnsmasq: Add interface tag to dhcp boot options

---

src/etc/inc/plugins.inc.d/dnsmasq.inc

Fixes: https://github.com/opnsense/core/issues/8694
Another possible minimal fix for the issue referred to in that ticket.

dnsmasq: Create static host entries for all except partial IPv6 addresses

---

src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

PR: https://forum.opnsense.org/index.php?topic=47221.msg237962#msg237962

dnsmasq: Fix physical interface in dhcp-boot

---

src/etc/inc/plugins.inc.d/dnsmasq.inc
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8731

dnsmasq: Fix wildcard host handling

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php

PR: https://www.reddit.com/r/opnsense/comments/1lcs57s/isc_dhcpv4_will_be_removed_in_favor_of_dnsmasqkea/

dnsmasq: dhcp-host are allowed to have duplicate partial IPv6 addresses

---

src/opnsense/mvc/app/views/OPNsense/CaptivePortal/index.volt
src/opnsense/mvc/app/views/OPNsense/Cron/index.volt
src/opnsense/mvc/app/views/OPNsense/DHCRelay/relay.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/arp.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/netflow.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/networkinsight.volt
src/opnsense/mvc/app/views/OPNsense/Diagnostics/systemactivity.volt
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/mvc/app/views/OPNsense/Firewall/category.volt
src/opnsense/mvc/app/views/OPNsense/Firewall/group.volt
src/opnsense/mvc/app/views/OPNsense/IDS/index.volt
src/opnsense/mvc/app/views/OPNsense/IDS/policy.volt
src/opnsense/mvc/app/views/OPNsense/IPsec/key_pairs.volt
src/opnsense/mvc/app/views/OPNsense/IPsec/tunnels.volt
src/opnsense/mvc/app/views/OPNsense/Interface/lagg.volt
src/opnsense/mvc/app/views/OPNsense/Interface/overview.volt
src/opnsense/mvc/app/views/OPNsense/Syslog/index.volt
src/opnsense/mvc/app/views/OPNsense/TrafficShaper/index.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/acl.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/dot.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/general.volt
src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt

Fixes: https://github.com/opnsense/core/issues/8306

mvc: Replace camelCase API notation with snake_case, some more spots that were missed

---

src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt

PR: https://forum.opnsense.org/index.php?topic=47731.0

firewall/automation: Fix issue with event binding

---

src/opnsense/mvc/app/controllers/OPNsense/Core/SnapshotsController.php
src/opnsense/mvc/app/controllers/OPNsense/Core/forms/snapshot.xml
src/opnsense/mvc/app/views/OPNsense/Core/snapshot.volt
src/opnsense/mvc/app/views/layout_partials/base_bootgrid_table.volt

Delete button is hidden with a new parameter in the base_bootgrid_table

snapshots: Implement base_bootgrid_table

---

src/opnsense/mvc/app/views/OPNsense/Core/hasync.volt
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/mvc/app/views/OPNsense/Firewall/filter.volt
src/opnsense/mvc/app/views/OPNsense/IPsec/settings.volt
src/opnsense/mvc/app/views/OPNsense/Kea/ctrl_agent.volt
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/opnsense/mvc/app/views/OPNsense/Trust/settings.volt

This will not be squashed, its one commit per button that has been changed.
For: https://github.com/opnsense/core/issues/8318

Replace most apply buttons with base_apply_button

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/PolicyController.php
src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/dialogPolicy.xml
src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/dialogPolicyRule.xml
src/opnsense/mvc/app/views/OPNsense/IDS/policy.volt

This just changes policy.volt.
index.volt is too special for a quick overhaul.

ids/policy: Implement base_bootgrid_table and base_apply_button

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/ServiceController.php
src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php

Follow up for: https://github.com/opnsense/core/commit/f4bef1f530d76d23a5a485d52c0548a9e75ba979

monit: Remove dirty subsystem checks as base_apply_button does not track that

---

src/opnsense/www/js/opnsense_ui.js

Persist checkmark long enough to ensure a new keyframe in remote desktop streaming tools can update the change.
Fixes: https://github.com/opnsense/core/issues/8647

ui: Add checkmark to SimpleActionButton as additional indicator

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php

For: https://github.com/opnsense/core/commit/30277015f458c067ef5a561517e3fd9e46210c41

dnsmasq: Implement getValues() consistently in dnsmasq.php

---

src/opnsense/mvc/app/views/OPNsense/Core/tunables.volt

PR: https://forum.opnsense.org/index.php?topic=48019

tunables: Fix tunable default reset button

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDomainOverride.xml
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml

dnsmasq: Fix case of labels and some help texts

---

src/opnsense/mvc/app/views/OPNsense/IPsec/tunnels.volt

Fixes phase 1 add button not working

ipsec/legacy: Remove data action from button so attach_legacy_actions can attach its own event

---

src/opnsense/mvc/app/views/OPNsense/TrafficShaper/index.volt

Fixes: https://forum.opnsense.org/index.php?topic=48518.0

trafficshaper: Attach click handler after flushAct button exists

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/FilterController.php
src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt

Fixes https://github.com/opnsense/core/commit/dbcb15033af14647e756820e84f1724f7e153be5
Fixes https://github.com/opnsense/core/issues/9127
Example output:
```
{
"uuid": "ff9a466d-c5c6-4db5-8e9f-39b8bdc17f48",
"enabled": "1",
"statetype": "keep",
"%statetype": "keep state",
"state-policy": "",
"sequence": "6400",
"sort_order": "200000.0006400",
"prio_group": "200000",
"action": "pass",
"%action": "Pass",
"quick": "1",
"interfacenot": "0",
"interface": "",
"direction": "in",
"%direction": "In",
"ipprotocol": "inet",
"%ipprotocol": "IPv4",
"protocol": "TCP\/UDP",
"icmptype": "",
"source_net": "RFC1918,NewTestAlias,unbound_cloudflare_com,lan,opt4ip,opt5,opt6,opt6ip,opt8ip,opt9,opt9ip,TEST_GRP,opt12ip",
"%source_net": "RFC1918, NewTestAlias, unbound_cloudflare_com, LAN net, lo3 address, lo4 …
```

firewall/automation: Fall back to translated values for non-aliases

---

src/opnsense/mvc/app/views/OPNsense/Core/hasync_status.volt

Fixes: https://github.com/opnsense/core/issues/9248

core/hasync: Fix reconfigure control on small viewports

---

src/etc/inc/filter.inc
src/etc/inc/system.inc
src/www/system_advanced_firewall.php

While here simplify the code and rename the functions.

firewall: adapt default table size for #9110
