opnsense/core

src/www/interfaces_assign.php

This is a temporary solution to allow using sixxs-aiccu service without
manual code change until the aiccu service is correctly included in the
web interface (issue #57).

added tun0 interface in interface assign (required for sixxs-aiccu)

---

src/etc/inc/filter.inc
src/www/vpn_ipsec_phase2.php

This PR adds an option to manually configure the NAT type for IPsec. It's fallback is to use the "auto" mode (to match the previous behaviour), so it shouldn't break anything for existing configurations.
This resolves issue #485.

fixes #485: make NAT type configurable for IPsec

---

src/www/status_dhcp_leases.php
src/www/status_dhcpv6_leases.php

This PR enhances the `Status->DHCP IPv4 Leases` and `Status->DHCP IPv6 Leases` pages by adding the description of the static lease (if available).

Fixes 376: add description for status DHCP leases

---

src/www/firewall_rules.php

If IPv6 is not enabled in global networking settings, show the implicitly
generated IPv6 block rule in floating firewall rules.
See also [this forum post](https://forum.opnsense.org/index.php?topic=1777.0).

firewall: show implicit IPv6 block rule if IPv6 disabled

---

src/opnsense/scripts/filter/pfinfo.py
src/www/diag_pf_info.php

Extends pfInfo by showing active rules incl. match statistics.
Especially for troubleshooting the generated rules by OPNsense are quite useful.

firewall: extend pfInfo by active rules

---

src/www/services_unbound.php

If unbound is enabled/disabled globally, the interface selectors should be
enabled/disabled as well.

tiny bugfix: unbound: fix JS to enable/disable interface selectors

---

src/www/system_gateways.php

Currently the descriptions for gateways are not visible in `System -> Gateways -> All`, but can still be seen when editing a gateway. This patch brings back the gateway descriptions.
I think they got lost during [a code cleanup](https://github.com/opnsense/core/commit/a453828f3abd249892cf980eed1f62456973e71f#diff-a544724430f51cdfcf966a33f5b8549f).

bring back gateway descriptions

---

src/www/firewall_rules_edit.php

In `Firewall->Rules->Edit` the option "Source / Invert" is erroneously labeled "Destination / Invert". This patch corrects the label.

fix label for option Source/Invert

---

src/etc/inc/load_balancer_maintable.inc
src/www/widgets/widgets/load_balancer_status.widget.php

Currently loadbalancer descriptions are configured with white (#FFFFFF) font. :-) This patch removes the `<font>` tags and relies on CSS to provide the required font color.

bring back loadbalancer descriptions

---

src/www/diag_logs_filter.php
src/www/diag_logs_filter_dynamic.php
src/www/diag_logs_filter_plain.php
src/www/diag_logs_filter_summary.php
src/www/diag_pf_info.php
src/www/firewall_nat.php
src/www/firewall_nat_1to1.php
src/www/firewall_nat_npt.php
src/www/firewall_nat_out.php
src/www/firewall_rules.php
src/www/guiconfig.inc
src/www/status_filter_reload.php

If firewall is globally disabled, show a warning banner in all relevant
firewall configuration and diagnostic screens (filter and NAT).

firewall: show warning banner if firewall disabled

---

src/www/firewall_nat.php
src/www/firewall_nat_1to1.php
src/www/firewall_nat_npt.php
src/www/firewall_nat_out.php
src/www/firewall_rules.php
src/www/firewall_schedule.php
src/www/firewall_virtual_ip.php
src/www/system_gateway_groups.php
src/www/system_gateways.php
src/www/system_routes.php
src/www/vpn_ipsec.php

Reworked action buttons of several lists:
* IPsec phase 1 and phase 2 entries
* Firewall rules
* NAT rules (all 4 pages)
* Firewall schedules
* Virtual IPs
* Gateways
* Gateway groups
* Routes
Changes applied (to each page):
* Changed plus icon of "add new item based on this one" to a clone icon; changed text to "clone item" (#606)
* Applied consistent button order of move, remove, add, clone
* Changed tooltips "click to toggle enable/disable rule" to "disable rule" and "enable rule" corresponding to the current state, respectively
* Added missing tooltips for buttons
Additionally the title of the manual NAT rules table was changed from "Mappings" to "Manual rules", since the automatically generated rules are called "Automatic rules" and also the NAT mode only uses the word "rules" and …

Reworked action buttons for list operations

---

src/etc/inc/unbound.inc

The option to register DHCP leases within unbound DNS was configurable via
DNS Resolver GUI, but the setting was ignored. DHCP leases were always applied.
There is still a bug in the "register DHCP leases in DNS" feature which might be related to this, but I'm not yet sure if it's a bug in the dhcpd or in unbound config generators: #624

unbound: Fix "register DHCP leases in DNS" config option

---

src/www/system_camanager.php

Found a bug while working on something else: Internal intermediate CAs were not correctly referred back to the signing CA.

CA Generation: fix internal intermediate CA creation

---

src/etc/inc/openvpn-client-export.inc

Addresses #653
I think this PR requires some more testing, since the modified function is used for several different client packages to be exported. I only tested some of them, maybe someone can help with testing the Windows Installers?
Generally, the [OpenVPN man page](https://openvpn.net/index.php/open-source/documentation/manuals/65-openvpn-20x-manpage.html) states:
> `--ca file`
> `Certificate authority (CA) file in .pem format, also referred to as the root certificate. This file can have multiple certificates in .pem format, concatenated together.`
So _theoretically_ there should not be a problem with any implementation...

OpenVPN Client Export: add CA chain to CA certificates

---

src/etc/inc/filter_log.inc

Intentional IGMP log messages dropped because the packets did not have source and destination set.

Firewall log not dispalaying intentionally logged IGMP packets

---

src/www/status_services.php

@fichtner In contrast to my original report in #780, a manual start/restart of the relayd service will disrupt network traffic too. Maybe this is a very specific edge case in my OPNsense setup/configuration, but adding a filter_configure() fixes this too.

fix relayd startup/restart (ref #780)

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/NetworkField.php
src/opnsense/mvc/app/models/OPNsense/Base/Validators/NetworkValidator.php

If I need to ensure that user enters the ip with netmask into network field, I can use `<NetMaskRequired>Y</NetMaskRequired>` in my model.

Add NetMaskRequired option into NetworkField and NetworkValidator

---

src/etc/inc/system.inc
src/etc/inc/unbound.inc
src/opnsense/scripts/dns/unbound_dhcpd.py
src/site-python/__init__.py
src/site-python/daemonize.LICENSE
src/site-python/daemonize.py
src/site-python/params.py
src/site-python/watchers/dhcpd.py
src/www/services_unbound.php

Refactor Unbound + dhcp leases, removes the /etc/hosts parsing and add a watcher daemon. 
Shareable components have been placed in src/site-python/, which may be used by the other scripts as well (todo).

Unbound dhcpd

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/CertificateField.php

Basically the same as #869, but this time for CertificateField. This functionality is required for SNI-capable services/plugins and thus support multiple certs at once.

support multiple values in CertificateField

---

src/www/diag_defaults.php

Probably home users would call their device "router", while professional users with the stronger systems would call their device "firewall". I opted for a more neutral expression here, "device" sounds too technical in my opinion.

Language correction: more generic expression

---

src/etc/inc/filter.inc

Rules using "Interface Address" as the NAT target IP did not select the
IPv6 address when generating the rule

Fix IPv6 Outbound NAT

---

src/etc/inc/filter.inc

It appears that the custom normalization rules do not function unless "disable interface scrub" is enabled.
This is simply because the "interface scrub" rules appear before the custom rules, and since they match all traffic on each interface, the custom scrub rules are never reached.
This patch puts the custom rules first.

Put custom scrub rules first

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/CertificateField.php

Currently the `CertificateField` is limited to types `ca` and `cert`. This patch allows to use type `crl` too.
Use case: advanced certificate validation in HAProxy plugin.
Is related to #1095 and not useful (for my use case) until the referenced bug is fixed.

allow to use CRLs with CertificateField

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml

k = kilo (1000 or 1024)
B = byte
b = bit
K = nothing
So kilobyte is kB (was written as Kb in the form)
And kilobit per second is kbps not Kbps.

Incorrect units capitalization in proxy form

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableTableModelControllerBase.php

As per discussions with @AdSchellevis here's my first stab at an ApiMutableTableModelControllerBase class. The use case for this abstract base class is to have a base class that can be derived from to act as an API controller for a gridview.
I've based this code on the pipe methods in OPNsense\TrafficShaper\SettingsController. A [diff](https://github.com/opnsense/core/files/407603/diff.txt) between these methods and my methods has been attached. This might be useful for understanding what I've done.
A few questions remain before this can be merged:
- What about validation? It seems that the code I looked at does not do validation. I'm not sure if that's correct in the general case.
- I'm not sure if I've implemented addItemAction() correctly.
- In addItemAction(), the traffic shaper code …

ApiMutableTableModelControllerBase

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php

Overriding getModel() is not to be done lightly. The code relies on the same object being there through multiple calls to getModel(). Any overriding methods should preserve this same behavior. For this reason, we should not encourage tinkering with this in a comment, better be silent on the matter.

(base) Do not encourage overriding getModel()

---

src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php

Looks like updating this default was missed when implementing the return of infinite rows in https://github.com/opnsense/core/commit/5d8b97e2b82b4804d90c4e3b49c69dd39dd516cc

(Base) Default to inf rows not 9999

---

src/etc/inc/util.inc

get_interface_list() tries to extract interface information by grepping through dmesg. This fails if there are interfaces present that for some reason do not appear in dmesg. The code attempts to handle it, but only handles the case where the first line returned from the grep is unparsable, it does not handle the case where no lines are returned at all. This leaks an undesired PHP info or warning out on stdout if not checked.
This may be the case for example, if a user has manually cloned VLAN interfaces on the FreeBSD end. (I'm sure other things break at least, but at least we don't have to leak this particular warning any more.)

(get_interface_list) Properly handle an interface not appearing in dmesg

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php
src/opnsense/www/api.php

Related to https://github.com/opnsense/core/issues/1136
Example before: `{"errorMessage":"Undefined offset: 0 [8]"}`
Example after: `{"errorMessage":"Error at \/usr\/local\/etc\/inc\/util.inc:952 - Undefined offset: 0 (errno=8)"}`

Improve error messages for API calls

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php

In case of serachUsers() returns false, this value handles wrong and Tester tool always returns successful login if in LDAP server settings does not specified "Bind credentials".

LDAP fix: handle legal boolean return result from searchUsers()

---

src/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php

Before:
```
Fatal error: Uncaught exception 'Phalcon\Validation\Exception' with message '[forward.interfaces] please specify a valid interface
' in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:468
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(562): OPNsense\Base\BaseModel->serializeToConfig()
#1 /usr/local/opnsense/mvc/script/run_migrations.php(49): OPNsense\Base\BaseModel->runMigrations()
#2 {main}
thrown in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php on line 468
```
After:
```
Fatal error: Uncaught exception 'Phalcon\Validation\Exception' with message '[OPNsense.Proxy.Proxy.forward.interfaces] please specify a valid interface
' in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:469
Stack trace:
#0 …
```

(BaseModel) Always log the class where validation failed

---

src/opnsense/service/templates/OPNsense/Proxy/squid.acl.conf

this fixes an issue that some newlines are missing and because of this, the configuration becomes invalid and squid will not start.

fix broken squid configuration

---

src/etc/rc.initial

if the tty is closed while the script is running,
it would previously go in an infinite loop trying
to read from and write to the now-defunct tty.
I finally opted for the set -e/set +e mechanism,
which introduces a minimal diff.
fixes: https://github.com/opnsense/core/issues/1240

rc: fix an infinite loop on tty close

---

src/www/services_dhcp.php

Current implementation of dhcp_clean_leases() takes too much time to remove static MACs from dhcpd leases database, which can sometimes exceed the max_execution_time, especially when leases database is huge or too many static MACs are configured.
This implementation uses regular expressions to speed up the cleanup process.

Optimized dhcp_clean_leases()

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php

Setting locale by code 
`$ret = new ViewTranslator(array(
'directory' => '/usr/local/share/locale',
'defaultDomain' => 'OPNsense',
'locale' => $lang_encoding,
));`
don't work correctly. After this $ret->_locale = false

Fix setting locale

---

src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php

Hmm, does it serve any purpose to set `##Unlinked` instead of just using an empty string?
It looks ugly if empty fields get filled with `##Unlinked` :)

UIModelGrid: use empty string instead of "##Unlinked"

---

src/www/services_dhcp_relay.php

The wording on the dhcp relay page is not making it clear that multiple servers are support, unless you click the help button.
This fixes it, and changes the help text to make multiple servers the default explaination.

dhcrelay: change the description and help text to make it clear multiple servers are supported

---

src/etc/inc/ipsec.inc
src/www/vpn_ipsec_phase1.php

This pull request is split across the tools and core repositories, this is the core part.
It has been changed, so it uses the radius servers defined in the auth framework.
1: commit improves readability of the generated strongswan.conf by fixing indentions, and ipsec.conf by adding some missing spaces.
2: commit implements the config file generation parts that is missing.
3: commit implements the ui part, adding some helper text, and hiding fields not to be used for EAP-RADIUS.

Part 2 of 2 - EAP-RADIUS ipsec/strongswan support, 2. try

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ModelRelationField.php

Use case: Plugins (and system components) may depend on optional plugins. For example, our Let's Encrypt plugin provides integration for our HAProxy plugin, but this is completely optional.
Without this fix, a fatal error occurs if the optional plugin is not installed:
```
[08-Feb-2017 10:50:57 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'OPNsense\HAProxy\HAProxy' not found in /usr/local/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ModelRelationField.php:90
Stack trace:
#0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(182): OPNsense\Base\FieldTypes\ModelRelationField->setModel(Array)
#1 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(228): OPNsense\Base\BaseModel->parseXml(Object(SimpleXMLElement), Object(SimpleXMLElement), …
```

ModelRelationField: soft-fail on missing classes

---

src/etc/inc/interfaces.inc
src/etc/inc/interfaces.lib.inc
src/www/interfaces_vlan_edit.php

This will allow setting a static outbound VLAN PCP (priority code point) in the VLAN settings.
This allows Google Fiber users to obtain full upload speeds.

add VLAN Priority (PCP) setting to VLAN config

---

src/etc/inc/filter.inc
src/www/firewall_rules_edit.php

This will add 2 additional advanced options for firewall rules. One to set the priority, and one to match based on the priority. This should be useful for Google Fiber users to unlock full upload speed.

Add priority settings to advanced firewall rule options

---

src/etc/inc/interfaces.lib.inc

This will fix the issue with tun interfaces (ie openvpn) having their subnet detected incorrectly. It also brings the code more in line with the IPv6 code.

Fix ipv4 subnet matching

---

src/www/firewall_rules_edit.php

Seems like most of the work for that was in the code already, only GUI option was missing. This commit adds the option in the GUI with appropriate checks, that are identical to synproxy state.

Add modulate state as an option for state tracking

---

src/etc/inc/filter.inc

This change cleans-up the rule generation for interface addresses and networks. It also addresses the issue with network addresses for interface groups (https://forum.opnsense.org/index.php?topic=4556.0). I have done some testing but not anywhere close to cover all of the scenarios. In theory, this should work as expected, and will also work with multiple interface alias IPs that I would like to add in the near future. Please consider this change as WiP and suggest any other areas and things that should be considered. Thanks.

Clean-up how interface address/network rules are generated.

---

src/etc/inc/filter.inc

Fix for overaggressive regex in a203c69 . If you create interface with "ip" in the end (group interface "testip") it will wrongly match and cause breakage of rules. This should narrow-down the match and fix the issue.

Fix a203c69 to prevent matching interfaces with 'ip'

---

src/etc/inc/filter.inc

Since pf already provides syntax to refer to interface IPs and directly attached networks, it is redundant to have this in the rule-set. I have not observed any place where those generated tables are used, but maybe missing something. It also does not work for group interfaces.

Further clean-up of generated firewall rules.

---

src/etc/inc/filter.inc
src/www/system_advanced_firewall.php

This setting will help with de-duplication of rules and reordering for better performance. From man pages:
<pre>
set ruleset-optimization
none      Disable the ruleset optimizer.
basic     Enable basic ruleset optimization.  This is the default
behaviour.  Basic ruleset optimization does four things
to improve the performance of ruleset evaluations:
1.   remove duplicate rules
2.   remove rules that are a subset of another rule
3.   combine multiple rules into a table when
advantageous
4.   re-order the rules to improve evaluation performance
profile   Uses the currently loaded ruleset as a feedback profile
to tailor the ordering of quick rules to actual network
traffic.
</pre>

Add ruleset-optimization option in firewall settings. 

---

src/etc/inc/dyndns.class

* Google Domains
* DuckDNS
they should work as they have a valid certificate (browser does trust them as well as curl URL works from my computer without `-k`)

enable tls certificate checks for some services

---

src/www/widgets/widgets/log.widget.php

IF -> Interface ("If" can be wrongly translated to a conditional -> using interface will fix this)
Unlock the cell width: This will prevent Firefox to write over the cell range into the next one (happens in german translation).

fix firewall widget:

---

src/etc/inc/services.inc
src/www/services_rfc2136.php
src/www/services_rfc2136_edit.php

As explained in #1456 this PR makes it possible to control whether A, AAAA or both record types are changed when updating using RFC2136.
_pfSense do not changed their table overview template, so you cannot see which record types are updated. Should we add this in OPNsense as it might be useful because you do not have to open the edit page for each update task?_ (see discussion)

RFC2136 RecordType Option

---

src/www/csrf.inc

* the script tag cannot be between head and body -> move into head
* the input was invalid (looks like a wrongly copied escape sequence
* add gettext

make csrf error page translateable, fix HTML errors in csrf.inc

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Note: SSL cannot be disabled because it does not exist (at least not in LibreSSL)
Important Note: This directive must be updated when upgrading to Squid 4.

harden ciphers and tls versions

---

src/etc/inc/plugins.inc.d/openvpn.inc

This semicolon is not needed but seems also not to break the config.

Removed unnecessary semicolon (Issue 1558 proposal) 

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Reason: to allow squid plugins define auth methods.
In my case I made plugin proxy-sso, which defines negotiate method for proxy authentication. This method included before basic to allow domain user to authenticate without appearing user credentials dialog.
squid.conf part:
`icap_enable off`
`include /usr/local/etc/squid/pre-auth/*.conf`
`auth_param basic program /usr/local/etc/inc/squid.auth-user.php`
`auth_param basic realm OPNsense proxy authentication`
`auth_param basic credentialsttl 2 hours`
`auth_param basic children 5`
`acl local_auth proxy_auth REQUIRED`
pre-auth plugin:
`auth_param negotiate program /usr/local/libexec/squid/negotiate_kerberos_auth -d -i -s HTTP/ting4.tingnet.local@TINGNET.LOCAL`
`auth_param negotiate keep_alive on`
`auth_param negotiate children 5`
In this case …

squid.conf: reorder pre-auth plugins and local auth settings

---

src/opnsense/scripts/OPNsense/CaptivePortal/htdocs_default/index.html

New iOS versions do autocapitalization, autocrrection and/or autocompletion in Web Forms. All three can be annoying when entering always changing usernames with sometimes lower-case first characters, as in the Captive Portal Vouchers' usernames. 
This should fix the behaviour and make the portal more graceful towards iOS devices.
Source for the attributes and their values: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html

Fix autocomplete, autocapitalize and autocorrect in Captive Portal login form

---

src/etc/inc/plugins.inc.d/webgui.inc

In lighttpd < 1.4.46 ssl options like ssl.use-sslv2 and
ssl.cipher-list have to be included twice.

Generate ssl options for IPv6 web configurator

---

src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc

I just stared using OPNsense with a downloaded version which was 17.1.4 where a custom v6 DynDNS update worked.
Then I did the upgrade to latest stable 17.1.8 and it just gave me the IPv4 address.
Seems the problem was just a little typo when refactoring...
This fixes it...

Fix DynDNS update for IPv6

---

src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php

To separate Mirror-Traffic and Website Traffic, a change of the URL is needed.
The website / mirror site behind both URLs is the same.

Change Mirror URL

---

src/opnsense/mvc/app/library/OPNsense/Firewall/FilterRule.php

Fix for #1745. Turns out this was a simple typo, but an important one, because it made it impossible to have floating rules without the `quick` keyword.

filter: fix floating rules default for quick parameter

---

src/www/status_graph.php
src/www/widgets/widgets/traffic_graphs.widget.php

This update includes many of the items discussed in feature request https://github.com/opnsense/core/issues/1462.  
This allows the hosts entries to persist for the duration of the overall traffic graph (showing the top 20), dynamically updating the traffic for each. It includes a small micrograph for each item displaying "bw in" and "bw out".  It also includes new columns for Total In, Total Out, as well as new sorting for Total In, Total Out, Bw In Avg, Bw Out Avg.  The Avg sorting helps reduce fluctuation in the table.
This pull request is based on code from the last commit of Mar 13, 2017. https://github.com/opnsense/core/issues/1449

Traffic Graph improvements

---

src/www/status_dhcp_leases.php

I had some issues with "illegal offset" warnings so I was not able to see dhcp lease times.
This fixed it for me and it seems that these isset-checks are missing.

Fix DHCP Leases PHP Illegal Offset Warnings

---

README.md

noticed a dead link in the readme, fixed it

fix link to development architecture

---

src/etc/inc/filter.inc

Adds support for non-whitespace field separators to URLtable IP lists.
Some IP lists use alternate characters as field separators - commas, semicolons, vertical bars.  For example, feeds from http://osint.bambenekconsulting.com/feeds/ use commas to separate list values.

Support non-whitespace field separators for URLtable lists

---

src/etc/inc/filter.inc
src/opnsense/mvc/app/library/OPNsense/Firewall/Plugin.php

It is needed to allow register tables in plugins.

Firewall plugin: register table

---

src/www/status_dhcp_leases.php

* replaces strcmp with strnatcasecmp, which is much better at sorting ip addresses
* sorts the list by IP address by default
* does a secondary sort by IP address, which gives better results when sorting by status or lease type
* fixes sorting on the "status" column (the underlying data structure is keyed on "online" instead of "status")
* removes the option to sort by interface, since that doesn't work (the data doesn't exist at the time the array is sorted)

 improve sorting of DHCP leases

---

src/opnsense/mvc/app/views/layout_partials/base_form.volt

For the case where I want to make the settings block "advanced" with the block header.

Default form: ability to hide header under 'advanced' tag

---

src/www/system_certmanager.php

With this patch, the correct issuer and subject will be shown to the user:
Follow up for #1964

fix: system_certmanager.php xss

---

src/etc/inc/interfaces.inc
src/www/interfaces.php

dhcp6c sends a release signal on exit by default. This can cause the loss of the allocated prefix or address and a new one on the next connection. This is especially the case with many ISPs.
This option allows the user to disable the release send.
I added the  -n option to the FreeBSD dhcp6c quite a while back.
Sorry for the previous PR, copy paste error!

dhcp6c No Release Option

---

src/etc/inc/filter.lib.inc
src/www/interfaces.php

Certain ISP's, Orange France for example use a VLAN, it is a requirement that the dhcpv6 packets are sent with a different priority, in Orange Frances case it is 6.
This PR allows the user to select whether or not to enable the setting of the VLAN priority for dhcpv6 packets and the value to use.
The is then used in the filter.lib.inc to add the extra set-prio value when the fillter is created.
This PR requires the the sysctl net.link.vlan.mtag_pcp be set to 1.

DHCPv6 Vlan priority

---

src/etc/inc/interfaces.inc

Use the REASONS given by dhcp6c when it calls its script. This then only calls newipv6 when 'REQUEST' is the reason.
RENEW, REBIND or INFO do not have changes to the leases, therefore no call to update is needed and this prevents reloading which can affect VPNs, Unbound etc.
On RELEASE or EXIT, once again newipv6 is called as the lease addresses should have been removed by dhcp6c.

dhcp6c - Use Reasons

---

src/www/services_dhcp.php
src/www/services_dnsmasq.php
src/www/services_unbound_acls.php
src/www/services_unbound_overrides.php

Error: The element button must not appear as a descendant of the a element.
Specification:
http://w3c.github.io/html/textlevel-semantics.html#the-a-element
"Allowed ARIA role attribute values: link (default - do not set), button, checkbox, radio, switch, tab or treeitem"
"The <a> element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links)."

HTML Compliance - Element <button> Descendant of <a> Element

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

Implement touch-action: manipulation CSS property to eliminate 300 ms tap delay.
Does not prevent zoom.  Zoom still available by pinch.  Only prevents double tap zoom in order to eliminate the 300 ms tap delay.
What Exactly Is..... The 300ms Click Delay
https://www.telerik.com/blogs/what-exactly-is.....-the-300ms-click-delay
Mozilla developers page.  Updated Oct 25, 2017.
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
W3C Recommendation - The touch-action CSS property
http://www.w3.org/TR/pointerevents/#the-touch-action-css-property

Eliminate 300 ms Tap Delay

---

src/opnsense/mvc/app/views/OPNsense/Proxy/index.volt
src/opnsense/mvc/app/views/layout_partials/base_form.volt
src/www/widgets/widgets/ipsec.widget.php
src/www/widgets/widgets/ntp_status.widget.php
src/www/widgets/widgets/system_log.widget.php

width, align, valign, cellpadding, cellspacing, border, summary
Error: The width attribute on the table element is obsolete. Use CSS instead.
Error: The align attribute on the table element is obsolete. Use CSS instead.
Error: The valign attribute on the table element is obsolete. Use CSS instead.
Error: The cellpadding attribute on the table element is obsolete. Use CSS instead.
Error: The cellspacing attribute on the table element is obsolete. Use CSS instead.
Error: The border attribute on the table element is obsolete. Use CSS instead.
Error: The summary attribute on the table element is obsolete. Consider describing the structure of the table in a caption element or in a figure element containing the table; or, simplify the structure of the table so that no description is needed.

HTML Compliance - Obsolete table attributes - II  (few stragglers)

---

src/www/widgets/widgets/interface_list.widget.php
src/www/widgets/widgets/ipsec.widget.php
src/www/widgets/widgets/log.widget.php
src/www/widgets/widgets/picture.widget.php
src/www/widgets/widgets/system_log.widget.php

Error: Attribute alt not allowed on element span at this point.
Error: Table columns in range 2…4 established by element td have no cells beginning in them.
Error: Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
Error: Row 1 of a row group established by a tbody element has no cells beginning on it.
Warning: A table row was 0 columns wide, which is less than the column count established by the first row (5).
Error: Duplicate ID submita.
Error: Bad value 100% for attribute width on element img: Expected a digit but saw % instead.
Error: Bad value 100% for attribute height on element img: Expected a digit but saw % instead.
Warning: The border attribute is obsolete. Consider specifying img { border: 0; } in CSS instead.
Avoid …

HTML Compliance - Lobby: Dashboard Widgets

---

src/www/index.php

Touch events not working with the widget controls (link, buttons, drag/drop sort).
Add distance, delay and touch-action css for the widget controls to work with touch screen input.
Widget controls not working correctly with touch screen input
https://github.com/opnsense/core/issues/2092

Widgets Controls on Touch Screen

---

src/etc/inc/authgui.inc
src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/scripts/OPNsense/CaptivePortal/htdocs_default/index.html
src/www/head.inc

Error: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.
The "Chrome=1" value was used to spawn Chrome Frame in IE 6,7,8,9.  However, "Google Chrome Frame was discontinued in January 2014", and think all IE<11 is beyond EOL.
So is this even needed/useful?
If needed/useful it would probably be better to support deployment by HTTP headers method instead.
Google Chrome Frame
https://en.wikipedia.org/wiki/Google_Chrome_Frame

HTML Compliance - Attribute "content" value on Element <meta>

---

src/opnsense/mvc/app/views/layout_partials/base_menu_system.volt
src/opnsense/mvc/app/views/layouts/default.volt
src/www/fbegin.inc

Warning: The navigation role is unnecessary for element nav.
HTML 5.1 2nd Edition
W3C Recommendation 3 October 2017
4.3.4. The nav element
http://www.w3.org/TR/html51/sections.html#the-nav-element
Allowed ARIA role attribute values: ‘navigation’ role (default - do not set) or ‘presentation’.
http://www.w3.org/TR/html51/dom.html#do-not-set
Note: In the majority of cases setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and not recommended as these properties are already set by the browser.
In the December 2017 document "is unnecessary and not recommended" is bold emphasized.
HTML 5.2
W3C Recommendation, 14 December 2017
http://www.w3.org/TR/html5/dom.html#aria-authoring-requirements
According to HTML5 Accessibility dot com, Chrome, …

HTML Compliance - "navigation" "role" on Element <nav>

---

src/www/widgets/widgets/log.widget.php

Widget purpose is to provide an overview, i.e. abbreviated information, of the firewall log.  Details are available in the firewall log view.
Source port is not all that interesting.  Consumes considerable space for not much value in this view.
Remove seconds from time field.  Verbosity is available in the firewall log view.
Apply "table-condensed" class for better space utilization.
Settings:
Provide some separation between check boxes and make their labels active.  Better accessibility and touch screen friendliness.

Firewall Logs Widget Tweaks

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css
src/www/index.php

This works with both Android and Desktop Chrome (v63) as well as IE 11.
exception: there is apparently an incompatibility between Chrome and JQuery sortable.  So drag/drop sort doesn't work in Chrome.
This is a modification of the previous:
https://github.com/opnsense/core/commit/3f7ee41b5307204fdc4819d09a09aef9e254dbc5#gitext://gotocommit/3f7ee41b5307204fdc4819d09a09aef9e254dbc5
Touch events not working with the widget controls (link, buttons, drag/drop sort).
Add distance, delay and touch-action css for the widget controls to work with touch screen input.
Widget controls not working correctly with touch screen input
https://github.com/opnsense/core/issues/2092

Widgets Controls on Touch Screen - Update (Chrome)

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css
src/www/index.php

Delay and distance no longer needed now that the handle does not overlap the controls (title link and buttons).
Be consistent with class naming convention (s/_/-/).

Widget Sort Handle Tweaks

---

src/www/widgets/widgets/ipsec.widget.php

This is more appropriate, as the tabs are more akin to a label than an output.
Also better for touch screens because some browsers select the tab label text (highlight for copying) when output element tapped.  Not a functionality issue, but looks bad and initially confusing (why is that text selected?)
Using data attributes
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
HTML5 is designed with extensibility in mind for data that should be associated with a particular element but need not have any defined meaning. data-* attributes allow us to store extra information on standard, semantic HTML elements without other hacks such as non-standard attributes, extra properties on DOM, or Node.setUserData().

IPSEC Widget Tabs - Tweak

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

Minimum time field width so date (month day, e.g. Jan 24) doesn't wrap and consume additional line unnecessarily.  Particularly in mobile portrait view.

Firewall Logs Widget - time min width

---

src/www/services_ntpd_gps.php

This was probably not planned that bootstrap breaks the line before and after the input field. Also the button was missing bootstrap style.

inline nmea checksum calculator; use bootstrap style for button

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec_settings.php

When routing the default route over IPSec, installing 0.0.0.0/1 and 128.0.0.0/1 routes effectively overrides the default gateway, making it impossible for the firewall itself to use the route, because this hack (https://doc.pfsense.org/index.php/Why_can%27t_I_query_SNMP,_use_syslog,_NTP,_or_other_services_initiated_by_the_firewall_itself_over_IPsec_VPN) no longer works.
This is alleviated by adding the option to not automatically install routes via the charon.install_routes directive (https://wiki.strongswan.org/projects/strongswan/wiki/Strongswanconf).
The rationale behind providing this via GUI is that "Passthrough Networks" also is provided for that exact reason; providing the new switch rounds off this experience.

Enable charon.install_routes from GUI

---

src/opnsense/mvc/app/models/OPNsense/CheckIP/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/CheckIP/Menu/Menu.xml
src/www/services_checkip.php
src/www/services_checkip_edit.php

Configurable check IP services.
Used by Dynamic DNS services to check IP addresses.
Configure as many check IP services as desired.  The first (highest in the list) that is enabled will be used as the default.
Include verify peer option.
A future possibility could be to add an option to the Dynamic DNS entires to use a specific check IP service.
Allows additional/private check IP services to be added and set as the default.

Check IP Services - Plugin

---

src/etc/inc/services.inc

Update get_dyndns_ip function to support adding other services and disabling the factory default service (Check IP Services - Plugin).
Factory default check IP service as array
Support verify peer
Support authentication

Check IP Services - Plugin Support

---

src/www/firewall_rules.php

Seems this option was in _admin and moved to _firewall. Now it links to the correct page for editing anti lockout rule

updated link for anti lockout

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Base/IndexController.php
src/www/guiconfig.inc
src/www/head.inc

this should stay on master for longer time since it may have side effects like blocking resources.

Harden GUI by adding a CSP, XSS protection and referrer hiding

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound_host_edit.php

Using * as a hostname, one now create wildcard domains in unbound.
```
redirect
The query is answered from the local data for the zone  name.
There  may  be  no  local  data  beneath the zone name.  This
answers queries for the zone, and all subdomains of the  zone
with the local data for the zone.  It can be used to redirect
a domain to return a different  address  record  to  the  end
user,    with   local-zone:   "example.com."   redirect   and
local-data: "example.com. A 127.0.0.1" queries for  www.exam-
ple.com and www.foo.example.com are redirected, so that users
with web browsers  cannot  access  sites  with  suffix  exam-
ple.com.
```

add support for wildcard entries in unbound

---

src/www/services_unbound_host_edit.php

Follow up for https://github.com/opnsense/core/pull/2313 , fixing form validation not allowing an asterisk ( i was testing with REST before, sorry )

Fix hostname sanitizing to allow asterisk for wildcards

---

src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php
src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.php
src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.xml

@AdSchellevis here is an updated version

backup nextcloud v2

---

src/etc/inc/interfaces.inc

When setting up the remote address to be an IPv6 address on an interface with a legal IPv6 address, the tunnel needs to be created using the inet6 parameter before the tunnel keyword, otherwise the command silently fails (return value ignored?).

Fixed creation of GIF tunnel with an outer IPv6 remote address (remote-addr)

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/Api/ServiceController.php
src/opnsense/mvc/app/views/OPNsense/IDS/index.volt

This adds Destination IP as a search filter for the IDS Alerts.  It also adds a tooltip to the trash can.

Add Destination IP to Alert Search

---

src/opnsense/mvc/app/library/OPNsense/Auth/Radius.php
src/opnsense/scripts/OPNsense/CaptivePortal/process_accounting_messages.php

In reference to #2363 this pull request adds support for traffic data (bytes_in/out) in IP address fields in the Radius Accounting messages.

Add traffic data and IP address to Radius Accounting messages

---

src/etc/inc/plugins.inc.d/ipsec.inc

Add double quotes around the RADIUS secret to prevent some corner cases where the secret was not fully read.

Fix IPsec RADIUS secret

---

src/etc/inc/services.inc

Additional fix for issue #2394 to prevent an incorrect prefix in case radvd.conf is created after the interface already has an IP address.

If SLAAC, don't fix the subnet based on the current address

---

src/opnsense/mvc/app/views/layout_partials/base_menu_system.volt
src/www/fbegin.inc

This feature adds the ability to have parent level menu items that are clickable and that can pivot to an internal link as well as a external link.
I made some improvements on the security stand point for external links due to the fact we are using `target="_blank"`. You can read more about the potential security risks here:
* [Target="_blank" - the most underestimated vulnerability ever](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)
I've added `rel="noopener noreferrer"` to legacy code as well as additional feature code.

feature: Top level menu item link pivots + security improvements

---

src/opnsense/mvc/app/library/OPNsense/Core/Routing.php
src/opnsense/mvc/app/models/OPNsense/Base/Menu/Menu.xml

In the current OPNsense, URLs that don't end in an extension (`php`) have to end with a trailing slash. If you navigate to the same URL without the trailing slash, the page is not found and you get a "Page not found" page. I went ahead and fixed the routing so that URLs are now dynamic in the aspect of whether you go to `/ui/plugin-page` or `/ui/plugin-page/` the content for that page loads.
The functionality is standard Phalcon stuff, and you can read more about the change I made at the following location:
link: [Dealing with extra/trailing slashes](https://olddocs.phalconphp.com/en/3.0.0/reference/routing.html#dealing-with-extra-trailing-slashes)
I also went ahead and fixed the one menu item that was using a trailing `/` to not use it.

Enhancement: URLs load correctly regardless of trailing slash

---

src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

`ipfw show`:
```
60004  50573  69792852 queue 10000 ip from not 192.168.23.0/24 to any xmit lagg0_vlan2342 recv em0 // wan -> lan: down,75 weight
60005  29657   3088201 queue 10003 ip from any to not 192.168.23.0/24 recv lagg0_vlan2342 xmit em0 // lan -> wan: up,75 weight
```

Help debugging of Traffic Shaping by generating ipfw comments in rules

---

src/etc/inc/certs.inc

Addresses https://github.com/opnsense/core/issues/2459.
Server certificates should have KU set to include "Digital Signature" and "Key Encipherment," and EKU set to "TLS Web Server Authentication."
OpenVPN requires both KU and EKU set correctly to successfully validate if client is using remote-cert-tls server configuration parameter.

Confirm KU/EKU for server certs

---

src/etc/inc/certs.inc
src/etc/ssl/opnsense.cnf

Related to #2459. 
The matching KUs for EKU "TLS Web Server Authentication" are Digital Signature AND (Key Encipherment OR Key Agreement). Added for compatibility with externally-generated certificates.
Removed the nsComment extension from all cert profiles. It's deprecated like nsCertType is, though nsCertType was retained in the server profile for backwards compatibility with ancient OpenVPN clients using the ns-cert-type configuration parameter.
Tested by porting modified code to a running OPNsense firewall and generating a bunch of certificates, all of which function properly.

Further KU/EKU fixes.

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound_acls.php

add support for "deny_non_local" and "refuse_non_local" ACLs
see: https://github.com/pfsense/pfsense/commit/2c84c28a221ff84636c205a2beddcfd31be58339

Unbound: extend access-control feature

---

src/opnsense/scripts/suricata/metadata/rules/opnsense.xml
src/opnsense/service/templates/OPNsense/IDS/classification.config

First https://github.com/opnsense/rules/pull/9 has to be merged to master/stable and the ruleset synced by daily cron to final webserver.

IDS: add uncategorized category to classification and rule download

---

src/etc/inc/interfaces.inc

I was trying to use `get_interfaces_info()` function in one of my plugin apis. I got an error `Undefined index` here because some `intf_detail` didn't have the `status` field. So let's use `isset` to check it first to avoid this error.

interfaces: check existence of `status`

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/ServiceController.php
src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/StatusController.php
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/opnsense/mvc/tests/app/compound/OPNsense/Monit/MonitTest.php
src/www/widgets/widgets/monit.widget.php

This PR removes the 'Test-/Reload Configuration' buttons.
Changes goes immediately after clicking 'Save Changes' to the config.xml and
a message appears to 'Apply' the configuration. After applying the configuration it is tested
and the Monit daemon is reloaded. In principle, the same as the Relayd.
The model has a locking mechanism now to prevent failures from concurrent access.
E.g. delete multiple items from the 'Service' tab leaves some configured.
The __constructor of the model locks per default the model object.
It is used by Service- and SettingsController with lock. The StatusController access it
without lock only for reading.
Last but not least, I added some PHPunit tests.

monit: UI improvements; phpunit tests

---

src/opnsense/mvc/tests/app/compound/OPNsense/Monit/MonitTest.php

This will fix (https://github.com/opnsense/core/pull/2505#issuecomment-402021083)
MonitTest.php tries to stop the Monit daemon before ServiceController test.
But for an unconfigured Monit `configctl monit stop` returns `Error (1)` caused by a missing monit_enable rc.conf setting.

monit: create template before stopping Monit for ServiceController test

---

src/opnsense/scripts/shell/banner.php

Example output:
```
$ /usr/local/etc/rc.initial.banner
*** test-fw.localdomain: OPNsense 18.1.10 (amd64/OpenSSL) ***
WAN (vtnet0)    -> v4/DHCP4: 172.30.23.2/24
SSH: 256 SHA256:fcMIAgT/vZR/TWP0j8AFROTNnudkU1tP9sRhbsIa8vM (ECDSA)
SSH: 256 SHA256:lDenOc5wy2WU0e6sSz2hR9nEFnMqx5c3u1F/pHxgJlY (ED25519)
SSH: 2048 SHA256:dsw9srlQHL0hPJlEdR9rL769N30BTZgXG9gXbdZGOkU (RSA)
HTTPS X.509 cert: SHA256 Fingerprint=F0:E6:EB:31:E8:87:AF:52:16:4E:84:05:3B:6C:03:2C:C1:DF:5A:E7:36:F4:32:44:3B:B5:57:63:97:45:C3:77
```
The list of fingerprints is appended after the interface list because the interface list might be pretty long and thus would move the fingerprints out of the screen which we don’t want.
Previously (#2427) I suggested to extract the X.509 certificate from the xml config but the difficult part for …

Print SSH and X.509 fingerprints in console banner without need to login

---

src/www/system_certmanager.php

Nice thing is that `openssl x509` respects the order of supplied arguments. It was chosen to print the one line of fingerprint above of the X509 text dump. `-sha256` is needed because OpenSSL 1.0.2k-freebsd 26 Jan 2017 seems to default to SHA1 currently.
Example of the first line:
```
SHA256 Fingerprint=F0:E6:EB:31:E8:87:AF:52:16:4E:84:05:3B:6C:03:2C:C1:DF:5A:E7:36:F4:32:44:3B:B5:57:63:97:45:C3:77
```
This commit is one piece to make fully trusted bootstrapping easier.
Related to: https://github.com/opnsense/core/issues/2427
URL path of the GUI page involved: /system_certmanager.php

Add `openssl x509 -fingerprint -sha256` to "Show certificate info"

---

src/www/vpn_openvpn_export.php

A fix for #2529 
I believe this should do the trick, though I have to admit I couldn't test it because I haven't figured out the procedure for testing it on a live system yet (editing the file in /usr/local/www and restarting services seems to have no effect) and I don't have a FreeBSD machine handy. If someone points me to a correct procedure for testing changes on a live system, I'll be grateful (if there's no such thing I can make a build setup of course).
Since I haven't contributed to OPNSense before, if I broke any process or coding conventions, just let me know and I'll fix it.

Add a special case for /31 tunnel networks to the OpenVPN config generator (fixes #2529).

---

src/etc/inc/plugins.inc.d/openvpn.inc

Finally, I've fixed it in the place where I originally intended to fix it (#2529).
This time I've verified that it works, thanks to people on the IRC who explained me how to restart the web GUI properly.

Add a special case for /31 networks to openvpn_get_interface_ip() (another instance of #2529)

---

src/etc/rc.subr.d/livemode

Just saying _"Both root and installer are available"_ is not very intuitive to a new user trying out OPNsense for the first time - which is the point where it needs to be most clear what's going on. (They may well enter root, thinking that "system setup" _means" installing, which isn't unreasonable.)
This PR clarifies the message.

Clarify install media login message/options

---

src/sbin/opnsense-installer

If the user's existing subnet isn't 192.168.1.1/xx, then telling the user to use this IP will fail. So tell the user how to set a different IP after reboot, rather than just telling them to use an IP that won't work for them.
Kept short this time - 1 line only :)
Also edited wording re certificate, to be clearer about this as well, by starting with what they will actually see (*"Your browser may..."* rather than *"You might need to..."*). Added just 1 line there as well.  
The wording *"and cannot be validated by an external root authority"* is so people don't worry about "WHY ISN'T IT TRUSTED, IS IT INSECURE!" - makes clear there isn't **external** validation. Also better understanding is good. Possible reword: "This is normal, as the initial certificate will be self-signed, and not …

After install, give basic tip that GUI IP can be set in console

---

src/opnsense/www/js/opnsense_ui.js

When calling saveFormToEndpoint I'd like to be able to reference data in the front end that was returned through the ajax call - as in the example below
```javascript
$("#someAction").click(function(){
saveFormToEndpoint(url="/api/plugin/feature",formid='frm_Form',callback_ok=function(data){
$("#someElement").html(data['message']);
});
});
```
The PR allows this data to be passed through as required.
I'd highlight however that I do not know the codebase well enough to know if this has other side effects or could be leveraged in ways to cause unwanted behaviors - while it seems probably okay I'd ask project maintainer(s) to provide guidance if required.

Cause data through saveFormToEndpoint callback_ok to be passed through

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt
src/opnsense/mvc/app/views/layout_partials/base_form.volt

since i used opnsense i noticed that the advanced slider button has an ugly blank on hover and focus. this problem occurs in every theme. has to do with a wrong placed blank.  Its also visible in the original theme of opnsense. I've fixed this with a standard html syntax. its visible on every page which uses an advanced button. like monitor, proxy and so on...see the screenshot

blank problem advanced button

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt

fix for an UI bug found while developing the nginx 1.1 plugin. Due to the really long headings, they would break in the first column because the colspan is set incorrectly.

fix table headers: tr elements cannot have a colspan, th elements can

---

src/etc/inc/plugins.inc.d/unbound.inc

stub-zone doesn't work for non-authorative upstream DNS servers, but forward-zone does.

Swap stub-zone for forward-zone

---

src/www/interfaces_assign.php

The XML variable name ($newifname) should always be "lan" (written in lowercase letters). This commit removes the gettext translation function for the variable name. With the former behaviour, removing the LAN interface and trying to add new (optional) interfaces was broken when a user had switched the interface language to German (the variable name was translated to "LAN" in capital letters, which caused any new interface to overwrite this "LAN" entry).

fix adding interfaces LAN bug of German interface

---

src/etc/inc/services.inc

Several vendors use EFI BC instead of the EFI x86-64 value for the arch, some thinkpads for example. We noticed this while we tried to use PXE on all our machines and that some EFI systems with 64-bit didn't work and some did. We then found the old commit that change the if clause from 00:07 to 00:09 and tested around. Thus we found out that some machines use 7 and some 9, so IMHO it's correct to redirect both cases to the 64bit syslinux filename. This commit doesn't break old configs, just adds the additional option.
Would be nice to see that in the next update so we can start using PXE :) Thanks

dhcpd: treat EFI BC the same as EFI x86-64

---

src/etc/inc/interfaces.inc

in some situation, like OpenStack, mtu is less then default (1500) and
it cause replication issue
we have noticed on a low used firewall with 2/3k State table size more
then 100k State table size on the backup server
copy mtu from real interface fix this issue

Copy pfsync0 MTU from real interface

---

src/sbin/opnsense-importer

Added probe for ZFS pool on partition.
I would like to suggest adding the ability to import a configuration from a pool with an arbitrary name.
How it works:
User selects the device, and probe_for_part() determines partition. If probe_zfs_pool() finds ZFS pool on that partition, configuration importing is performed from ZFS pool.
1. import all possible pools without mounting any filesystems
2. enumerate pools and search for the one that uses selected partition
3. export all imported pools except root mounted pool, if exists
Now user must specify exactly "zroot" for import configuration from ZFS, i.e., ZFS supported only on "zroot/ROOT/default"

Added probe for ZFS pool on partition in opnsense-importer (from Smart-Soft)

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/dialogUserDefined.xml
src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml
src/opnsense/service/templates/OPNsense/IDS/OPNsense.rules

As discussed in #2110 with @AdSchellevis here are whitelists.
I didn't realized it's that simple. Two new fields for source/destination. When empty it's any, so existing rules won't be changed. In dropdown there's now a "Pass" to add a whitelist.
Since we have in suricata.yaml:
```
action-order:
- pass
- drop
- reject
- alert
```
.. we don't run into problems when the SID is higher than the match. 
Here's my test rule:
`pass ip   10.10.10.1  any ->  192.168.55.5  any (msg:"test pass";  sid:4294967294; rev:1;)
`
If I have a FP on let's say some SIP attacks from a real phone, normally you'd just disable the rule to get it running. But it would also allow this kind of attack. Now you can just create a whitelist from your phone to your PBX and that's it.
So, what do you think?

IDS, add whitelists

---

src/www/widgets/widgets/interface_list.widget.php

On lobby with more than two columns, in the interface_list.widget the IPv6 address can be longer than the box. This wraps it.

Wrap the IP address

---

src/etc/inc/services.inc
src/www/services_dhcpv6.php

Does not use dhcp6c mods. uses existing functions to determine the PD length available.

dhcpd6 PD Auto tracking additons

---

src/www/vpn_ipsec_phase1.php

3DES shouldn't be used anymore, same to SHA1. Also, DH, the higher the number doesn't mean it's more secure. DH22-24 should be avoided in a new draft of RFC:
https://tools.ietf.org/html/draft-ietf-ipsecme-rfc4307bis-18#section-2.4
The new values are marked as MUST or SHOULD+ values from the RFC.

Make IPSec Phase1 defaults more secure

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/alerts.xml
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml

Change the Mail Format field for Alerts to textbox to configure it multi-line.
The problem came up with opnsense/plugins#820

monit: change mail format field for alerts to textbox

---

src/etc/rc.newwanip

When using a static WAN IPv6 address and using PPPoE for v4,  if you save and apply the interface - this is when the interface is already up, the IPv6 address does not get applied, an error from ifconfig is generated. It appears as though the interface is not ready to accept the v6 address. This fix adds a slight delay in calling ifconfig if both the IPv6 address is static and the v4 is pppoe.
This is a fix for issue 2726 [https://github.com/opnsense/core/issues/2726](url)

Fix for static IPv6 when using PPPoE IPv4 on WAN

---

src/www/interfaces.php

Correct missing '"' and copy paste error with a "text" field.

Correct missing '"'' at the end of the userclass field

---

src/opnsense/www/js/jquery.bootgrid.js

Currently, pagination uses double guillemets for first/last page and lower than/greater than signs for previous next (like so: `« < 1 2 3 > »`). This looks ugly. Change this to use single guillemets, for visual consistency (like so: `« ‹ 1 2 3 › »`).

Use single guillemets for previous/next page

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

I noticed that the separation of the individual <a> links is missing. Now it is up to you to say if we should install it again or not. if you do not want it please just delete this pr. have added two screenshots as a comparison. Thank you, best regards, René
new would be:
old was:

border between <a>´s are missing

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/StatusController.php
src/opnsense/mvc/app/views/OPNsense/Monit/status.volt

The status page uses css classes for text colors now.
Hence it's customizable via themes.
opnsense/plugins#928

monit: change status page look-and-feel

---

src/www/firewall_nat_1to1.php
src/www/firewall_nat_npt.php
src/www/firewall_nat_out.php
src/www/firewall_rules.php
src/www/firewall_scrub.php
src/www/firewall_virtual_ip.php
src/www/vpn_ipsec.php
src/www/vpn_openvpn_client.php
src/www/vpn_openvpn_csc.php

What I did:
- Some upper and lower case corrections on the tooltips.
- Rearranged the buttons order in "Firewall: Settings: Normalization"
- Correction for the "move to end" function for "Firewall: Rules: xxx"

Move selected ... to end

---

src/www/diag_logs_template.inc

function_exists() takes a string, but an undefined constant was passed. If a constant is undefined, PHP will convert it to a string, but this is very dirty behaviour.

Fix use of undefined constant where string was intended

---

src/etc/inc/PEAR.inc

Since PHP5, __construct() is preferred. As of PHP7, the old PHP4 style constructor is deprecated.
There are also a dozen occurrences in contrib, but I assume those are supposed to be fixed upstream.

Fix old-style constructor in PEAR.inc

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/services.xml
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/opnsense/service/templates/OPNsense/Monit/monitrc

Add quotation marks to custom program path and the timeout parameter.
See #2811 and [Monit Service Checks](https://mmonit.com/monit/documentation/monit.html#Program)

monit: add quotes and timeout to custom program path

---

src/etc/config.xml.sample
src/etc/inc/system.inc

It took me some time to figure out that the default value for these sysctls is `0` on OPNsense. So I thought it would be a good idea to expose these defaults in the GUI and make it more obvious.

system: expose defaults for security-related sysctls

---

src/www/system_certmanager.php

This was all that was needed - the PHP code already handled it correctly, and the resulting CSR has its subjectAltName set correctly.

Implement #2686: Allow setting alternative names on CSRs

---

src/opnsense/mvc/app/views/OPNsense/Unbound/stats.volt

Noticed this when checking the stats clearing problem. It would only update once.

Fix Unbound stats autorefresh not working

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt

copied that line from the base form - it makes advanced headers working in dialogs (base_form already has it).

fix advanced field bug in dialogs

---

src/opnsense/mvc/app/models/OPNsense/Firewall/Migrations/M1_0_0.php

It just happened that the alias migration failed on a device that was in use for 3+ years. The error message was not very useful (because there's no hint which entry is erroneous):
```
Nov 22 23:20:12 opnsense config[71480]: [OPNsense\Firewall\Alias:aliases.alias.d8c784bb-e748-47fa-bada-2dc68b622c18.content] Entry "" is not a valid port number.
Nov 22 23:20:12 opnsense config[71480]: Model OPNsense\Firewall\Alias can't be saved, skip ( Phalcon\Validation\Exception: [OPNsense\Firewall\Alias:aliases.alias.d8c784bb-e748-47fa-bada-2dc68b622c18.content] Entry "" is not a valid port number.  in /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:538 Stack trace: #0 /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php(645): OPNsense\Base\BaseModel->serializeToConfig() #1 …
```

firewall: ignore empty values in alias migration

---

src/etc/inc/interfaces.inc
src/www/diag_backup.php
src/www/diag_ipsec_spd.php
src/www/diag_limiter_info.php
src/www/interfaces.php
src/www/services_dhcp.php
src/www/services_dhcpv6.php
src/www/services_dnsmasq_edit.php
src/www/services_ntpd.php
src/www/services_unbound_acls.php
src/www/status_dhcpv6_leases.php
src/www/system_camanager.php
src/www/system_certmanager.php
src/www/vpn_ipsec_settings.php
src/www/vpn_openvpn_server.php
src/www/widgets/widgets/carp_status.widget.php
src/www/wizard.php

This fixes some typos, deprecated elements and the usage of the `alt` attribute on `<div>` elements (which is not allowed and does not work either).

Fix HTML errors

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

If sslurlonly is 0 `ssl_bump peek bump_step1 all` is listed twice.
Might be cosmetic only since it's working though ...

proxy: move bump_step1 down in squid.conf

---

src/opnsense/www/js/opnsense_theme.js

since the navigation bar can change in height at any time due to the installation of plugins, and since we may want to redistribute the plugins, I have decided to dynamically adapt the resize function for navigation. now it does not matter how many menu items are in the sidebar. the resize function of sidebar navigation is now dynamic.

resize function adapts to the sidebar height

---

src/etc/inc/IPv6.inc
src/etc/inc/filter.inc
src/etc/inc/interfaces.inc
src/etc/inc/legacy_bindings.inc
src/etc/inc/plugins.inc.d/ntpd.inc
src/etc/inc/plugins.inc.d/openvpn.inc
src/etc/inc/plugins.inc.d/unbound.inc
src/etc/inc/rrd.inc
src/etc/inc/services.inc
src/etc/inc/util.inc
src/etc/inc/xmlparse.inc
src/etc/rc.openvpn
src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/NetworkinsightController.php
src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemhealthController.php
src/opnsense/mvc/app/library/OPNsense/Auth/Local.php
src/opnsense/scripts/shell/setaddr.php
src/www/diag_states_summary.php
src/www/interfaces.php
src/www/widgets/api/plugins/traffic.inc

This fixes several problems regarding variable assignments or initialisation. Most of these are variables that are declared but never used or declared but immediately overwritten. It also contains cases of an assignment operator instead of a compound string concatenate operator, and some cases of (nonworking) "C-style" variable declaration.

Clean up incorrect/unused variable assignments

---

src/www/firewall_nat.php
src/www/firewall_nat_npt_edit.php
src/www/firewall_rules.php
src/www/firewall_rules_edit.php
src/www/firewall_schedule_edit.php
src/www/firewall_scrub_edit.php
src/www/firewall_virtual_ip_edit.php
src/www/services_dhcpv6.php
src/www/system_camanager.php
src/www/system_groupmanager.php
src/www/system_usermanager.php
src/www/widgets/widgets/ipsec.widget.php
src/www/widgets/widgets/system_log.widget.php

The table attributes 'cellspacing' and 'cellpadding' were moved inside the style attribute via a script. However, they are not valid CSS properties, so browsers should (and do) ignore them.
This commit removes them. The 'table' class, set on most tables, should take care of proper formatting anyway.

Remove nonexistant CSS properties

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/systemactivity.volt

This required teaching jQuery-bootgrid about how to decode the data type.
Previously, it would treat the values as a string, sorting 1G before 10K, and sorting 100M before 11M. Both issues are now fixed.
Alternatively, we could add these data types and converters to our fork of jquery-bootgrid, if we expect to need them in other places.

Fix sorting of SIZE and RES columns in system activity

---

src/www/diag_logs_common.inc
src/www/widgets/widgets/system_log.widget.php

For consistency, I added the line char limit parameter to both `dump_clog` and `dump_log`.

Fix #2960: Limit line length in log widget

---

src/www/system_advanced_network.php

Timestamp is not used for DUID-LL , only the mac address. There is some confusion in the RFC3315 doc. Section 9.4 states that DUID-LL should be the link layer address in canonical form, as described in RFC2464. That doc shows the link-layer part of the DUID would be  xx:xx:xx:ff:fe:xx:xx:xx, however, looking at 'in use' examples of DUID-LL the additional ff:fe centre pair are not used, so I've not added them for Opnsense.

DUID-LL Generator fix

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/+TARGETS
src/opnsense/service/templates/OPNsense/Proxy/parentproxy.conf

Closes #2068 
Example:
```
root@OPNsense:~/core # cat /usr/local/etc/squid/pre-auth/parentproxy.conf
cache_peer 10.24.66.3 parent 8080 0 no-query default
acl ExcludePPDomains dstdomain test.de bla.de
acl ExcludePPIPs dst 1.1.1.1 2.2.2.2
cache_peer_access 10.24.66.3 deny ExcludePPDomains
cache_peer_access 10.24.66.3 deny ExcludePPIPs
cache_peer_access 10.24.66.3 allow all
never_direct allow ExcludePPDomains
never_direct allow ExcludePPIPs
never_direct deny all
```
Reference:
https://forum.opnsense.org/index.php?topic=6763.msg29212#msg29212

Proxy: Add Parent Proxy feature

---

src/www/services_dhcp.php
src/www/status_dhcp_leases.php

Config for dhcpleaseinlocaltime was not being wrtten to the config. Corrected leasetine display routine.

Fix dhcp leasetime ( timezone ) display

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec_phase1.php

This PR allows to use the Hybrid-RSA + XAuth mode of IKEv1. Without these changes, strongswan fails with following error message:
looking for HybridInitRSA peer configs matching x.x.x.x...x.x.x.x[x.x.x.x]
found 1 matching config, but none allows HybridInitRSA authentication using Main Mode
-----
First commit fixes a logical problem in the config form for IPSec Phase 1.
Second commit fixes a problem in the generated `ipsec.conf`: To use Hybrid-RSA with XAuth the authentication must be configured exactly as leftauth=pubkey, rightauth=xauth.
No rightauth2/leftauth2 may be set.
This can be seen here in the source code:
https://github.com/strongswan/strongswan/blob/be1c7e38157b336655894d99012d25f1b3b75429/src/libcharon/sa/ikev1/phase1.c#L506

Generate correct config for "Hybrid-RSA + XAuth" IPSec

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/services.xml
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/opnsense/service/templates/OPNsense/Monit/monitrc

This PR allows setting dependencies in the UI. This allows advanced check behaviour, e.g. VPN <- hosts behind VPN <- service behind VPN on host.
At the moment, the selection of the service as its own dependency is possible, monit shows a dependency loop error in that case with a helpful message. I'm unsure how to restrict the available services to exclude itself from the dependency list.

monit: Support declaring dependencies

---

src/opnsense/mvc/script/load_phalcon.php

include_once returns TRUE if the file has already been loaded. This is not what you want if you're setting a variable from it.
http://php.net/manual/en/function.include-once.php
This fixes notices when including certain old scripts from modern controllers, as well as a notice when running run_migrations.php.

Fix usage of include_once in load_phalcon.php

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/tests.xml
src/opnsense/mvc/app/models/OPNsense/Monit/Migrations/M1_0_8.php
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/opnsense/mvc/tests/app/compound/OPNsense/Monit/MonitTest.php

This solves #2918 and should prevent issues like #3063 :smirk: 
I couldn't implement the connect checks. And for all other special
cases I've added a custom condition with the old freestyle behaviour.
For backward compatibility the migration process adds the 'type=custom' property to all tests.

monit: add Service/Test type relation; improve Service Tests UI

---

src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
src/www/widgets/widgets/monit.widget.php

This PR solves #3126.
Changes:
- fix issue with deleting services via GUI
- replace the pagination with a scrollbar
- make the number of rows to be shown configurable
- add a search filter
Unfortunately I have two small problems that I cannot solve.
The number of rows that are effectively shown is based on a rough estimation of the rendered row height. That can lead to different table heights on different themes.
And there is no translation for the word 'Rows'.

monit: widget improvements

---

src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php
src/opnsense/mvc/app/views/OPNsense/Monit/index.volt

Issues fixed:
- wrong test type validation when saving a service
- unable to delete services via GUI (already fixed in #3147 but not merged yet)
- view/hide fields in modals broken 
The field id's for the General tab are prefixed with monit (rows have row_monit).
In the other tabs they aren't.
Is that intended?

monit: bug fix

---

src/www/vpn_ipsec_phase2.php

This fixes the problem noted in https://github.com/opnsense/core/issues/2833#issuecomment-432543007
This is necessary if you want to add different Phase1 Config for Mobile clients, e.g. IKEv1 for android and IKEv2 for windows 10, but have the same subnet(s) on the connections.

IPSec: allow same Local Subnet if used in different Phase1

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

adds ESD as file type for refresh_pattern of Microsoft Update files. 
example link used by Microsoft:  
http://fg.ds.b1.download.windowsupdate.com/d/Upgr/2018/09/17763.1.180914-1434.rs5_release_clientbusiness_vol_x64fre_en-us_d29ef094928a77496cdf53d072b5023eddea7281.esd

Update squid.conf to add ESD file types

---

src/opnsense/mvc/app/library/OPNsense/Firewall/SNatRule.php
src/www/firewall_nat_out_edit.php

This key is randomly assigned unless set every time the ruleset is
loaded. In order to make it persist, allow setting it to a predetermined
value.

Allow explicitly setting Source Hash Key

---

src/etc/inc/services.inc

When there is more than one CARP address per interface with different
skews, check only the first CARP if and skew in order to determine
primary. This prevents a misconfiguration where both hosts are
configured as dhcp primary due to each host having one VIP with skew <20.
Technically, active/active isn't advisable in general, however we have a setup where we balance clients using separate dhcp pools with different default routers, ensuring clients "stick" to the same firewall except in a failover/maintenance scenario.
Checking the skew of the first VIP should suffice either way, as the recommended configuration is to ensure the same skew for all VIPs on one host.

Fix behaviour of determining dhcp primary/secondary

---

src/www/system_certmanager.php

In certificates list, "show certificate info" button for pending CSR file shows empty dialog, because certificate file is not available yet.
Therefore, it is better to remove this button if no certificate is available.

remove "show certificate info" on certificate list from pending CSR

---

src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogRule.xml
src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml
src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

There was a request on Friday if we support DSCP matching for shaper. @fichtner and me said no, only for `pf` but then I checked ipfw manpage and it looks good.
The beauty of this is, that you can have multiple rules with match any any as you can match for differenct DSCP values, mostly set by SIP phones automatically. Would be a nice addition for enterprise demands.
If pf acts before ipfw in shared forwarding you could also mark rules with pf for DSCP and do the shaping afterwards :)

Shaper: Add DSCP matching

---

src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php

This PR adds test type validation.
It simply checks if a service has a link to a test and refuses to change the type of the test if so.
That means if you want to change the type of a test you have either to remove all links from services or delete and recreate it which does the same in turn.
If I'm not mistaken deleting an alias which is in use by a rule has a similar behavior.
The validation is not performed on full model validations only if the field has changed.
The test type - service type validation is made by the service validation.
I've put it in an extra model function isTestServiceRelated to enable/disable the Test Type dropdown in the GUI later based on the result of this function.
(Don't know how to grab the uuid yet :smiley: )

monit: add validation for test type

---

src/www/diag_logs_settings.php

I came across this while documenting the page. In (almost?) all places we have an enable/disable checkbox, this checkbox comes first, for obvious reasons.

Remote logging: move 'enable' to the top

---

src/etc/inc/certs.inc
src/www/system_certmanager.php

This is a proposal for #3272 . This enables creating a private only for the device who opens admin web page.
This is not elegant for the point that secret key is sent back to the OPNsense, which produces double traffic, but on situation that OPNsense does not want to save the secret key, I thought significant improvement against this is hard.

Add option to create key pair without saving onto firewall on "Create Internal Certificate"

---

src/www/system_general.php

On System > Settings > General, hostname example is translated.
(Like: "Example: ファイヤーウォール" for hostname)
Same as here:
This example contains invalid characters.
(This alerts says that hostname can contain only a-z, 0-9, and -, which is correct.)
As long as I see, Czech and Japanese are affected. French, on the other hand, seems to have a French text which is valid hostname: "pare-feu".

Not to translate hostname example

---

src/etc/inc/plugins.inc.d/ipsec.inc

So this is the PR mentioned here
https://github.com/opnsense/core/pull/3298
It just adds wildcard includes to
ipsec.conf
ipsec.secrets
strongswan.conf
Best regards
Rainer

Implemented wildcard includes for ipsec/strongswan

---

src/etc/inc/interfaces.inc

Hi all,
Since Opnsense 19.x, the main log file used by dhcp6c is system.log, not dhcpd.log like on 18.7
I didnt understand where this change was made, but there is another log related to dhcp6c on dhcpd.log
Maybe the good way is to have a dedicated log file, but on the 19.1.3, it's better to have all dhcp6c-related logs on the same place.
Thanks

Use system log file for rtsold dhcp6c messages

---

src/opnsense/mvc/app/models/OPNsense/Monit/Migrations/M1_0_8.php
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php

This fixes #3334.
@AdSchellevis I had to revert your commit eb280f6 partially because it brakes the migration.
The BaseModel::runMigrations() function makes a serializeToConfig() after BaseModelMigration::run().
But run() fills the test->type with the default 'Custom' which was not allowed.

Monit, remove __items and fix migration issue

---

src/www/system_certmanager.php

We do not need to wrap `$cert['descr']` with `htmlspecialchars` since everything in `$cert` is already html encoded via `legacy_html_escape_form_data`.
Because of double wrapping, Let's Encrypt issued certificate have an awkward looking name as:
**`my.hostname.com (Let&#039;s Encrypt)`**

certmanager: Avoid double encoding cert name

---

src/etc/inc/config.inc
src/opnsense/mvc/app/library/OPNsense/Core/Config.php

Refactoring: Move legacy function cleanup_backups() to OPNsense/Core/Config::cleanupBackups()

Cleanup backups after saving in MVC (Smart-Soft)

---

src/www/diag_confbak.php

When I tried to restore old setting, displayed time on alert was equivalent to unixtime 0. This fix works for me, and this seems to be consistent with the delete line just below modified line.

diag_confbak.php to show correct timestamp

---

src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php
src/opnsense/mvc/app/models/OPNsense/Backup/NextcloudSettings.xml

removes also spaces for more safety.
closes #2647

opnsense/core: automatically remove trailing slash

---

src/opnsense/www/js/opnsense_ui.js

log of 0 is undefined (-infinity in JS), which leads to an error.

opnsense/core: fix file size suffix

---

src/www/services_dhcp_edit.php

This commit fixes a small bug which was introduced with 8e361f3051aa - bootfilename wasn't stored due to typo in the fieldnames of services_dhcp_edit.php.

dhcp: added TFTP bootfile-name (fix for #3074)

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

On current devel mode you get an error while starting squid.
2019/04/28 18:46:56 kid1| Too few /usr/local/libexec/squid/ssl_crtd -s /var/squid/ssl_crtd -M 4MB processes are running (need 1/5)
2019/04/28 18:46:56 kid1|   Took 0.00 seconds (  0.00 entries/sec).
Filename is now: 
security_file_certgen
Syntax is the same:
https://forum.lissyara.su/freebsd-f8/freebsd-11-squid-4-5-prozrachnoe-proksirovanie-s-p-t45437.html
Should stay in master as long as we are on Squid 3.5

Proxy: ssl_crtd was removed with Squid 4.X

---

src/opnsense/www/themes/opnsense/assets/stylesheets/main.scss
src/opnsense/www/themes/opnsense/build/css/main.css

background color fix (see screenshot)
see also fixes for tukan and cicada
https://github.com/opnsense/plugins/pull/1321
@fichtner please merge to clean up the modal problem for all themes

opnsense - core theme modal fix for (19.7)

---

src/www/firewall_rules.php

#rules > thead > tr > th,
#rules > tbody > tr > td,
#rules > tfoot > tr > td {
padding:10px 0px 10px 20px;
}
i set the same values as in 19.1 (main.css)
see -> https://github.com/opnsense/core/issues/3462#issuecomment-489431982

19.7 - Firewall rules - page margin - fix

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/www/services_dhcp.php

While the hardcoded default split of 128 is a perfectly reasonable value there are scenarios where it may be preferrable to only have one peer (eg the primary) give out leases as long as both peers are running. The split-parameter allows to configure what percentage of clients should be handled by either peer in normal mode. It would probably also be an option to implement this as a choice and only allow values of 0, 128 and 256.
there is still an issue with handling of 0 as non-default in this code, I am not sure how to achieve this.
If someone finds the time to review this that would be great, its my first pull-request so I hope I did not screw something up...

added failover_split parameter to configure loadbalancing for DHCPD failover

---

src/www/interfaces_groups.php
src/www/interfaces_groups_edit.php

This now makes it easy and predictable to add interfaces to multiple groups.
Before this change, the interfaces_groups GUI was sorted by the order that interface groups were added. However, this was not the order that the actual pf rules would then be generated making it unpredictable when adding interfaces to multiple groups.
The filter_rules_sort function already took care of the actual pf rule order.
I also took care of only marking the filter subsystem dirty when needed.  I tested this patch quite a bit on 19.1.8. When updating, users only need to make one change to the interface groups to have them sorted in the GUI.
I hope I did not miss anything because this patch is against master. In it’s current state, the patch can be directly applied to 19.1.x or master.

Sort interface groups in GUI to match firewall rule order

---

src/opnsense/scripts/OPNsense/CaptivePortal/allow.py
src/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py
src/opnsense/scripts/OPNsense/CaptivePortal/lib/ipfw.py
src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

closes https://github.com/opsense/core/issues/3559
Our current generated ruleset creates two count rules to match incoming and outgoing traffic to and from the client for accounting purposes. Since ipfw doesn't support table stats, the options are limited to know the amount of traffic processed and last accessed times.
This patch basically replaces the accounting section with seperate blocks, which are jumped to using the exising table (which contains address + rulenumber now), logically this would lower the time needed to parse the accounting section (since only the count rules for the specif ip's are evaulated now).
In terms of ruleset, this will generate 3 rules per address (count from, count to and jump to end of ruleset), like:
```
30001   342    27744 count ip from xxx.xxx.xxx.xxx …
```

Captive portal: optimise ipfw rule parsing.

---

src/etc/inc/plugins.inc.d/dhcpd.inc

DHCP-relay service will fail with the following error if DHCP server IP is know in static route:
dhcrelay: Can't attach interface {ifname} to bpf device /dev/bpf0: Device not configured
This is the only place where get_real_interface( ) isn't used in IPv4 dhcp-relay

Fix IPv4 dhcp-relay 

---

src/www/firewall_rules.php
src/www/firewall_rules_edit.php

Currently the direction of the traffic can only be chosen in floating rules, but in some scenario's it's much easier to create outbound rules (only inbound is supported now).
When using a lot of interfaces, which should all be allowed to access devices on one specific interface, this would save quite some rules and is easier to track for the administrator.
This feature adds direction as on option and while already changing these pages, also allow to create "non quick" rules on interfaces.
Functionally the "regular" rules would be more aligned with the "floating" rules as we have now, with the exception that you can't add multiple interfaces in a normal rule due to the inability to reorder a single rule in multiple rulesets (rules are positional).
Policy based routing on outbound rules is …

Filter egress 3594

---

src/etc/inc/plugins.inc.d/openvpn/wizard.inc

To fix: OpenVPN server wizard always asks to create a new CA #3568
Note: the wizard (and so my fix) currently restricts CAs for which the firewall has the private key. This is because if you choose to create a new server certificate in the next step, it will utilize the selected CA to sign the server certificate.
However, the CA certificate selected ends up filling the "Peer Certificate Authority" field of the OpenVPN Server, and the Peer Certificate Authority does not need to be a CA certificate with private key when you are not using the wizard. Some logic could be added in the future to the wizard to account for all the possible scenarios.

To fix: OpenVPN server wizard always asks to create a new CA

---

src/etc/inc/plugins.inc.d/openvpn/wizard.inc
src/www/wizard.php

This PR fixes the issue I described in #3617.
In the case that both server and non-server certs are present, I chose to have the wizard just filter out non-server certificates from the Server Certificate Selection dropdown.
This is in contrast to the vpn_openvpn_server.php which shows the user all certificates, let's you select a non-server certificate, but then displays an error when trying to save (screenshot of error in issue report.) We can echo this behavior if you think this is a better UX.

OpenVPN wizard server cert check

---

src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml

Monitoring the physical interface really makes sense.
Solves #3495

monit: add parent devices to interface list

---

src/etc/inc/plugins.inc.d/unbound.inc

root.hints file is located at /var/unbound not /
Current users may not be leveraging root.hints with unbound deployments.

Set absolute path to root.hints

---

src/opnsense/mvc/app/models/OPNsense/Monit/Migrations/M1_0_0.php
src/opnsense/mvc/app/models/OPNsense/Monit/Migrations/M1_0_6.php
src/opnsense/mvc/app/models/OPNsense/Monit/Migrations/M1_0_7.php
src/opnsense/mvc/app/models/OPNsense/Monit/Migrations/M1_0_8.php
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php

This PR adds missing test types to the migrations.
The migrations use the `post` method now instead of `run` to
avoid validation errors.
Solves #3659

monit: fix migration

---

src/www/system_advanced_sysctl.php

There is a note at the bottom of the tuneables which states that some changes are applied directly and some require a reboot. 
In my opinion a more logical notification would be to show that sentence in the Apply notice box in stead of at the bottom of this page. That location can be easily overlooked.

Cosmetic changes to Tunables section

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/KeyPairsController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/LegacySubsystemController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/KeyPairsController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogKeyPair.xml
src/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.php
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Menu/Menu.xml
src/opnsense/mvc/app/views/OPNsense/IPsec/key_pairs.volt
src/opnsense/service/conf/actions.d/actions_ipsec.conf
src/www/vpn_ipsec_phase1.php

**Feature Description**
The current IPsec plugin implementation does not support public key authentication, which allows for a more secure mutual authentication than PSK while still not introducing the complexity of X509 certificates. The authentication can easily be set up by generating a bare RSA keypair chain on both machines, followed by exchanging the public keys between the two peers.
This commit introduces public key authentication functionality by adding a new authentication method to phase 1 configuration called "Mutual Public Key" and adding a menu entry "Public Key Authentication", which allows adding public keys (+ optional private keys). It was successfully tested against a Linux virtual machine running Strongswan 5 and the entered RSA keys are automatically verified for …

ipsec: Add support for public key authentication

---

src/opnsense/service/templates/OPNsense/Auth/sshd.pam

As of today sshd prompts hostname on client side (leaking info):
`Password for root@OPNsense.private.:`
Proposal is to change it to be only:
`Password:`

Hide leaking hostname on SSH password auth

---

src/opnsense/service/conf/actions.d/actions_captiveportal.conf
src/opnsense/service/conf/actions.d/actions_ipsec.conf

This adds descriptions to the restart action of Captive Portal and IPSec. Both services may use a Let's Encrypt certificate.
This is necessary in order to setup an automation in our Let's Encrypt plugin to automatically restart the service when the certificate was renewed:
https://github.com/opnsense/plugins/blob/a878826c05ff470ab2a5001cf9f26b153a1f7bcf/security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml#L860-L866
Without a description the action is not visible in the GUI (for good reasons).
refs https://github.com/opnsense/plugins/issues/1534

captive portal/ipsec: add description to restart actions

---

src/etc/inc/plugins.inc.d/dhcpd.inc

The "domain-search" option in dhcpdv6.conf must be prefixed with "dhcp6". This fixes one of the issues from #2336 which are still open.

DHCPv6, fix for domain-search option

---

src/etc/inc/plugins.inc.d/dhcpd.inc

Always add dhcp6.domain-search and dhcp6.name-servers to dhcpdv6.conf, even if no range6 is specified.

Fix stateless DHCPv6 mode

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec_phase1.php

As stated in #3821, making the `dpdaction` configurable comes in handy for IPsec `start on traffic` CARP clusters for a clean failover.
I've added a `default` option, to not break existing setups.

Make strongSwan's dpdaction configurable

---

src/www/services_dhcpv6_edit.php

If adding static mapping v6 addresses then replace the windows dashes with colons automatically. Makes life a lot easier if there's a whole bunch to do.

Auto Replace windows DUID dashes

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound_advanced.php

The 'custom options' field is deprecated + does not work for these fields since it places the contents out of the 'server:' context. E.g. adding:
```
log_queries: yes
extended_statistics: yes
```
To the field creates an invalid config which blocks the service from starting.
These boolean fields allow the options to be used and are future proof in case the custom options field gets removed.

Unbound: Add options for logging queries and extended statistics.

---

src/www/status_dhcp_leases.php
src/www/status_dhcpv6_leases.php

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
[X] I have searched the existing issues and I'm convinced that mine is new.
**Is your pull request related to a problem? Please describe.**
I find it difficult to distinguish between "offline" and "online" when I look at the list of DHCP Leases. The two words look very similar, and it is hard to scan the column visually.
**Describe the solution**
My commit adds an icon in front of the "online" or "offline" text to make it easier to distinguish the two states from each other at a glance. I chose the `signal` and `ban-circle` glyphicons. I don't have a strong opinion about the particular icons used as long as they make sense and maintain a good enough visual distinction.
**Describe …

dhcp: add icons next to online/offline lease status

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec_phase1.php

Since OPNsense already has a mode to automatically open security associations when needed with the `start on traffic` option, I think it might come in handy for people to automatically tear down security associations when not sending or receiving traffic over a certain timespan (and create those again when needed).
This option is already seen on numerous Firewall vendors, for example on a Cisco ASA.
Luckily, strongSwan offers an option for this via the `inactivity` parameter, so I made it configurable.

Make strongSwan's inactivity parameter configurable

---

src/etc/inc/plugins.inc.d/dhcpd.inc

The Router Address flag "indicates that the Prefix field contains a complete IP address assigned to the sending router" (RFC 6275). This does not apply, we only send a prefix. This flag is only relevant for Mobile IPv6.
It has been there (for unknown reasons) since pfSense switched to radvd 8 years ago: https://github.com/pfsense/pfsense/commit/3f9cc8e44c5b50e588f0f916611ffa37f7ae0bcb

radvd: don't set Router Address flag

---

src/etc/inc/plugins.inc.d/dhcpd.inc

As discussed in #3310. For tracking LAN interfaces with manual configuration disabled, some odd radvd configuration choices were made:
MinRtrAdvInterval / MaxRtrAdvInterval were set to very low values (3 / 10) for no apparent reason. Now removed so radvd defaults (200 / 600) will be used.
The DHCPv6 server is enabled and configured with a range6, but the Managed flag was not set. Now set to on.
DeprecatePrefix was only set if the IPv6 configuration type of the tracked WAN interface was SLAAC. Now always set to on.

radvd.conf for tracking LAN interfaces, cleanup

---

src/opnsense/mvc/app/library/OPNsense/Auth/Voucher.php

Always check if voucher is not expired (either
because of never expires or because of expiry
date is in the future) and ensure session timeout
will be the lowest of validity based on the first
usage, the starttime or expiry (if not never expires).
If one of those conditions is not true, reject
authentication.
Fix #3930

(Auth) fix expiry and validity for vouchers

---

src/etc/inc/plugins.inc.d/unbound.inc

192.0.0.0/24 is not a private net. ipv4only.arpa resolves to 192.0.0.170 and 192.0.0.171. This is required for DNS64 prefix detection (RFC7050).
(Quick way to verify: Lookup ipv4only.arpa via Google DNS / Cloudflare DNS / whatever. Resolves to 192.0.0.170 / 192.0.0.171. But doesn't resolve via OPNsense's unbound.)

unbound: remove 192.0.0.0/24 from rebinding prevention list

---

src/etc/inc/plugins.inc.d/dnsmasq.inc
src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_dhcpv6.php
src/www/services_dhcpv6_edit.php
src/www/services_dnsmasq.php
src/www/services_unbound.php

'domain' was removed in #3824 because it is not used by dhcpdv6. But it is used by unbound and dnsmasq for DNS registration of DHCP static mappings. Just set it to the first entry of the domain search list.
Closes #3945.

DHCPv6 static mappings, fix DNS registration

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec_mobile.php

The feature is described at https://github.com/opnsense/core/issues/3852.
Known OPNsense limitations:
- multiple IKEv2 mobile servers use the same IPv4 and IPv6 pools - ipsec.conf file lets us set individual pools to each mobile server independently, but the current configuration model adopted in OPNsense web UI does not provide for matching tunnel settings to mobile clients profiles - it might be a feature;
- automatic outbound NAT rules (in [filter.lib.inc](https://github.com/opnsense/core/blob/master/src/etc/inc/filter.lib.inc#L196-L199)) include only IPv4 pool, since IPv6 NAT is discouraged - a checkbox can be introduced somewhere to let the admin decide whether to create a NAT rule for IPv6 pool or not - it might also be a feature.
Known protocol and/or client limitations (checked …

IPsec: add virtual IPv6 pool for mobile clients

---

src/etc/ssl/opnsense.cnf

This PR fixes text inconsistencies in nsComment and disables nsComment and nsCertType extensions as they are deprecated. See [OpenSSL manual](https://www.openssl.org/docs/man1.0.2/man5/x509v3_config.html) for details.
I divided this PR into two independent commits so that you could accept only the first one in case you are against disabling deprecated Netscape extensions for any reason. However, as the use of such extensions is officially discouraged and major authorities (e.g. DigiCert, Let's Encrypt) do not include them into their certificates, it seems reasonable to follow the recommendations. Those who need these extensions may always enable them manually in OpenSSL configuration file.
The tables below illustrate nsComment and nsCertType values depending on certificate type.
| …

Fix deprecated Netscape extensions in OpenSSL config

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasUtilController.php

Currently the API has a strange behavior when we try to add or delete in parallel several addresses in the same alias
For example, while we want to delete multiple address  (1 request = 1 address) all the request returns a 200 OK {"status": "done »}, but some address stay in the alias content
The same logic apply for the alias_utils/add endpoint
This behavior can be reproduced with this python script
import os
import subprocess
addr_list = ["10.1.0.0", "10.1.0.1", "10.1.0.2", "10.1.0.3", "10.1.0.4",
"10.1.0.5", "10.1.0.6", "10.1.0.7", "10.1.0.8", "10.1.0.9", "10.1.0.10"]
secret = ""
key = ""
host = ""
existing_alias = ""
for addr in addr_list:
subprocess.Popen(
["curl   --header \"Content-Type: application/json\"   --basic   --user \"" + secret + ":" + key + "\"   --request POST  --data …

Allow concurrent add and delete request with alias_util API

---

src/etc/inc/filter.inc
src/etc/inc/interfaces.inc
src/etc/inc/plugins.inc.d/pf.inc
src/etc/rc.newwanip
src/etc/rc.newwanipv6
src/www/interfaces_groups_edit.php

for https://github.com/opnsense/core/issues/3780
It doesn't really seem to make sense to try to link groups on different places, if they're only usable for pf which is always reloaded when new interfaces are connected.
The new ifgroup_setup() synchonizes attached interfaces for all configured groups, only rename and delete are still being served from the management pages (to avoid dropping static groups like openvpn).

ifgroups: simplify group maintenance for 

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/www/services_router_advertisements.php

As I mentioned in #4063, some edge cases may cause instability issues on IPv6 connectivity by relying to the target interface MTU for RA. This PR adds an override to the AdvLinkMTU.

Add AdvLinkMTU to Router Advertisements page

---

src/etc/inc/interfaces.inc

Dhcp6c multiwan

---

src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml

Adding:
Aho-Corasick, reduced memory implementation
Aho-Corasick, "Ken Steele" variant
Controls the pattern matcher algorithm. Aho–Corasick is the default. On supported platforms, Hyperscan is the best option. On commodity hardware if Hyperscan is not available the suggested setting is "Aho–Corasick Ken Steele variant" as it performs better than "Aho–Corasick".
https://github.com/opnsense/core/blob/master/src/opnsense/service/templates/OPNsense/IDS/suricata.yaml#L1439
https://suricata.readthedocs.io/en/suricata-5.0.3/performance/tuning-considerations.html#mpm-algo-ac-hs-ac-bs-ac-ks
Documentation updated as well: https://github.com/opnsense/docs/pull/256

Updated Pattern Options for IDS/IPS

---

src/opnsense/mvc/app/library/OPNsense/Backup/Nextcloud.php

LDAP accounts need the UUID to be used at file system access instead of the real username but the real username is still needed for authentication.
closes #4080

nextcloud: add support for upstream LDAP accounts - #4080

---

src/opnsense/mvc/app/models/OPNsense/Unboundplus/Miscellaneous.xml

CSVListField needs comma for validator, also 46 chars is only one v6 address without shortening.

Unboundplus: fix DoT validations

---

src/opnsense/scripts/suricata/installRules.py

Further to the changes in https://github.com/opnsense/core/commit/38ea28d0ad24ce82ac3106e2ee9dc35088fbdb92
The installRules.py script also needs to handle an extra space in the rule.

When enabling rules prefixed with '# ' consume the extra space

---

src/etc/inc/plugins.inc.d/dhcpd.inc

Only marry live prefix to user-specified range if range is not empty.
Bug report in the forum: https://forum.opnsense.org/index.php?topic=17423.0

dhcpdv6, fix stateless mode for track6 interfaces

---

src/opnsense/mvc/app/views/OPNsense/Proxy/index.volt

Fixed an issue that causes a duplicate label in https://opnsense/ui/proxy#remote_acls:
(2 x "Download ACLs & Apply instead of "Download ACLs & Apply" and "Download ACLs")
Signed-off-by: Wolfgang Hofbauer <wolfgang.hofbauer@techz.one>

Proxy: fix wrong button label for Download ACLs

---

src/etc/inc/interfaces.inc

pdinfo could get deleted by a renewal or  event other than release or exit. These changes make the creation of the pdinfo file only on a REQUEST reply flag and only delete on a RELEASE or EXIT flag

Fix Show ISP Assigned PD in status interfaces

---

src/etc/rc.subr.d/recover
src/opnsense/service/templates/OPNsense/WebGui/php.ini

PCRE's JIT is incompatible with PaX NOEXEC. In order for PaX NOEXEC to
work well with PHP, disable PCRE's JIT.
Signed-off-by:	Shawn Webb <shawn.webb@hardenedbsd.org>
Sponsored-by:	BlackhawkNest

Hardening: Disable PCRE JIT in PHP config

---

src/www/vpn_ipsec_phase2.php

When AES-GCM encryption is selected the hashing algorithm should be NULL as AES-GCM has message authentication built in.
The PHP warning raised by supplying in_array() with an empty string results in warning on the dashboard that links to:
[12-Jun-2020 17:08:01 Pacific/Auckland] PHP Warning:  in_array() expects parameter 2 to be array, string given in /usr/local/www/vpn_ipsec_phase2.php on line 713

Valid IPSec Phase 2 hash config warning raises GUI alert.

---

src/opnsense/mvc/app/controllers/OPNsense/TrafficShaper/forms/dialogRule.xml
src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml
src/opnsense/service/templates/OPNsense/IPFW/ipfw.conf

As discussed in #4132 and prompted by #528 
This change enables users to set the maximum packet length a rule should be applied to. Tested on a production system.

Add the iplen option to shaper rules

---

src/www/status_ntpd.php

Improved the solution proposed in issue #4209 to handle potentially variable number of digits in NMEA message Latitude and Longitude. Degrees and minutes are read still into _deg and _min variables from string, separated by minutes decimal point. FIx is to move the whole minutes from _deg to _min.

ntpd: NMEA GPS clock messages lat and lon parsing fix #4209

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Hello
This is a suggestion to enable the PURGE method for handling Squid cache.
Once local disk cache is enabled, the ACL is ready and at this moment on CLI:
squidclient -v -m PURGE http://....
will remove a wrong cached file
Could be available through portal and/or enhanced the current ACL to ask for authentication...
Thanks in advance for your attention.

Squid - Allow PURGE on cache

---

src/opnsense/scripts/unbound/dnsbl.py

These links were updated to reflect the current hosting platform that allows for last-modified header.

Updated Project Block Lists Links

---

src/opnsense/scripts/filter/find_table_references.py

we can use pfctl to check IP against tables
-its exclusions aware
-this should be more accurate because check tables in pf after table loading (with deduplicating, conflict checking etc)

find_table_references.py: use pfctl for IP check

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/generalSettings.xml
src/www/system_advanced_network.php

Current help texts do not contain complete information to prevent users blocking network access if IPS mode **and** hardware accelerations are enabled. See issue discussion and [this posting plus follow-ups](https://forum.opnsense.org/index.php?topic=13600.msg62833#msg62833).
This PR aims to include information for all relevant settings.

Improve IPS mode help to avoid blocking network access, issue #4257

---

src/etc/inc/plugins.inc.d/dhcpd.inc

Relating to #4356, when defining additional pools with DDNS values, the corresponding zone and key declarations were not added to /var/dhcpd/etc/dhcpd.conf
This will add zone and key declarations to dhcpd.conf based on DDNS values provided in each additional pool within a subnet.

Add zone declarations of additional pools in dhcpd.conf - Fix for #4356

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php

In 6f76b5f the displayName attribute was added as the first camel case
attribute being read from the search result. As various[^1] comments[^2]
for `ldap_search` mention the attribute names must be lower case, even
though the LDAP server might return them differently.
Using all lower case to access the returned attribute results in the
value of displayName actually being used as the full name of the user.
[^1]: https://www.php.net/manual/en/function.ldap-search.php#37317
[^2]: https://www.php.net/manual/en/function.ldap-search.php#28991

Auth/LDAP: Fix reading displayName attribute

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.conf

This adds a checkbox to allow the pinger service in squid to be disabled. It edits the squid.conf to add 'pinger_enable off' which is currently on be default. The pinger service seems to be only really required when using peer / parent proxy.
I raised a question on the forum:
[https://forum.opnsense.org/index.php?topic=19289.0](https://forum.opnsense.org/index.php?topic=19289.0)
Squid doco:
[http://www.squid-cache.org/Doc/config/query_icmp/](http://www.squid-cache.org/Doc/config/query_icmp/)
[http://www.squid-cache.org/Doc/config/pinger_enable/ ](http://www.squid-cache.org/Doc/config/pinger_enable/ )
I'm really new to git, github, and programming in general, so accept apologies if I have gone about this the wrong way, and feel free to delete.

Add toggle for pinger service in proxy settings

---

src/etc/rc.syshook.d/monitor/10-dpinger

Dpinger actually reports RTT and RTTd in µs.

Change dpinger syslog message to reflect correct RTT and RTTd unit

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.acl.conf

This adds:
- Google Suite personal accounts blocking: when enabled, block any account outside of the specified domain. Very useful to limit access to Google Drive, Gmail inside corporate networks. (ref.: https://support.google.com/a/answer/1668854?hl=en)
- Youtube: Strict and Moderate modes to avoid young people access some videos with violent or sexual content. Very popular in schools networks. (ref.: https://support.google.com/a/answer/6212415?hl=en) 
**Both requires SSL interception enabled!**

Add GSuite and Youtube filtering in proxy

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/www/services_dhcp.php
src/www/services_dhcpv6.php

The min-secs option allows to configure a delay of 0-255 seconds before a DHCP server responds to a client's request. This can be used to set up a secondary DHCP server as stated in the [manual](https://www.freebsd.org/cgi/man.cgi?query=dhcpd.conf&sektion=5&apropos=0&manpath=FreeBSD+12.2-RELEASE+and+Ports). This PR contains changes for both v4 and v6, however I have not tested the latter much.

DHCP: Add min-secs option for each subnet

---

src/www/services_dhcp_edit.php

As we had the discussion on the forum in the last days, I had a look at the software OPNsense is using as DHCP server. As it turns out it is ISC DHCP, so there is no need to keep the static leases outside of the pool.
Just removed the check from the PHP file and changed one description in line 326 (do I need to do something about translations here?).
Copied the file to my test OPNsense and I was able to set a static lease within the pool. Client was receiving the correct IP.
Old line 144 was not needed anymore as we're already checking this in line 117.

DHCPv4: Removed the need for a static IP being outside of the pool

---

src/etc/inc/util.inc
src/www/services_dhcpv6_edit.php

**Issue:**
The DHCPv6 static mappings are shown in the order they were added. Sorting code exists but won't work. 
**Reason:**
The ipcmp() function doesn't seem to return a correct result for IPv6 addresses. 
**Solution:**
Introduce ip6cmp() function and fix sorting of IPv6 static mappings.
**Version:**
OPNsense 20.7.6

DHCPv6: Fix sorting of IPv6 static mappings

---

src/www/diag_ipsec.php

Add a new 'Remote Host' column to the IPsec status overview page.

Display remote host in IPsec Status Overview

---

src/opnsense/mvc/app/library/OPNsense/Base/Filters/QueryFilter.php

Hi!
it is not forbidden to use the underscore sign in the filter string?
(want to use it in the search in the system log widget and system->log files)
Thanks!

QueryFilter.php: allow underscore in filter string

---

src/etc/inc/plugins.inc.d/dhcpd.inc

Custom Options is incorrectly inserting quotes around the integer value. Issue 4542
Added code to differentiate between numeric or text option, same as v4 Options.

Correct DHCPv6 Custom Options Unsigned Integer field

---

src/www/diag_system_pftop.php

The html element of the "all" value in the pftop diagnostics view currently does not match the array value. For this reason, the option has no effect. The number of states is always set to the default value of 200.

pftop: fix all state value

---

src/www/status_dhcpv6_leases.php

This is a *hopeful* fix for Issue #4423. I've only tested the code in isolation (not in opnsense itself!), but I hopefully it should fix the issue. Please make sure to test before merging.

Hopeful fix for #4423 - Incorrect parsing of DUID in dhcpd6.leases.

---

src/opnsense/scripts/unbound/download_blacklists.py

proposed fix for https://github.com/opnsense/core/issues/4595
also changed "if chop[-1]" to "if parts[-1] != "\n":" (checking an array is more correct than checking an incoming string?)
second "parts.pop()" in line65 just for array  cleanup (so as not to yield "\n" only).
checked on https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt and
https://blocklistproject.github.io/Lists/fraud.txt (without ending "\n")

download_blacklists.py: fix broken lines in large files

---

src/www/vpn_openvpn_server.php

Hi!
NetBIOS options in server config looks a bit ugly (especially in dark themes).
Can we add a couple of breaks to prettify it?
before:
after:
Thanks!

vpn_openvpn_server.php: netbios options prettify

---

src/etc/inc/interfaces.inc

**Issue:**
DHCPv6 leases have an empty interface field when IPv6 address belongs to /120 subnet.
**Reason:**
Incomplete preg pattern used to find possible IPv6 subnets in guess_interface_from_ip() function.
**Solution:**
Apply a consistent approach of using is_subnet{v4,v6} to find possible subnets.
**Other:**
This PR is a part of changes proposed by [#4514](https://github.com/opnsense/core/pull/4514).

interfaces.inc: Improve guess_interface_from_ip()

---

src/www/widgets/widgets/interface_statistics.widget.php

This adjusts to the user's preference: in an English browser, 1234567890 will be shown as 1,234,567,890. JavaScript is already required for widgets to work, adding these toLocaleString calls is not an issue in that regard, and the function is supported in all browsers as far as I can see https://caniuse.com/mdn-javascript_builtins_number_tolocalestring
The current packet count column is very hard to read at a glance. Since one may want to see whether packets are going through the interface at all, and you already can't tell that from the data column (as that is shown in MB/GB/...), I figured we wouldn't want to hide the last few digits by making it shown 5k/5M/5G or something. Formatting the number with the user's local settings seemed like the best option to me.

Format packet count with toLocaleString in dashboard widget

---

src/etc/inc/interfaces.inc

Builds upon the 6rd routing fixes discussed in https://forum.opnsense.org/index.php?topic=20260.0
Instead of setting the calculated /64 subnet length on the _stf interface, I set the original ISP provided subnet length.
And change the gateway to be inside the ISP provided prefix instead of the calculated /64.
wan address will still be the same but the wider subnet solves any routing issues with single /64 prefixes.

fix issue #4025: 6rd with single /64 prefix

---

src/www/firewall_rules.php

When a rule is set to Allow, Block or Reject, the icon is `fa-play`, `fa-times` and `fa-times-circle` respectively.  When you toggle a rule to disable it, the code in `firewall_rules.php` changes the icon to `fa-play` (Allow Icon) regardless of it being Block or Reject, which is confusing.  
Due to the order of how things are defined in the CSS, Reject and Allow work fine, but Block does not.  Since `fa-spinner fa-pulse` appears to be defined later in CSS than the indicators, it takes priority for the icon.  When removed, it restores the proper icon with the appropriate `text-muted` or `text-success`.  I think we can safely remove the `fa-play` from the toggle, which will fix the Block icon.
Example of issue by clicking it a couple times..

firewall: Fix Icon Toggle for Block

---

src/www/services_unbound.php

The old URL gets redirected to the start page of Unbounds documentation, this one directly links to the `local-zone` part of the "new" unbound.conf documentation.

Update Unbound Documentation URL

---

src/etc/inc/plugins.inc.d/dhcpd.inc

As discussed back in #3343: Router Advertisements should never contain a ::/0 route. A default route is indicated by setting the Router Lifetime to > 0. This was originally fixed by @fichtner in e67dade991d631d7edba5b750a87396b38bac2e1, but the ::/0 route is still added for CARP interfaces and "static mode" interfaces (introduced in 66dc0e9b29ec3d7fbe2446faf057116e6a9b6337).
I only noticed this after recently switching to static interface mode.

radvd: don't advertise ::/0 route

---

src/etc/inc/plugins.inc.d/openvpn.inc
src/etc/inc/plugins.inc.d/openvpn/wizard.inc
src/opnsense/mvc/app/library/OPNsense/OpenVPN/PlainOpenVPN.php
src/www/vpn_openvpn_client.php
src/www/vpn_openvpn_server.php

This PR deals with OpenVPN compression configurations for both servers and clients. The [official documentation](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/) suggests using the option --compress instead of the deprecated --comp-lzo. It allows to use the LZ4/LZ4 v2 algorithms in addition to the LZO. Besides, in view of the [VORACLE attack](https://community.openvpn.net/openvpn/wiki/VORACLE), the stub/stub v2 algorithms are made available.
Before:
After:
This is a part of the changes requested in #2048.

OpenVPN: Enhance configuration - Compression

---

src/www/system_usermanager_settings_ldapacpicker.php

Make StartTLS work when retrieving LDAP authentication containers. The code did not set the LDAP connection properties as configured and thus connected as if `TCP - Standard` was selected.
Fixes #4453 (currently erroneously already closed)

LDAP bugfix: use StartTLS as configured when retrieving authentication containers

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt

Hi!
table is empty if "Select any of given criteria (or)" selected and filter is empty

fw_log.volt: show rows with 'or' and empty filter

---

src/opnsense/scripts/dns/unbound_dhcpd.py

Cleanup local data cache when a DHCP endpoint expires, so that it is
kept in sync with dynamic changes.  This ensures that if an expired DHCP
endpoint returns and is assigned the same IP address the local cache is
correct and doesn't block the entry being dynamically re-added to Unbound.
Also don't cache the blacklist entries, which aren't needed to manage
the DHCP DNS entries. There can easily be 1M+ blacklist entries, so
ignoring these improves startup speed and reduces memory footprint
Fixes #4714

Unbound: Handle DHCP client expiring and returning

---

src/etc/inc/interfaces.inc

When a PPPoE down event happens the dhcp6c.conf file does not get re-written thus leaving the config section for that link. This results in errors from dhcp6c and possibly delays when the link is re-established,
It happens because the interface_bring_down returns when it's a PPPoE link without calling an update using interface_dhcpv6_prepare() and a HUP to dhcp6c.

Correct dhcp6c.conf issue on pppoe link down

---

src/etc/inc/plugins.inc.d/unbound.inc

Correct the omission of the prefix when a dynamic interface v6 dhcpdv6 address is set as a static entry. The result is that only the suffix /64 gets added to the unbound host entries. This patch should sort that so a full address is created for unbound.
Resolves #4712

Correct static address on an address where dhcpdv6 entry is an override

---

src/opnsense/scripts/dns/unbound_dhcpd.py

Move deletion of dhcp cache info when the lease expires to after the
last reference to the cache information.
Fixes #4741

Unbound: Fix bad dereference when DHCP lease expires

---

src/www/services_dhcpv6.php

Range help refers to WAN, should be LAN, added ( PD ) to make it even more obvious,

Correct help text for Range

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php
src/www/diag_authentication.php
src/www/system_authservers.php

Hi!
based on https://forum.opnsense.org/index.php?topic=21605.0
- baseDN igonred in search function if ldapauthcontainers is set. help text for "Authentication containers" input fixed
https://github.com/opnsense/core/blob/25959a45a918000c36d092403ac3e3c223c4671a/src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php#L160-L163
- In select "Authentication containers" modal Close button is actually a Save button (writes changes to the "Authentication containers" input)
- Some debug info added to System: Access: Tester page for LDAP servers
thanks!

LDAP minor fixes

---

src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php

Hi!
looks like a typo (outbound nat rules uses 'network' for aliases. not 'address').
https://github.com/opnsense/core/blob/3277c0beb6f3ecb957fef0e95ae0562cea43eb99/src/www/firewall_nat_out_edit.php#L286-L297
closes https://github.com/opnsense/core/issues/4778 imho (tested on vm)
thanks!

Alias.php: typo in dst type

---

src/www/index.php

Hi.
This can help to get rid of double event bindings in widgets when manipulating DOMs.
Also fixes https://github.com/opnsense/core/issues/4750 on my test vm without changing to $( document ).ready

Dashboard: cut scripts from widgets before move

---

src/www/index.php
src/www/widgets/widgets/traffic_graphs.widget.php

Hi!
after a long investigation in the "messages" on the forum, it turned out that the traffic_graph widget is still not quite stable in the Firefox browser. The FF can start requests before the widgets are visible. As a result, the chart plugin assigns the canvas height to 0 (chartjs does not like if the parent element is hidden when the chart is initialized) and it start to look like https://github.com/opnsense/core/issues/4750.
To reproduce the behavior, you can set a breakpoint on the `        $("#traffic_graphs-configure").removeClass("disabled");` in FF and refresh the page. It should be seen that the widgets div are not yet visible before executing the request.
Could you consider adding an event after placing widgets and launching a widget functions on this trigger?
This change …

traffic_graphs.widget: start when widgets is visible

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php

Hi!
Can we add just one another LDAP error handler when looking for OUs? It turned out that sometimes it can be a simple time out.
https://forum.opnsense.org/index.php?topic=21605.msg103863#msg103863
Thanks!!

LDAP.php: one more error handler

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/CategoryController.php
src/www/javascript/opnsense_legacy.js

This commit adds the option of filtering on (No Category) in the firewall rules. A tooltip for visual aid is also added. In order to run static text through gettext(), a separate API endpoint has been created. This is a clean PR and invalidates the old one (https://github.com/opnsense/core/pull/4775) since it was pretty messy.

firewall: categories improvements

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasUtilController.php

Hi!
sorry, did not take into account when I made https://github.com/opnsense/core/pull/4579
should sort before slice for correct column sorting (now sorting sliced part of ip-sorted array)
closes https://github.com/opnsense/core/issues/4577 correctly

Diagnostics->pfTables: sort before slice

---

src/opnsense/scripts/firmware/health.sh

To avoid self-contradictory output:
>>> Check installed kernel version
Version 21.1.3 is correct.
Cannot verify kernel: missing /usr/local/opnsense/version/kernel.mtree.sig
>>> Check for missing or altered kernel files
No problems detected.
Now we will instead get:
>>> Check installed kernel version
Version 21.1.3 is correct.
Cannot verify kernel: missing /usr/local/opnsense/version/kernel.mtree.sig

firmware/health.sh: refine missing/invalid signature message

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/traffic.volt
src/www/widgets/widgets/traffic_graphs.widget.php

Hi
just https://github.com/opnsense/core/commit/3d3810b42d1664087594ecc8fadc43568056220c alternative
uses internal time formatting instead of additional `moment` use
don't think it's faster - just fewer lines of code
thanks!

Reporting / Traffic (+dashboard widget): 24H format alternative

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
src/www/widgets/widgets/log.widget.php

Hi!
replaces https://github.com/opnsense/core/pull/4817 and possibly closes https://github.com/opnsense/core/issues/4815
- no `legacy_config_get_interfaces`
- multiple choice of interfaces
- no `toLowerCase()`
- not reading DOM attrs for each log entry
- starts on "WidgetsReady" for Firefox consistency on page refresh (bootstrap not applied on 'load' after F5. so FF generates second `<button>`)
widget works on driver-names and is indifferent to upper\lowercases from the API
thanks!
UPD
- added changes for https://github.com/opnsense/core/issues/4836 
bootstrap popover on Action icon hover with rule number and description (if any) display.
open ruleID-prefiltered Live View on Action icon click
ie11,chrome,FF tested )
thanks!

firewall log widget: multiple interface choice, popovers, link to Live View

---

src/opnsense/scripts/unbound/download_blacklists.py

Fix missing ')' at the end of log line:
before fix: blacklist download https://block.energized.pro/bluGo/formats/hosts (lines: 125888 exclude: 5 black: 125814
after fix: blacklist download https://block.energized.pro/bluGo/formats/hosts (lines: 125888 exclude: 5 black: 125814)

Fix missing ')'

---

src/www/firewall_nat_npt.php
src/www/firewall_nat_npt_edit.php

- The length of the internal and external prefix must match. If non-identical prefix lengths are selected, an error is logged (_'binat' source mask and redirect mask must be the same_) and no pf rules are created. Remove the external prefix length selector and use the internal prefix length for both.
- If either one (or both) of the "Invert" options are enabled, an error is logged (_syntax error_) and no pf rules are created. Remove.
- The "Source" / "Destination" terminology is a little confusing and doesn't match the "Internal" / "External" terminology used on the rule overview page. Rephrase.

NPTv6 configuration clean-up

---

src/opnsense/scripts/unbound/download_blacklists.py

Hi!
started testing unbound with a new regex-check and it looks like we forgot to escape the string for a complete match - allows entries with url on first match. 
-match the entire string to prevent garbage after valid fqdn
-add to skip stat if not match

unbound dnsbl: yet another change in regex

---

src/www/firewall_rules_edit.php

A lot of OPNsense users become confused by the concept of traffic direction in firewall rules (despite this being covered in the official documentation). This change is to expand the help text that is shown in the webgui for the Direction option in the firewall rules, along the lines of the official documentation, to hopefully to provide more clarity for users. Feel free to accept or decline in your discretion!

webgui: clarify help text for firewall rules traffic direction

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/www/services_dhcp.php

A lot of clients boot into two modes one of which doesn't send uids, which means they get different IP addresses when they boot. For instance, if they need a decrypt password at boot time to unlock the root drive. 
Another instance where the uids change is when the machines are vagrant containers, or if they dual boot windows.
The dhcpd server already provides the `ignore-client-uids` configuration for this case. This patch just exposes the function.
Fixes opnsense#3673

dhcpd4: support ignore-client-uids

---

src/www/widgets/widgets/interface_statistics.widget.php

Rotate interface statistics widget, this fixes the issue where after x number of interfaces, the widget's interfaces go off the screen, causing an unwanted horizontal scroll bar.
This PR is for this feature request https://github.com/opnsense/core/issues/4510
Before
After

Rotate interface statistics widget

---

src/opnsense/mvc/app/library/OPNsense/Firewall/NptRule.php

Omits the erroneous reverse binat rule which causes issues with reply-to in firewall rules. Closes #4879.

NPTv6: remove reverse binat rule

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt

When the Edit panel is opened to edit an existing Dynamic IPv6 Alias, the proto type is visible. If you select another type of Alias and then return to the Dynamic IPv6 type the proto has gone. This PR just adds a hide proto selectpicker.

Edit Alias fix

---

src/etc/inc/plugins.inc.d/webgui.inc

An HSTS cache validity period of less than 1 year is no longer considered to be sufficiently secure and might fail various audits.
References:
https://internet.nl/article/new-release-with-improved-tests-for-TLS-and-CSP/
https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/http-strict-transport-security-hsts-max-age-value-too-low/
https://hstspreload.org/

lighttpd: set HSTS max-age to 1 year

---

src/opnsense/scripts/shell/setaddr.php

Before this change, it wasn't clear what one would revert from, as there was no context being given.

shell: Clarify revert to HTTP

---

src/www/system_camanager.php
src/www/system_certmanager.php

The "Distinguished name - organisation" field is quite limited in what is allowed in it. Even just having a comma or fullstop was prohibited.
Searching through the docs of openssl I could not find a reason to block those, so here's a PR to allow those characters specifically in the organisation fields.

Allow more characters in the "Distinguished name - Organisation" field

---

src/www/status_dhcp_leases.php

**Issues in status_dhcp_leases.php for which this PR suggests a solution:**
- Insecure handling of the order argument
- Use of strnatcasecmp() instead of ipcmp() for sorting by ip
- Impossible to sort by interface name
**Other:**
This PR is a part of changes proposed by [#4514](https://github.com/opnsense/core/pull/4514).

DHCPv4 leases status: Fix sorting

---

src/www/status_dhcpv6_leases.php

**Issues in status_dhcpv6_leases.php for which this PR suggests a solution:**
- Insecure handling of the order argument
- Use of strmp() instead of ipcmp() for sorting by ip
- Impossible to effectively sort by any field due to lack of the corresponding UI
**Other:**
This PR is a part of changes proposed by [#4514](https://github.com/opnsense/core/pull/4514).

DHCPv6 leases status: Fix sorting

---

src/etc/inc/plugins.inc.d/unbound.inc

Domain overrides for reverse lookup zones add a typetransparent local-zone to unbound.conf. This allows forwarding of reverse lookups of private IP addresses which would otherwise be blocked by ~~DNS rebinding prevention~~ unbound's default AS112 zones.
These entries were only created for IPv4 reverse lookup zones (.in-addr.arpa.), but not for IPv6 reverse lookup zones (.ip6.arpa.).
Closes #4787.

Unbound: fix domain overrides for private address reverse lookup zones

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt

Hi!
addresses the https://forum.opnsense.org/index.php?topic=23309.msg110930#msg110930 issue (also mentioned on https://github.com/opnsense/core/issues/4988#issuecomment-850878852)
-templates and records controls are collected in one div (so template controls were not split)
-add more space for filters table
-the filter value field is slightly narrowed so that the filters table does not get out of the div when the screen width decreases

fw_log.volt: prevent controls overlap

---

src/opnsense/scripts/filter/read_log.py

Hi!
replaces https://github.com/opnsense/core/pull/5073
just empty label for obsolete rule
no erroneous movement of 'elif' statement
thanks!

read_log.py: set label for obsolete rule in log

---

src/opnsense/mvc/app/library/OPNsense/Auth/LDAP.php

The OpenLDAP setup we use does not return functional attributes by default. I understand this behaviour is quite common. One has to query for memberOf separately. So to enable allocating users to groups, I have added an extra ldap_read() that adds memberOf attributes to the lastAuthProperties array. 
This is relevant to issue #4454.

Enable group sync for LDAP servers, that do not return memberOf

---

src/etc/inc/plugins.inc.d/openvpn/wizard.inc
src/www/vpn_openvpn_server.php

Hi!
clear (i hope) version of https://github.com/opnsense/core/pull/5108/
-no more `isset()`
-still check that 'tunnelnet' not empty (`openvpn_validate_cidr` allows empty field) https://github.com/opnsense/core/pull/5108/files#r674182409
-removed the extra space from previous commit in wizard

openvpn: check ipv4 tunnel prefix. v2

---

src/opnsense/scripts/suricata/lib/rulecache.py

Hi!
again strange metadata in the ptresearch ruleset
`metadata: autosign, id_0,;`
ref: https://github.com/ptresearch/AttackDetection/blob/9bb547bd8411e2398ea6d4972af979d1ee64504e/Telegram/telegram.rules#L2
so mdtag[2] leads to 'index out of range' error for `record['metadata'][parts[0]]`
can we add one more check please?
thanks!

rulecache.py: skip empty metadata

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
src/opnsense/service/templates/OPNsense/Proxy/squid.conf

memory_cache_mode: 	Controls which objects to keep in the memory cache (cache_mem)
default = always. If always is set, value will not saved to config.
Maximum object size in memory: Objects greater than this size will not be attempted to kept in the memory cache. This should be set high enough to keep objects accessed frequently in memory to improve performance whilst low enough to keep larger objects from hoarding cache_mem.
default = 512KB. If value not set default applies.
Only visible with advanced config. Help text formated and adapted form squid documentation.

Adding additional memory cache options for squid webproxy

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/opnsense/site-python/watchers/dhcpd.py
src/www/services_dhcp_edit.php
src/www/services_dhcpv6_edit.php

When a DHCP static entry is created with a hostname but no IP address, Unbound DNS is not update when an IP address from the DHCP pool is assigned to the client.
As discussed in #2946 the issue is that the hostname reported in the `client-hostname` field in dhcpd.leases is the hostname reported by the client.  This change adds the configured hostname to a _set_ variable, `hostname-override`, that gets recorded in dhcpd.leases, then use this value if preset to update the DNS server record.
This only works with the Unbound DNS server, but it could be extended to work with dnsmasq by updating sbin/dhcpleases to parse `hostname-override`

DHCP: Update DNS with hostname only static entries

---

src/etc/inc/console.inc

This PR adds support for LAGG configuration on initial setup and via console.
It helps a lot when dropping a new install into an existing environment that already has LAGGs configured downstream. Would no longer require a temporary config just to access the web interface to then create the LAGGs and VLANs.

Add LAGG support to console

---

src/opnsense/scripts/filter/lib/alias.py

A name like '.example.com' is not a valid name, but should be handled like a non existant name instead of throwing an exception
I was testing using the list from (https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/youtubeparsed) to attempt to block youtube, but the list would never load.  The first entry is '.youtubeeducation.com', which presumably pihole can deal with but it was causing the following error:
```
Dec 30 13:22:04 OPNsense /update_tables.py: fetch alias url https://raw.githubusercontent.com/nickspaargaren/no-google/master/cat
egories/youtubeparsed (lines: 1823) 
Dec 30 13:22:04 OPNsense /update_tables.py: error fetching alias url https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/youtubeparsed 
```

Allow DNS resolver to skip entry on EmptyLabel

---

src/man/man8/opnsense-beep.8

Blindly copied the path, added my own musical score and wondering why it doesn't work.

Correct the melody database directory in manpage

---

src/www/vpn_openvpn_server.php

Hi!
somehow I didn't take this into account in the https://github.com/opnsense/core/pull/5108
p2p configs allows /30 prefix
may close https://github.com/opnsense/core/issues/5212
thanks!

openvpn: allow /30 prefix for p2p

---

src/www/diag_testport.php

Hi!
if "Show Remote Text" (no `-z` flag) set and there is no text to display, `nc` may not output the result at all.
can we add `-v` option to display the connection result in this case?
thanks!

diag_testport.php: set verbose

---

src/opnsense/service/configd_ctl.py

Hi!
can we discuss `configd_ctl.py` behavior when a pipe breaks? (ref. https://forum.opnsense.org/index.php?topic=24868.0) ?
afaik `readline()` not catching EOFError and just returns empty string. maybe it is worth adding a check for such a condition?
and could you please explain why the `list` is used if only one line is read?
thanks!!

configd_ctl.py: catch broken pipe on event handler

---

src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml

The `Link` event for alert settings was missing.
See #5147

monit: add Link event to alert settings

---

src/opnsense/service/templates/OPNsense/Syslog/syslog-ng.conf.in

Hi!
add trailing new line after each file included so as not to control its presence in each inclusion
ref: https://github.com/opnsense/plugins/issues/2587#issuecomment-954873093
(example: `001-local.conf` does not contain trailing new line. so next file will be appended to the last line from it)
thanks!

syslog-ng: add empty line to template

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/www/vpn_ipsec_phase1.php

Hi folks,
another minor enhancement to the IPsec options. Some legacy devices like Forcepoint Sidewinder incorrectly implement HMAC_SHA256 for phase 2.
With the same reasoning as for the "closeaction" parameter I added the field to the phase 1 form, because it applies to all phase 2 entries of a particular peer or not at all.
In general style I followed @AdSchellevis implementation of the "closeaction".
Kind regards,
Patrick

VPN / IPsec / Advanced settings - add sha256_96 flag

---

src/etc/inc/system.inc

Hi!
sorry, it looks like we missed one point when we discussed excluding intermediate certificates from the store
authorityKeyIdentifier extension may  have several params
https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.1
if the root CA's certificate extension contains them, then the condition will not be met and the certificate will not be flushed to the store
ref. https://forum.opnsense.org/index.php?topic=25361.0
thanks!

System / Trust / Authorities get authority keyid from authorityKeyIdentifier extension

---

src/www/status_dhcp_leases.php

Added `ipaddr` parameter to prefill the static IP address field when creating a static DHCP lease.

Pass current IP address to static DHCP lease creation

---

src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
src/opnsense/scripts/OPNsense/CaptivePortal/htdocs_default/index.html
src/www/diag_authentication.php
src/www/diag_backup.php
src/www/firewall_virtual_ip_edit.php
src/www/head.inc
src/www/interfaces.php
src/www/interfaces_ppps_edit.php
src/www/services_opendns.php
src/www/system_authservers.php
src/www/system_certmanager.php
src/www/system_hasync.php
src/www/system_usermanager.php
src/www/system_usermanager_passwordmg.php
src/www/vpn_openvpn_client.php

Prevent browser from auto filling certain username/password fields with the system login credentials in new forms or if left blank.
* Don't globally override existing autocomplete attribute on input elements.
* Apply the attribute autocomplete="new-password" to password input elements.
Examples:
System:
Access:
User +
Servers +
Tester
Configuration:
Backups - Google Drive
High Availability:
Settings
Interfaces:
Point-to-point:
Devices +
VPN:
OpenVPN:
Clients +
Services:
Dynamic DNS +
OpenDNS
See also corresponding commit in plugins for DynDNS.

Prevent Browser Auto Fill Username/Password

---

src/opnsense/scripts/filter/lib/states.py

Hi
it seems that the `states.py` script does not take into account the change in the position of the src and dst addresses depending on the state direction. its clearly visible on a broadcast network. the current behavior can lead to something like (clients applications is searching for sentinel hasp servers):
root@OPN:~ # pfctl -ss | grep .255
```
all udp 172.17.1.255:1947 <- 172.17.1.47:52339       NO_TRAFFIC:SINGLE
all udp 255.255.255.255:1947 <- 172.17.1.65:54326       NO_TRAFFIC:SINGLE
all udp 172.17.1.255:1947 <- 172.17.1.218:63477       NO_TRAFFIC:SINGLE
all udp 239.255.255.250:1900 <- 172.17.1.234:49970       NO_TRAFFIC:SINGLE
all udp 239.255.255.250:1900 <- 172.17.1.215:50739       NO_TRAFFIC:SINGLE
all udp 255.255.255.255:1947 <- 172.17.1.236:60800       NO_TRAFFIC:SINGLE
all …
```

Diagnostics / States: switch dst-src with direction

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_pftop.volt

Hi!
I apologize, did not notice earlier and did not add to the previous pr :worried: .
looks like a typo on the pf_top page. as a result, all sessions are marked as incoming (api returns direction as a `dir`. formatter uses `column.id` to get value ).
thanks!

Firewall / Diagnostics / Sessions - typo

---

src/opnsense/scripts/suricata/rule-updater.py

Hi!
since syslog-ng grabs only `level(notice..emerg)` for system log maybe it is worth changing the severity level so that messages about skipped downloads go to the log?
thanks!

IDPS rule-updater: change syslog severity level

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/LogController.php
src/opnsense/mvc/app/views/OPNsense/Diagnostics/log.volt
src/opnsense/scripts/systemhealth/queryLog.py

Hi!
just for possible discussion of  https://github.com/opnsense/core/issues/5337#issuecomment-974886511
Clarifications: Under certain circumstances, some processes and services can create quite a lot of noise in the logs. This is great for debugging, but can be annoying for the administrator during normal operation.
Initial idea: since the OPNSense finally completely switches to syslog-ng, RFC5424 support has been added, and even a severity filter has already been added (!  :thumbsup:), it may be worth considering to make the default log representation of the "warning logs" type (do not show by default lines reflecting normal behavior)?
Details: pr by default displays the logs filtered with "Warning" severity (UPD. badly put it: filtered with a level **below or equal to** "Warning"), the …

Logs: quick severity filter with "Warning" default

---

src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php

Update `formatBytes()` to support terabytes. 
* Add support for terabyte sizes, used in calculating update sizes
I am not aware of a clean way to test this, so I just overrode the values of `$active_count = 1;` and `$active_size = 723918942673774;` to force the API to return the message.
Looks like:
Other sizes tested:
```
| Tested Value      | output size |
| ----------------  | ----------- |
| 42705383466540728 |     37.9PiB |
| 1125899906842624  |      1.0PiB |
| 723918942673774   |    658.4TiB |
| 58274116272128    |     53.0TiB |
| 1099511627776     |      1.0TiB |
| 72391673774       |     67.4GiB |
| 1073741824        |      1.0GiB |
| 37633392          |     35.9MiB |
| 1048576           |      1.0MiB |
| 1024              |      1.0KiB |
| 424               |        424B |
| 0 …
```

firmware/status: Update to support terabytes

---

src/etc/inc/util.inc

This just expands the supported range of the formatting to support tera-, and petabytes.
It utilizes the same method as megabytes, and gigabytes, only adding an extra 1024 for the larger sizes.
* This formatted number is used by the Interface Statistics widget,
and makes the columns go wider than necessary when going above a
terabyte of data. Add petabytes for good measure.

util: add support for terabytes, and petabytes to format_bytes

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
src/opnsense/scripts/filter/read_log.py

Hi!
For "live view" part of  https://github.com/opnsense/core/issues/5412
-dont check rule number in `running_conf_descr` for nat/rdr rules
-dont show rule lookup link if `rid`  is not rid
thanks!

Firewall/Live View: dont search rid for nat

---

src/opnsense/www/js/opnsense.js

Hi!
noticed when checking the observers performance
I hope not missing anything, if we are looking for element `id` in `validationErrors`, maybe it makes sense to limit `find` only to elements with `id`? (this gave me about 0.4s when loading forms with a lot of elements, like Aliases forms)
Thanks!

GUI: speedup forms load a bit

---

src/www/services_dnsmasq.php

This looks like a copy & paste error, retaining the "data-for" from the previous empty.

fix domain_needed and no_private_reverse help tooltip

---

src/etc/inc/plugins.inc.d/dnsmasq.inc

Currently, when configured, "strict-order" adds the necessary "strict-order" argument. However, the hardcoded "all-servers" argument overrides this, making "strict-order" pointless.
With this change, "all-servers" and "strict-order" are mutually exclusive.

fix dnsmasq strict-order

---

src/www/firewall_scrub.php

This PR is a quick fix of an issue on the Firewall/Setting/Normalization page. The page shows interface names (e.g. opt1) in the Interfaces column of the Detailed settings table, while the corresponding editing page shows interface descriptions. I suggest we convert interface names to descriptions using the approach taken from firewall_scrub_edit.php.

Firewall/Scrub: Display interface descriptions

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/InterfaceController.php
src/opnsense/scripts/routes/gateway_status.php

**Problem:**
I needed a way to get the currently assigned IP address for a PPPoE interface through API.
At the moment, if you use this command:
```bash
$ curl -sku "${OPNKEY}:${OPNSEC}" https://${OPNSENSE_ADDRESS}/api/routes/gateway/status | jq
```
You get:
```json
{
"items": [
{
"name": "WAN_PPPOE",
"address": "x.x.x.x",
"status": "none",
"loss": "0.0 %",
"delay": "9.1 ms",
"stddev": "1.9 ms",
"status_translated": "Online"
},
{
"name": "WANLTE_GWv4",
"address": "y.y.y.y",
"status": "down",
"loss": "100.0 %",
"delay": "0.0 ms",
"stddev": "0.0 ms",
"status_translated": "Offline"
}
],
"status": "ok"
}
```
The ip address indicated in the "address" field is the monitored IP address of the gateway.
I found no other suitable API calls to get the currently assigned IP address of an interface, so …

show interface IP address in API

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/log.volt
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/mvc/app/views/OPNsense/IDS/index.volt
src/opnsense/www/js/jquery.bootgrid.js
src/opnsense/www/js/opnsense_bootgrid_plugin.js

Implementation of #5439 to store settings of bootgrids (sort order, visible columns, row count) in local browser storage.
- Update of jquery.bootgrid.js from 1.3.5 to 1.4.0 (opnsense/jquery-bootgrid#5)
- Removing of equivalent functionality from opnsense_bootgrid_plugin.js

Move storing jQuery Bootgrid settings in browser from core to bootgrid

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/ModelRelationField.php
src/opnsense/mvc/tests/app/models/OPNsense/Base/FieldTypes/ModelRelationFieldTest.php

I came across this in my exploration, and thought it was weird that this field didn't support the BlankDesc option with it building a very similar thing to what OptionFields do. I tried it out and it seems to work the same way as OptionFields' BlankDesc. Needs an expert eye though. I just copied the same structures over from the `BaseListField` type and change the code to use the `internalEmptyDescription` instead of the hard coded `none`.
* Add BlankDesc options for ModelRelationField types.
* Copied from BaseListField type.

mvc: Add BlankDesc to ModelRelationField

---

src/etc/rc.syshook.d/carp/20-ppp

The `interface_ppps_configure` only takes one argument.

Fix CARP PPP hook.

---

src/etc/inc/authgui.inc

in_array() is case sensitive; host and domain names are not.

DNS Rebind Check Case Sensitivity

---

src/etc/inc/plugins.inc.d/dnsmasq.inc
src/www/services_dnsmasq.php

Attempting to link this to the issue: closes #5374
* Add checkbox to enable --no-hosts command line option

dnsmasq: no hosts option; closes #5374

---

src/opnsense/mvc/app/library/OPNsense/Core/Backend.php

Hi!
ref. https://github.com/opnsense/core/issues/5382
it seems that error messages from the `configdRun()` function (https://github.com/opnsense/core/blob/b6ffe6fa17b8ec7838128027b9955697330bacab/src/opnsense/mvc/app/library/OPNsense/Core/Backend.php#L81) do not get into the `syslog-ng` backend log.
changes worked for me:
- `$ident = 'configd.py'` for `f_local_configd` syslog-ng filter matching
- remove `[%date%][%type%] ` from default phalcon message format to avoid duplication in log line
thanks!

Backend.php: syslog-ng migration

---

src/etc/inc/plugins.inc.d/openssh.inc
src/opnsense/scripts/openssh/ssh_query.py
src/www/system_advanced_admin.php

As OpenSSH 8.8 disables RSA signatures using the SHA-1 hash algorithm
by default some older SSH clients might not be able to connect to
OPNsense anymore. Therefore, it might be needed to manually modify the
PubkeyAucceptedAlgorithms sshd config option.

Allow to configure SSH setting PubkeyAcceptedAlgorithms via GUI

---

src/etc/inc/authgui.inc
src/etc/inc/util.inc

Hi!
I hope I didn't miss anything and now we can take advantage of using severity levels?
starting with GUI authentication logging )
Thanks!

util: use severity levels

---

src/etc/inc/authgui.inc
src/etc/inc/util.inc

Hi!
in https://github.com/opnsense/core/pull/5497 continuation
don't obfuscate `log_error`, add `log_msg()`
will try to traverse `log_error` calls and move to `log_msg`  where appropriate in next pr
thanks!

util/log_error: keep it clear. add a log_msg

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php

Hi!
Accidentally stumbled while playing with the pf table counters issue.
Since html special chars are allowed in the rules descriptons returning plain `sprintf` may lead to possible XSS vul. imho.
example:
Choose any pf rule using aliases, change rule descripton to `<img src=& onerror=alert("XSS")>`, try to delete Alias associated with this rule
thanks!

Firewall: Aliases - encode rule name in response

---

src/opnsense/scripts/systemhealth/queryLog.py

Hi.
For logs part of https://github.com/opnsense/plugins/issues/2776 and may close https://github.com/opnsense/plugins/issues/2786
set initial `severity` val to `None `and just add lines with missing severity (not set by parser or not in log) to the output. no fake prio - just empty field
Thanks!

Logs: add backward compatibility

---

src/www/firewall_nat.php
src/www/firewall_nat_1to1.php
src/www/firewall_nat_npt.php
src/www/firewall_nat_out.php
src/www/firewall_rules.php

Hi!
`hook_firewall_categories()` function tries to prevent accidental rules mass actions by disabling `".rule_select"` checkboxes for filtered-out rules. But `prop()` not taking this in to account.
Thanks!

Firewall: Categories - do not select filtered-out rules

---

src/etc/inc/plugins.inc.d/dhcpd.inc

According to https://www.php.net/manual/en/function.implode.php and PHP warning since 7.4.0:
Exception: Error at /usr/local/etc/inc/plugins.inc.d/dhcpd.inc:2012 - implode(): Passing glue string after array is deprecated. Swap the parameters (errno=8192) in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ApiControllerBase.php:96

Fix implode() call

---

src/etc/inc/interfaces.inc
src/opnsense/mvc/app/controllers/OPNsense/Interfaces/Api/VlanSettingsController.php
src/opnsense/mvc/app/models/OPNsense/Interfaces/FieldTypes/VlanInterfaceField.php

Since FreeBSD 13 its possible to stack vlans on top of vlans (IEEE 802.1ad), although in the past it should have been possible to build a QinQ using netgraph, it didn't work reliable forcing us to remove it back in 2018 (https://github.com/opnsense/core/issues/2274).
Given the new functionality it seems like a good idea to give this another try as the interface is much cleaner now.
Implements https://github.com/opnsense/core/issues/5560

Interfaces: Other Types: VLAN - Add stacked VLAN support (IEEE 802.1ad / QinQ)

---

plist
src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/DotController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/ForwardController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogDot.xml
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/forwarding.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Migrations/M1_0_2.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/mvc/app/views/OPNsense/Unbound/dot.volt
src/opnsense/scripts/system/nameservers.php
src/opnsense/service/conf/actions.d/actions_system.conf
src/opnsense/service/templates/OPNsense/Unbound/core/dot.conf
src/www/services_unbound.php

resolves https://github.com/opnsense/core/issues/5138
This PR pulls query forwarding over the current dot setup, so visually nothing changes.
All API calls are redirected to new Forward functions, which slightly modifies what is returned based on whether "Query Forwarding" or "DNS over TLS" is selected from the menu. This way backwards compatibility is preserved.
As an addition, a user is now able to specify a specific domain for a forward zone as well. Meaning that queries for this specific domain will skip a catch-all (".") domain (if specified), and instead use the server specified for this domain.
Entering a forward zone with a catch-all domain (".") in both Query Forwading and DNS over TLS is considered a duplicate by Unbound, so a static warning for this has been attached in the …

unbound: implement custom forwarders over current dot setup

---

src/opnsense/mvc/app/library/OPNsense/Backup/Base.php

https://www.openssl.org/docs/man1.1.1/man1/openssl.html
```
pass:password
The actual password is password. Since the password is visible to utilities (like 'ps' under
Unix) this form should only be used where security is not important.
```
Another issue was that secure temporary files were created, but never used or deleted.
```php
$file = tempnam(sys_get_temp_dir(), 'php-encrypt');
```
The files actually used were just created insecurely by writing to a known file after the creation of the previously mentioned `$file`.
```php
file_put_contents("{$file}.dec", $data);
```

Don't leak backup password to `ps`

---

src/etc/inc/legacy_bindings.inc
src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php
src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php
src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.xml
src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasField.php
src/opnsense/mvc/app/models/OPNsense/Firewall/static_aliases/core.json
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/scripts/filter/lib/alias.py
src/opnsense/scripts/filter/update_tables.py
src/opnsense/service/templates/OPNsense/Filter/filter_tables.conf

This PR contains various improvements to the alias subsystem. 
o change /api/firewall/alias/listNetworkAliases endpoint to return name and address
o add alias description as subtext in network group dropdown
o exclude row buttons for internal aliases
o support nesting of external aliases
o attach statistics to external aliases (like bogons and new interface network types)
o add preprocess in alias to handle non gui defined types
o network aliases will flush :network into the table
o aliases which aren't managed via configured settings will be fetched for nesting
o gather pf tables which aren't generated into filter_tables.conf as being external so the new imported static_aliases are usable without the need to import the settings in the template language
o initial work to support interface …

Firewall / Aliases - various usability and visibility improvements

---

src/etc/inc/plugins.inc.d/unbound.inc
src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/forwarding.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Migrations/M1_0_2.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/mvc/app/views/OPNsense/Unbound/dot.volt
src/wizard/system.xml

Migrating to MVC means we can use the existing get/set API calls without having to manually manipulate the legacy configuration.
This PR also adds a migration for the legacy unbound->forwarding configuration.
I'm not sure what the original intent behind https://github.com/opnsense/core/blob/master/src/wizard/system.xml#L158-L159 was, but i'm removing it here.

unbound: clean up references to legacy code, use mvc instead. also minor style fix

---

src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundDomainField.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml

Closes #5697 
The original implementation was also pretty buggy, validation now makes sure a '.' dot is used to prefix the subdomain coming after it. In fact, legacy allowed just "_msdcs", contradicting the validation message.

Unbound / Domain overrides: accept _msdcs since legacy supported it.

---

src/opnsense/mvc/app/models/OPNsense/Unbound/FieldTypes/UnboundServerField.php
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml

Current implementation is correct, but looks like this if the IP field is left empty:

Unbound overrides: fix validation message style issue

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php

Unbound host and domain sort order.
Host and domain names are case insensitive.  Should be handled case insensitively.  myHost comes before YourHost.  Always.
Sort order should be:
myHost
YourHost
Not:
YourHost
myHost

unbound: overrides: mvc: case sort order

---

src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml

Wildcard functionality of HostnameField was refactored
See f110c988d4c5722308d0ec7a4ef5b86c0b3f767c

Unbound overrides: fix handling of wildcard aliases

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/ServiceController.php
src/opnsense/mvc/app/views/OPNsense/Unbound/dnsbl.volt
src/opnsense/scripts/unbound/blocklists.py
src/opnsense/scripts/unbound/wrapper.py
src/opnsense/service/conf/actions.d/actions_unbound.conf

This PR contains an optimization for the way unbound can be updated in its' configuration
without the need for restarting Unbound and by extension a loss of internet connectivity.
Hopefully this will pave the way for optimizations on other aspects of Unbounds' configuration as well.
We could for example look into making the provided wrapper function more generic.
The GUI has also been modified slightly to inform the user of the amount of RRs added/removed.

unbound: make blocklist additions/removals dynamic to prevent a restart

---

src/opnsense/mvc/app/views/OPNsense/Core/firmware.volt

Even though the server responds with proper cache headers to avoid
browser caching, it seems that Safari (and maybe others) may still cache
repeated calls to `/api/core/firmware/upgradestatus`. This change adds
in the time-old tradition of appending the current timestamp in
milliseconds to each request which should force the browser to fetch the
resource.
Ref: https://www.reddit.com/r/opnsense/comments/umhx04/opnsense_2217_released/i83bp36/?context=5

Bypass cache with timestamp in upgradestatus call

---

src/etc/inc/certs.inc
src/www/system_certmanager.php
src/www/system_crlmanager.php

Since php-openssl still has no implementation for CRLs, phpseclib is now used to provide these.
To test this PR:
- Create a CA
- Create a certificate signed by the CA
- Create a CRL and revoke the above certificate
- Run `openssl verify -crl_check_all -CRLfile <crl>.crl -CAfile <ca>.crt <certificate>.crt`
Output:
```
error 23 at 0 depth lookup: certificate revoked
error testcertificate.crt: verification failed
```
`$crl['method']` was accessed in multiple places as well - this is a bug, fix included here.
Improved error handling is skipped here to prevent unnecessary regressions.
Fixes https://github.com/opnsense/core/issues/5675

PHP80: CRL support

---

src/opnsense/mvc/app/views/OPNsense/Unbound/stats.volt

This pull request updates the zero_ttl stat in the unbound page to the expired page, and also enhances the statistics to include request queue stats (included in default stats) and some opinionated sorting of the output to include "Total" and "Times" at the top. (Fixes #5792)

Fix for Unbound Stats: zero_ttl is no longer a valid statistic

---

src/opnsense/www/js/opnsense_bootgrid_plugin.js

* command-info uses this.command_info method, which expects
params['info'] to be populated, not 'get'.
I stumbled across this issue ticket and saw that this wasn't addressed yet. I looked into it and I think it should be changed to info, as the method does use 'info', and not the 'get' param. If 'info' is not provided, the method still executes without error, but ends up with a literal `undefined` as the URL in the ajaxGet call. Which gets caught by the API error handler as action not found.
https://github.com/opnsense/core/blob/91b840d5d2ae0d274c3b7b105d2a76bef2209598/src/opnsense/www/js/opnsense_bootgrid_plugin.js#L333-L347
I expect anyone that's using `commandsWithInfo` data-formatter will have an info URL defined, since the button won't do anything without it.

ui: bootgrid, correct required api for command-info #5478

---

src/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php

* Return a useful message to the UI if no mount is found in the model XML.
Otherwise this condition results in a SimpleXMLElement error, trying to
parse an empty string in toXml(), `$xml = new SimpleXMLElement($xml_root_node);`
I followed the pattern of error handling of the two throws above it. I'm not sure about the message, but it should be clear enough.
Message looks like:
```
/usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:323: model xml /usr/local/opnsense/mvc/app/models/OPNsense/Myplugin/Settings.xml missing mount definition
```

MVC - model: throw when no mount found

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/TunnelController.php
src/www/vpn_ipsec_phase1.php

**Issue:**
- You need to configure separate IPv4 and IPv6 phase1 entries for a dual stack mobile setup on each interface, i.e. 2 phase1 entries and 4 phase2 entries for each interface. If you have more than 1 authentication options (e.g. Mutual RSA, EAP-MSCHAPv2, etc.), the number of phase1 entries grows proportionally. It is even more inefficient when/if you need to make a small change - you have to repeat the change multiple times to each phase1 entry.
**Solution:**
- Strongswan provides for multiple IPs separated by commas as left/right side addresses in the ipsec.conf. Thus, we can implement an IPv4+6 protocol option (in addition to the existing IPv4 and IPv6 ones) that halves the number of phase1/phase2 entries required for a dual stack mobile setup. 
**Further ideas:**
- We might …

VPN / IPsec / Tunnel Settings: Add IPv4+6 protocol for mobile phase1 entries

---

src/www/widgets/widgets/log.widget.php

Reduce line wrap:
Remove "Dest " from the destination port header.  Provides little value at the expense of increase line wrap.  In this context and column position (to right of destination address) it is obvious to be the destination port.  Source port in this context and column position would make no sense.

Firewall Log Widget Header Tweak

---

src/etc/inc/interfaces.inc
src/www/interfaces.php

- Add WPA Enterprise configuration options using EAP with TLS, TTLS and PEAP
- New _identity_ property
- _WPA passphrase_ reworded to _WPA passphrase/EAP password_
- Select EAP mode: TLS/TTLS/PEAP
- Select _phase 2 algorithm_: MD5/MSCHAPv2
- Allow configuration of CA to verify authenticity of authentication server
- Allow configuration of certificate and private key for TLS/PEAP authentication
- As the wireless interface configuration page is quite overwhelming with all the available options, only relevant settings should be shown. Irrelevant settings are being hidden:
- Show WPA/WEP/EAP settings only when WPA/WEP/EAP is enabled
- Show IEEE 802.1X settings only when relevant
- Hide AP-only/Adhoc-only settings when infrastructure mode is selected
- Hide infrastucture-only settings when …

Wireless: Add WPA Enterprise Configuration for Infrastructure Mode

---

src/www/widgets/widgets/system_log.widget.php

Hi!
Can we discuss adding a filter to the widget?
Answering the question posed earlier: yes, it seems to me that being able to save the filter in config might add a bit of convenience. Life scenario: user can setup the monit to monitor events\logs important to him, just save the filter with the "monit" value and always see a filtered log in lobby
and can you please explain why using cookies to pass validation results is not a good idea in this case?
by the way I can try to do this by changing the form submit behavior if it is more correct )
thanks!

system log widget: add filter

---

src/opnsense/www/js/opnsense_bootgrid_plugin.js

* Exclude if array, primarily for rowCount
I found that this condition was also picking up rowCount as an object, it would then convert it to an object which breaks a couple of things down the line, which I noticed with LogController, and jquery.bootgrid.js.
This should be visible by going to System -> Log Files -> General (or any other log page that uses LogController).
An API exception appears reporting `/usr/local/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/LogController.php:76: Unsupported operand types`
This is due to `$itemsPerPage` being an array instead of an integer.
Also the row selector doesn't appear, which is normally between the refresh button, and column selector.
I think these issues stem from jquery.bootgrid.js doing unexpected things since it's expecting an …

MVC - bootgrid - regression from 79f5d8f

---

src/www/services_opendns.php

https://github.com/opnsense/core/issues/5845
The OpenDNS plugin uses array('2620:0:ccc::2', '2620:0:ccd::2') but should be using:
array('2620:119:35::35', '2620:119:53::53') according to https://www.opendns.com/about/innovations/ipv6/
I have tried with the changed settings and verified that it works whereas it did not with existing addresses.

Update OpenDNS ipv6 servers

---

src/opnsense/service/modules/processhandler.py

* except when an Exception occurs reading a config file
This intends to mitigate an issue that I encountered through a mistake that I made copy/pasting actions for a plugin where I ended up with two sections in the conf file with the same name.
This duplicate name situation appears to stall configd, and it doesn't open the socket to interact with it. Attempts to `configctl` result in only a message:
```
configd socket missing (@/var/run/configd.socket)
```
However, the configd service is running according to the status:
```
configd is running as pid 92539.
```
No error is presented when starting the service at the command line.
A log message is recorded in `/var/log/configd/latest.log` though:
```
<11>1 2022-06-28T17:50:40-04:00 OPNsense.localdomain configd.py 62084 - [meta …
```

configd - except configparser read

---

src/opnsense/mvc/app/models/OPNsense/Base/Validators/IntegerValidator.php

Fixes validation for valid negative integers
Uses FILTER_VALIDATE_INT which should cover all the cases including min/max int value

fix IntegerValidator returning false for negative numbers

---

src/opnsense/www/js/opnsense_ui.js

* Add condition for data existing before others
catches Uncaught TypeError: data.status is undefined
I encountered this when I was using SimpleActionButton with a custom API that doesn't have 'status' in the response.
Adding a condition that requires `status` key existing in `data` appears to mitigate the error. I assume that it doesn't evaluate the rest of the conditions with this one failing. Since `data['status']` is used later on, this will require that it exists first.

MVC: SimpleActionButton, add catch undefined TypeError

---

src/etc/inc/plugins.inc.d/loopback.inc

This fixes a bug:
* Loopback interfaces other than the one being configured/created
are all going to be removed/destroyed.

interfaces: Fix unable to bring up multiple loopback

---

src/etc/inc/interfaces.inc

When setting up an IPv4-over-IPv6 or IPv4-over-IPv4 gif tunnel, IPv6 should be disabled inside the tunnel to prevent the automatic configuration of an IPv6 link-local address. From man gif(4):
> Note that IPv6 link-local addresses (those that start with fe80::) will be automatically configured whenever possible. You may need to remove IPv6 link-local addresses manually	using ifconfig(8), if you want to disable the use of IPv6 as the inner header (for example, if you need a pure IPv4-over-IPv6 tunnel).

Disable IPv6 inside 4in6 and 4in4 gif tunnels

---

src/opnsense/mvc/app/controllers/OPNsense/Core/Api/SystemController.php
src/opnsense/mvc/app/library/OPNsense/System/AbstractStatus.php
src/opnsense/mvc/app/library/OPNsense/System/Status/CrashReporterStatus.php
src/opnsense/mvc/app/library/OPNsense/System/Status/FirewallStatus.php
src/opnsense/mvc/app/library/OPNsense/System/SystemStatus.php
src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/www/js/opnsense_status.js
src/www/fbegin.inc
src/www/head.inc

o Switch to shared circle with coloring (no visual jumping)
o Switch SUCCESS circle to muted (muted keeps us calm)
o Switch dialog color to primary (keep one consistent "neutral" layout)
o Switch dialog close button to plain (it doesn't do anything)
o Add translation in legacy template (because that's nice)
o Add muted circle to page load (to avoid shifts and jumps)
o Check error level for crash report in production (probably better as warning)
o Rearrange dismiss and error presentation, inline "circle" indicator (perhaps)
Behavioural changes thought of but discarded:
o ~~Open error dialog right away~~ (it implies action to be taken but might be annoying especially if the reporting page is already open)
o ~~Dismiss on redirect also?~~ (can't do this, clears crash report)

system: change UX for new notices

---

src/etc/inc/interfaces.inc

There was some dormant code to request DNS servers + search list via stateless DHCPv6, but this was not actually merged into dhcp6c.conf. Also, there was no code to process stateless DHCPv6 replies in the dhcp6c script. Context: [#5862](https://github.com/opnsense/core/issues/5862#issuecomment-1207473812)

SLAAC WAN: add support for requesting DNS info via stateless DHCPv6

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound.php

Adds on option which removes all A records from the answer section of all responses. Closes #5944.

Unbound / DNS64: add AAAA-only mode

---

src/etc/inc/plugins.inc.d/dhcpd.inc

Allow the DHCPv6 two-message exchange for clients which don't support the four-message exchange. Closes #5947.

dhcpd6: allow rapid-commit message exchange

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_unbound.php

In order to prevent unpredictable behaviour from something that is not explicitly prohibited in RFC1035, it is best to restrict the creation of PTR records from every single host and alias (except for wildcard entries, no PTR records are created here), to only non-alias overrides (edit: the exception here is an alias whose parent does not create a PTR record). We also further restrict it to unique IP addresses so there can be no confusion in how to maintain the entries within the running Unbound instance.
Hopefully this can pave the way for adding PTR records as a separate type instead of generating them under the hood, as is done currently.
This change should at least address inconsistencies regarding random PTR records being returned as mentioned in …

unbound: restrict creation of PTR records for both the system domain and host overrides

---

src/etc/inc/certs.inc
src/www/system_crlmanager.php

Hi!
ref. https://forum.opnsense.org/index.php?topic=29567.0
it turned out that phpseclib2.0 does not support some algos and does not throw exceptions on errors (hope that with phpseclib3.0 it will be possible to do everything more correctly).
https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md#300---2020-12-16
https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md#303---2021-01-16
PR:
add some debug info
dont add cert to crl if cert_revoke() / crl_update() failed
check if CA can sign anything before CRL create
set "method" param to set Method select value
Thanks!

CRL management small adjustments

---

src/etc/inc/auth.inc

Allow accessing Web GUI via link-local IPv6 addresses by ignoring %scope suffix when performing HTTP_REFERER check.
Closes #5971.

Web GUI: fix IPv6 link-local HTTP_REFERER check

---

src/www/system_crlmanager.php

Hi!
ref. https://forum.opnsense.org/index.php?topic=29937.0
Turned out that administrator may accidentally break the **imported** CRL by clicking Save when viewing crl data: `CRL data` field shows encoded string.
Thanks!

CRL: decode stored crl data before display

---

src/etc/inc/certs.inc

Requires https://github.com/opnsense/ports/pull/159
Closes https://github.com/opnsense/core/issues/5977
Includes EC support:
```
[tbsCertList] => Array
(
[version] => v2
[signature] => Array
(
[algorithm] => ecdsa-with-SHA256
)
```

certs: add support for phpseclib3

---

src/www/status_interfaces.php

Having two sets of buttons implies that they only act on the respective protocol, but this is not the case.
https://github.com/opnsense/core/issues/5974#issuecomment-1225222923

Interfaces Overview, merge DHCPv4 / DHCPv6 buttons

---

src/etc/inc/plugins.inc.d/webgui.inc

Hi!
ref. https://forum.opnsense.org/index.php?topic=29284
ref. https://forum.opnsense.org/index.php?topic=30048.0
It turned out that the administrator can break access to the gui by selecting  TLSv1.3 ciphersuites only.
OpenSSL uses different config file options and commands to define ciphersuites for TLS1.2 and below (`CipherString`) and for TLS1.3 suites (`Ciphersuites`): 
https://www.openssl.org/docs/manmaster/man3/SSL_CONF_cmd.html#SUPPORTED-CONFIGURATION-FILE-COMMANDS
PR tries to follow this logic and use matching command for defined ciphers.
RFC8446 Compliance Requirements (https://www.rfc-editor.org/rfc/rfc8446#section-9.1) is also fulfilled when using TLS1.3 suites: the presence of the TLS_AES_128_GCM_SHA256 is controlled.
Thanks!
UPD. RFC8446 Compliance Requirements check …

webgui: match cipher suites and openssl config commands

---

src/www/widgets/include/ipsec.inc

The IPsec widget on dashboard by default links to `diag_ipsec.php`, which doesn't seem to exist anymore and results in:
This quick PR changes the link to `ui/ipsec/sessions`, which is the "Status Overview" page:
Tested the change locally by modifying the file:
```shell
<?php
$ipsec_title = gettext('IPsec');
$ipsec_title_link = 'ui/ipsec/sessions';
```

ipsec: fixed widget link

---

src/opnsense/service/templates/OPNsense/Proxy/squid.conf

Arch Linux moved from `xz` compression to `zst` some time ago: [Now using Zstandard instead of xz for package compression](https://archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/).
The change simply replaces the pattern for the `xz` compressed package names for Arch Linux with the `zst` in the `squid.conf`.

update pattern to zst for the Arch packages

---

src/etc/ssl/opnsense.cnf

Hi!
ref. and hopefully closes https://github.com/opnsense/core/issues/5912
Thanks!

OpenSSL: add keyUsage extension in CA config

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/InterfaceController.php
src/opnsense/mvc/app/views/OPNsense/Diagnostics/arp.volt
src/opnsense/scripts/interfaces/list_arp.py
src/opnsense/service/conf/actions.d/actions_interface.conf

Arp table only relies on dhcp-leases entries to get the hostname. So when using an external DHCP server, or for IP addresses that are not assigned by DHCP, the displayed hostnames are always blank.
Features added:
- if hostame is not found in the dhcp-leases, the hostname is fetched from a DNS PTR query, (using the system's DNS server).
- use_dns variable can allow/disallow this behaviour (useful is someone would like to move this to a system preference)
HTH

ARP Table: hostname uses reverse DNS lookup as fallback

---

src/etc/ssl/opnsense.cnf

Hi!
ref. https://github.com/opnsense/core/pull/6017#issuecomment-1244087369
trying to follow the RFC requirements for `basicConstraints `extension as well
Thanks!)

OpenSSL: follow RFC on basicConstraints too

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_pftop.volt
src/opnsense/scripts/filter/lib/states.py

Hi!
ref. https://github.com/opnsense/core/issues/6008
Turned out that for sessions with large values of Age or Bytes, the `pftop` utility can change the display format of this fields even with a large value of the `-w` parameter. So internal Age value conversion can break  Firewall/Diagnostics/Sessions page display
[print_fld_sdiv(field_def *fld, u_int64_t size, int div)](https://github.com/araujobsd/pftop/blob/ab98de9ce24f0b15da5ab677acb50db187ad1094/engine.c#L661)
[print_fld_age(field_def *fld, unsigned int age)](https://github.com/araujobsd/pftop/blob/ab98de9ce24f0b15da5ab677acb50db187ad1094/engine.c#L607)
PR tries to take this into account and returns the values to a single format.
The value of the multiplier for converting units on the frontend has also been changed to align with the …

Firewall/Diagnostics/Sessions: parse pftop internal data conversion

---

src/www/widgets/widgets/openvpn.widget.php

Hi!
seems to have overlooked a small regression after https://github.com/opnsense/core/commit/405395264ffb4f77e298a3bfa5d670b9a53eeda6 at openvpn widget (script with event binding stripped before execute).
(a little strange that there were no complaints)
thanks!

OpenVPN widget: bring back the buttons action

---

src/opnsense/scripts/unbound/blocklists.py

Hi!
as discussed at https://github.com/opnsense/core/issues/6026#issuecomment-1249704152 [Requests timeout](https://requests.readthedocs.io/en/stable/user/advanced/#timeouts) parameter limits the server response time and time between bytes. So there is no need to wait so long for unresponsive server.
Thanks!

unbound: don't wait blocklist too long

---

src/etc/inc/plugins.inc.d/ipsec.inc

Fix #6022 that will add multiple phase 2 IPs to the same interface when tunnel isolation is disabled.
@AdSchellevis I believe that as $tunnels is not defined anywhere on this function, using $configured_intf it's able to append to the ['networks'] array which configures multiple IPs on the ipsec interface when tunnel isolation is disabled. This will imitate pfsense behavior.

Fix bug in ipsec when tunnel isolation is disabled

---

src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php

Hi!
ref https://forum.opnsense.org/index.php?topic=30368.0
`abs()` "no longer accepts internal objects which support numeric conversion." [(ref)](https://www.php.net/manual/en/function.abs.php)
Thanks!

Fireewall : Aliases - PHP8 error fix

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php

Hi!
ref. https://github.com/opnsense/core/issues/6047
It turned out that the unbound api does not allow adding a simple (non-DoT) forwarder in the usual way (have to emulate the browser behavior by setting the HTTP Referer header value).
PR tries to add the ability to set the forwarder type by explicitly specifying the type in the request.
Thanks!

unbound: allow setting forwarder type via API

---

src/etc/inc/plugins.inc.d/dnsmasq.inc

See: https://data.iana.org/root-anchors/root-anchors.xml

dnsmasq: DNSSEC: Remove expired root trust anchor

---

src/www/system_general.php

* Don't suggest using unreserved top-level domains.
* Use the reserved example.com|net domains for other examples.
* Encourage adoption of the special-purpose internal/site home.arpa (RFC 8375) domain.

Change system domain name suggestions

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogDot.xml

A small option string change that’ll hopefully make it clearer what the setting is for and what to enter.

Unbound: Clarify “Verify CN” option field

---

src/etc/inc/config.inc
src/etc/inc/interfaces.inc
src/etc/inc/util.inc
src/etc/rc.subr.d/var

```
2022-10-19T12:19:27+02:00 interface_configure[316] Configuring OPT3 interface...
2022-10-19T12:19:27+02:00 interface_configure[316] done.
2022-10-19T12:19:28+02:00 interface_configure[316] Configuring boring interface...
2022-10-19T12:19:28+02:00 interface_configure[316] done.
2022-10-19T12:19:29+02:00 interface_configure[316] Configuring foobaz interface...
2022-10-19T12:19:29+02:00 interface_configure[316] done.
2022-10-19T12:19:31+02:00 interface_configure[316] Configuring yes interface...
2022-10-19T12:19:31+02:00 interface_configure[316] done.
2022-10-19T12:19:31+02:00 interface_configure[316] Configuring LAN interface...
2022-10-19T12:19:32+02:00 interface_configure[316] done.
2022-10-19T12:19:32+02:00 interface_configure[316] Configuring WAN interface... …
```

system: write a boot log using the embedded configuration messages

---

src/etc/inc/certs.inc

Hi!
ref. https://forum.opnsense.org/index.php?topic=31109.0
(external (imported) CRLs cannot be viewed\edited)
since comparision have highest precedence then coalescing, `is_crl_internal` returns string if array member exists.
so all CRLs starts treated as internal
Thanks!

certs: typo in is_crl_internal

---

src/opnsense/www/css/tokenize2.css

Hi!
not a big deal but can annoy sometimes)
after some work in dev console, chrome may return tokenized field content with a garbage like
pr uses escaped unicode number
thanks!

tokenize2: unicode content in CSS

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableModelControllerBase.php

Hi!
noticed trying to enable `$internalModelUseSafeDelete` in nginx api settings controller (for  https://github.com/opnsense/plugins/issues/3196).
looks like the referencing nodes only matches if it matches exactly (only one uuid is specified?).
pr tries to make matches possible for multivalued referencing nodes.
tested on HAProxy and nginx configs
I hope I didn't miss anything
Thanks!

MVC: match multivalued references on 'safe delete'

---

src/etc/inc/plugins.inc.d/unbound.inc

Hi
ref. https://forum.opnsense.org/index.php?topic=31336.0
It turned out that when the DNS64 module is enabled, the blocklists do not work. Looks like the python module always has to be first for blocklists to work
thanks!

unbound: always use python first

---

src/etc/inc/plugins.inc.d/ipsec.inc
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/ConnectionsController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/PoolsController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/PreSharedKeysController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/VtiController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/ConnectionsController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/VtiController.php
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogChild.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogConnection.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogLocal.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogPSK.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogPool.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogRemote.xml
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogVTI.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/FieldTypes/ConnnectionField.php
src/opnsense/mvc/app/models/OPNsense/IPsec/FieldTypes/IKEAdressField.php
src/opnsense/mvc/app/models/OPNsense/IPsec/FieldTypes/IPsecProposalField.php
src/opnsense/mvc/app/models/OPNsense/IPsec/FieldTypes/PoolsField.php
src/opnsense/mvc/app/models/OPNsense/IPsec/FieldTypes/VTIField.php
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.php
src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml
src/opnsense/mvc/app/views/OPNsense/IPsec/connections.volt
src/opnsense/mvc/app/views/OPNsense/IPsec/pre_shared_keys.volt
src/opnsense/mvc/app/views/OPNsense/IPsec/vti.volt
src/opnsense/scripts/ipsec/get_legacy_vti.php
src/opnsense/service/conf/actions.d/actions_ipsec.conf

Add new component to manage IPsec connections in a similar format as `swanctl.conf` is defined (https://docs.strongswan.org/docs/5.9/swanctl/swanctlConf.html).  As this needs to work in conjunction with the legacy IPsec module, some minor changes are needed to the current state. 
o VPN/IPsec/Pre-Shared Keys - add optional remote identifier (merges in `ipsec.inc`)
o VPN/IPsec/Virtual Tunnel Interfaces - new component to show existing VTI's and add new ones (as these are separate entities)
o VPN/IPsec/Connections [new] - configuration tool to build `swanctl.conf` 
o Integrate MVC generated `swanctl.conf` into `ipsec.inc` (legacy overlays)
o Integrate manually configured VTI's into `ipsec.inc` (`array_merge(ipsec_get_configured_vtis(), (new \OPNsense\IPsec\Swanctl())->getVtiDevices())`)
o …

VPN/IPsec add new MVC module

---

src/opnsense/mvc/app/views/OPNsense/IDS/index.volt

Hi!
tested https://github.com/opnsense/core/commit/92e5536ca039ed558b5027077ed2e71a04230598 and it works great, thanks!
sorry, I did not mention one more in pr  - the alerts grid is not updated after log drop.
Thanks!

Services: Intrusion Detection: Administration - Alerts: reload grid after log drop

---

plist
src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/OverviewController.php
src/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Menu/Menu.xml
src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
src/opnsense/scripts/unbound/logger.py
src/opnsense/scripts/unbound/stats.py
src/opnsense/service/conf/actions.d/actions_unbound.conf
src/opnsense/service/templates/OPNsense/Unbound/core/dnsbl_module.py
src/opnsense/site-python/duckdb_helper.py
src/opnsense/www/css/dns-overview.css
src/www/reporting_settings.php
src/www/services_unbound.php

Moves the reporting backend from sqlite to duckdb.
Since, unlike sqlite, duckdb does not support concurrency, a wrapper has been written to synchronize access to the database. Refer to the class itself for further documentation.
If you were on the master branch and had unbound statistics enabled prior to this commit, you should `rm -f /var/unbound/data/unbound.sqlite` and restart Unbound.

unbound / overview: migrate to duckdb

---

src/opnsense/scripts/unbound/start.sh

Hi!
ref. https://forum.opnsense.org/index.php?topic=31475.0 and https://github.com/opnsense/core/commit/13ea70af049dabcec3f7fe907240d3a8aaeef4dc
just another place where the unbound-checkconf messes things up
( false-error triggers trust anchor update on every unbound (re)start)
Thanks!

unbound: change working dir before unbound-checkconf on start

---

src/opnsense/mvc/tests/app/models/OPNsense/Base/FieldTypes/TextFieldTest.php

* Verify/validate existing functionality
Add some tests for TextField. Some focus on TextField functionality, specifically the regex focused ones, but other focus on BaseField functionality which should properly inherit.
Some coverage for some unusual cases, but mostly just verifying expected functionality to flag if something breaks down the line.

mvc: TextField tests

---

src/opnsense/scripts/unbound/blocklists.py

Hi!
another thing noticed when trying to reproduce https://github.com/opnsense/core/issues/6026
if the connection or server is very (i made it 5 kbit/s) slow (and we also reduced the timeout value), the update may fail with a non-obvious `Command ' /usr/local/opnsense/scripts/unbound/blocklists.py && /usr/local/opnsense/scripts/unbound/wrapper.py -b ' returned non-zero exit status 1` error in backend log. Perhaps it makes sense to catch exceptions when reading a file? Then a more understandable message like
```blocklist download : error reading file from https://blocklistproject.github.io/Lists/alt-version/malware-nl.txt (error : HTTPSConnectionPool(host='blocklistproject.github.io', port=443): Read timed out.)```  will get into the unbound log, and script execution will continue
Thanks!

unbound: catch exception on blocklist reading

---

src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/services.xml
src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
src/opnsense/service/templates/OPNsense/Monit/monitrc

The PR is to add the ability via the web to configure Service Start Timeout.
This could be extended to include Service Stop Timeout as well but I wanted to see if this was going to be accepted first.
This is my first PR so take it easy, I willing to accept any pointers to feedback.
Thanks

Monit starttimeout

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dnsbl.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
src/opnsense/scripts/unbound/blocklists.py
src/opnsense/service/templates/OPNsense/Unbound/core/blocklists.conf

This includes the ability to whitelist a domain from the overview page as well. Relevant to both
the top passed/blocked domains, as well as the detailed query grid.
blocklists.py has been modified in such a way that it will detect whether it needs to
start the download process or simply administrate locally. The latter currently only happens
when custom domains for blocking have been added/removed by a user. The reasoning is
that we can easily extend/shrink the current blocklist when it comes to blocking exact
domains as this is handled on the incoming side. However, while we can modify the current
list to accomodate a new whitelist entry (which can be regex), we (currently) cannot know which domains
were skipped in the process of retrieving them in the first place if a user explicitly …

Unbound / Blocklists: add exact domain blocking and integrate into overview page

---

src/opnsense/mvc/app/library/OPNsense/Routing/Gateways.php

Hello. First-time contributor here.
I've been battling with an annoying problem on my OPNsense box (great software, btw). So, I have a dual-WAN setup and one of the WANs uses 6rd for IPv6. I followed the guide to set up a gateway group and then configured the right firewall rules. However, OPNsense was not routing IPv6 traffic at all. I was annoyed by this, so I spent a day debugging the issue and coding up a fix (which is this pull request). This problem ONLY occurs when you use a gateway group that contains a gateway that uses either 6rd or 6to4 for IPv6 connectivity. Here is what I discovered:
The root cause ended up being that OPNsense wasn't correctly writing the firewall rule to set the gateway policy for traffic entering the gateway. To be more precise, instead of using the correct …

Fixed route-to interface not being set correctly in firewall rules when using 6rd/6to4 IPv6 gateways with gateway groups.

---

src/opnsense/mvc/app/views/OPNsense/Core/firmware.volt

Hi!
finally closes https://github.com/opnsense/core/issues/5635 (i hope ;) ):
make tables responsive (by moving `.table-responsive` to the parent div);
workaround bootstrap "dropdowns inside responsive table" issue by adapting the table height when needed;
don't let the buttons fall apart;
thanks!

firmware.volt: responsiveness fix

---

src/www/firewall_nat.php

Hi!
Sorry, me again )
If port alias is specified as a Redirect target port, range is not calculated for rdr rule (local port is omitted or first port in alias is used): https://github.com/opnsense/core/blob/fdcd17cd5712f8a166cc76af9ee49cded3e617ff/src/opnsense/mvc/app/library/OPNsense/Firewall/ForwardRule.php#L123-L136
thanks!

Firewall/NAT/Port Forward - dont calc local port range for alias

---

src/opnsense/mvc/app/library/OPNsense/Firewall/Util.php

Hi!
possible fix for https://github.com/opnsense/core/commit/2ba91361a7e27f616fa8f1b46250267ffac34e74#commitcomment-98713264
Prevent possible infinite loop in getPortAlias if alias references itself somehow (add current (or nested) alias to "parsed aliases" array before parsing)

MVC/Firewall/Util - prevent possible infinite loop in port aliases parsing

---

src/opnsense/mvc/app/controllers/OPNsense/Interfaces/forms/dialogVip.xml

Currently description only shows for CARP type, but the description should show for all.

Make description field show for all types of VIP

---

src/opnsense/scripts/unbound/logger.py

Hi!
ref. https://forum.opnsense.org/index.php?topic=32494.0
looks like logger db without index initializes so much faster that pipe may not be ready yet due to json loading?
thanks!

Unbound: let the logger wait for the pipe a bit

---

src/etc/inc/plugins.inc.d/dnsmasq.inc
src/www/services_dnsmasq.php

I just found out that the default TTL for local DNS entries is just 1 second and that some nectwork clients just ask over and over for the same address again.
The "local" TTL is not yet configurable as well as two other parameters (dns_forword_max and cache_size), which is addressed by this patch.

dnsmasq: Create three more optional parameters

---

src/opnsense/scripts/unbound/logger.py
src/opnsense/service/templates/OPNsense/Unbound/core/dnsbl_module.py

Hi!
I'm very ashamed, perhaps the strangest typo on my end (I've never even used unary operators in real code).
as a result, the logger waits forever for the pipe ..
typo fix shows a dependence of the required waiting time on the size of the dnsbl (on a test vm with all lists enabled, it can reach up to 6 sec, so I set it to 10).
Besides of changing the order of actions in the `dnsbl_module.py` (first create a pipe, then load the json), using `Thread` to call load_dnsbl showed a good result.

unbound: fix typo in logger. create a pipe early in dnsbl_module.py

---

src/etc/inc/plugins.inc.d/openvpn.inc
src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/AliasController.php
src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.xml
src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/AliasContentField.php
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/scripts/filter/lib/alias/__init__.py
src/opnsense/scripts/filter/lib/alias/auth.py
src/opnsense/scripts/openvpn/ovpn_event.py
src/opnsense/service/templates/OPNsense/Filter/filter_tables.conf

Firewall / Aliases - Allow to create firewall rules for logged in OpenVPN user groups. (https://github.com/opnsense/core/issues/6312)
o extend model with authgroup type (currently only for OpenVPN) o add controller action to list user groups
o modify alias form to show group list in a similar way as network groups, simplify some of the code to prevent copying. o add AuthGroup parser to glue the output of list_group_members.php and ovpn_status.py to a set of addresses per group for our new authgroup alias type to use o hook 'learn-address' event in openvpn to trigger an alias update
Although theoretically we could pass addresses and common_names from learn-address further in our pipeline, for now we choose to use a common approach which should always offer the correct dataset (also after …

Firewall / Aliases - Allow to create firewall rules for logged in OpenVPN users

---

src/etc/inc/filter.inc
src/etc/inc/system.inc
src/etc/rc.bootup
src/etc/rc.syshook.d/monitor/10-dpinger

In an attempt to extract the default gateway switching out of filter_configure_sync() we actually move it to system_routing_configure() with minimal impact on current development state of things. Things to keep in mind:
1. The "down" interfaces are fetched and passed in this case.
2. When default gateway switching is active we ignore the user request for a specific interface if given. This way we save a hop between gateways of different interfaces in the original system_routing_configure() -> filter_configure_sync() flip-flop. Of note is that down gateways are thus never being used for the default route once gateway switching is enabled.
3. The monitor rc.syshook is easily ported over to rc.routing_configure call
4. Both system_routing_configure() and filter_configure_sync() are …

system: move default gateway switching to system_routing_configure()

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt

Leave out delimiter ('T') from UI last updated time display for better readability.  Run together strings are less readable for we mere mortals.

Can we please leave out the time delimiter ('T') too?  Better human readability.

---

src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml

Fix help-text error, should describe "second-level" instead "first level".
Reported-by: gecko_x2 (irc)
Signed-off-by: Sami Olmari <sami@olmari.fi>

Fix typo: "second-level subdir" in helptext

---

src/etc/inc/system.inc

This PR fixes adds handling for empty DNS server gateway to fix ` /system_general.php: ROUTING: not a valid host gateway address: ''`.
In System -> Settings -> General a user can _optionally_ set a gateway for each DNS server. However, if no gateway is set for a DNS server the error above is thrown. This is caused by `system_host_route` being always called, even though there is no gateway set. If none is set, there's no need to setup a static route.

system: Handle empty DNS server gateway

---

src/www/widgets/widgets/services_status.widget.php

It's not just the slash character that causes problems, it's really any character that has special meaning in a CSS selector.
Better to handle all characters properly. This updated PR uses a data attribute instead and removes the need to make a key from the ID.
In my case, I noticed it with `in.tftpd` (from the `os-tftp` plugin) being repeated once more every time the widget would refreshed. This is because the dot ends the ID selector and starts a class selector, causing it to create a new row (and making me think it was creating more and more processes that would crash the system).

Fully sanitize HTML ID avoiding CSS selector characters

---

src/etc/inc/filter.lib.inc
src/etc/inc/interfaces.inc
src/www/interfaces.php

PR: https://forum.opnsense.org/index.php?topic=33376.0

interfaces: VLAN priority fix for DHCPv4

---

src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml

- eliminate the artificial limit of length and signs which does not exist in squid
- allow in particular `@` to support `first.last@mycompany.com` as username
- all other characters can be used via URL escaping (i.e. `%20` for spaces) but this also means `%` must be written as `%%`
see http://www.squid-cache.org/Doc/config/cache_peer/

proxy: allow more signs for username and password

---

src/etc/rc.d/netflow
src/opnsense/scripts/netflow/lib/parse.py

This PR fixes an incorrect interface index used in Netflow.
Possibly related: https://forum.opnsense.org/index.php?topic=28555.msg138715#msg138715
I noticed this bug, because because my Netflow data (both `/var/log/flowd.log` and subsequently the SQLite DB created by the aggregator) contained incorrect interface index / name information.
Looking at `flowd-reader -v /var/log/flowd.log`, I see traffic from `pppoe0` (WAN) to `vtnet1` (LAN)
However, these flows are labled `in_if 11 out_if 2`, which map to `wg0` and `vtnet1` according to `ifconfig -l`.
All flows related to `pppoe0` are therefore wrongfully displayed and stored as `wg0` and vice-versa.
It looks like `ifconfig -l` doesn't return the interfaces according to their actual interface index.
The current behavior will cause **`wg0` to …

netflow: Fix incorrect interface index

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt

This PR fixes the progress bar default value.
I argue that if the actual number of entries hasn't been loaded yet, there's no reason to show `23%` per default. Additionally, this results in a flashy progress bar, even though there's no actual progress.
This is best visible when (re)loading the Firewall Alias page.
Before:
https://user-images.githubusercontent.com/46975855/232329685-40434a58-141c-4e93-a91f-4be61b722d17.mp4
After:
https://user-images.githubusercontent.com/46975855/232329702-fbb67fcd-9722-4acf-adbd-ab8f2f84ab67.mp4

firewall/alias: Fix progress bar default value

---

src/opnsense/service/templates/OPNsense/WebGui/php.ini
src/www/system_advanced_admin.php

With the default PHP settings, there is a 1% chance for the session gc to trigger upon the start of a session, removing session files with modification times older than 24 minutes. This can cause sessions to timeout earlier than indicated by the webgui settings.

webgui: prevent PHP session gc from running early

---

src/etc/inc/system.inc

The hyphen was added in the wrong place causing the 'route add' command to error out. This was causing it to run
`route add inet -'IP' 'GW'`
when it should be
`route add -inet 'IP ' GW'`
Reference: https://github.com/opnsense/core/pull/6580#issue-1729389899

Fix issue with route add command

---

src/etc/inc/plugins.inc.d/ipsec.inc

Looks like `$ipseccfg` is only used in the if condition just after this definition, and it is also wrapped in an `isset()`. This should catch when ipsec node doesn't exist in the config, set to an empty array, and then the following isset() will be looking for the named index in an empty array which will not be set.

ipsec: Check ipsec config exists before using, closes #6411

---

src/etc/inc/authgui.inc
src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/scripts/OPNsense/CaptivePortal/htdocs_default/index.html
src/www/head.inc

Ref: https://searchfacts.com/noodp-noydir-meta-tags/
I did learn this right now, and found all occurrences to remove them as the projects are long gone

src: remove noodp and noydir, they do not serve any SEO purpose now

---

src/etc/inc/plugins.inc.d/webgui.inc

Hi!
Noticed that the gui returns the content uncompressed, although the `mod_deflate` module is enabled.
I think lighty expects `deflate.allowed-encodings` to select a method from a match with the browser request.
after adding the option, content is returned gziped.
perhaps building lighty with `--with-brotli` would be good  but I did not find it in the ports..
ref. https://redmine.lighttpd.net/projects/lighttpd/wiki/Mod_deflate
thanks!
ps. I'm not sure about the need to add a cron for old\stale cache entries purge.

webgui: enable compression

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/advanced.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/service/templates/OPNsense/Unbound/core/advanced.conf

See: https://forum.opnsense.org/index.php?topic=23747.0
Maximum negative TTL for cached records.
Useful if the cloud isn't as fast as you are.
For example, if you add records to CloudFlare it may take a few moments before the records are propagated.
If the negative TTL on that domain 1h, you need to flush your local cache (or wait an hour).
The setting forces a max TTL on negative responses (NXDOMAIN responses).
before:
```
> dig test.tcdn.nl     
...
;; QUESTION SECTION:
;test.tcdn.nl.			IN	A
;; AUTHORITY SECTION:
tcdn.nl.		3600	IN	SOA	donna.ns.cloudflare.com. dns.cloudflare.com. 2300657040 10000 2400 604800 3600
...
```
after added setting set to 30:
```
>dig test.tcdn.nl     
...
;; QUESTION SECTION:
;test.tcdn.nl.			IN	A
;; AUTHORITY SECTION:
tcdn.nl.		30	IN	SOA …
```

unbound: Added cache-max-negative-ttl setting

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dnsbl.xml

'Enable Safe Search' doesn't do justice to what the option actually does, which is attempt to strictly enforce safe search. Byproducts of which include, but maybe not limited to, restrcting general usage of YouTube.
Once Safe Search is Enabled, YouTube operates in Restricted mode, as if any Google Account holder attempting to use YouTube is restricted by Google Workplace policy, or Family Policy. To my mind, Enabling and Forcing are different. I did not expect the Enabling of Safe Search in OpnSense to cause my YouTube content to be restricted like I'm 13 years old. It took me a little while to track the cause down. 'Enable' is a fairly soft word for what takes place inside OpnSense, whereas 'Force' is I believe more accurate.

Better description for Safe Search

---

src/etc/inc/interfaces.lib.inc

The current OPNsense code displays the same number for active ports and flapping ports in the interfaces overview page. The displayed flapping count does not match the output of `ifconfig -v <interface>`.
This looks like it was a simple copy/paste error in the code and the fix is very simple.
This was reported on the forum at https://forum.opnsense.org/index.php?topic=30098.0

LAGG interfaces: Fix bug with reported number of flapping ports

---

plist
src/opnsense/mvc/app/controllers/OPNsense/Base/ApiMutableServiceControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/DHCPv4/Api/LeasesController.php
src/opnsense/mvc/app/controllers/OPNsense/DHCPv4/Api/ServiceController.php
src/opnsense/mvc/app/controllers/OPNsense/DHCPv6/Api/LeasesController.php
src/opnsense/mvc/app/controllers/OPNsense/DHCPv6/Api/ServiceController.php
src/opnsense/mvc/app/views/OPNsense/DHCPv4/leases.volt
src/opnsense/scripts/dhcp/prefixes.sh
src/opnsense/service/conf/actions.d/actions_dhcpd.conf
src/opnsense/service/conf/actions.d/actions_dhcpd6.conf

To allow legacy services without a model to hook into the `ApiMutableServiceController`, we define a protected `serviceEnabled` function that by default checks the given `internalServiceEnabled` property to see if a service is enabled, but allows derived classes to override the functionality. We loosen the property restrictions in `initialize()` by moving the checks to their runtime implementations.
DHCPv4/v6 is modified here to hook into this change, but since the `actions_services` requires the keyword `service`, which isn't used by the mutable service controller, we define start/stop/restart/status actions in the `actions_dhcpd.conf` and the new `actions_dhcpd6.conf` files.

MVC: allow new legacy services to hook into ApiMutableServiceController

---

src/opnsense/scripts/dhcp/dnsmasq_watcher.py
src/opnsense/scripts/dhcp/unbound_watcher.py

Currently DHCP leases with DNS names including underscores cause a warning "dhcpd leases: XXX_XXX not a valid hostname, ignoring" 
While these may not be true internet-valid hostnames according to IETF, many valid DNS names include underscores (e.g. _acme-challenge for ACME/letsencrypt validation, microsoft active directory names, SRV records, and manufacturer-default IP camera names, though I'm sure there are others). 
Blindly denying underscores for DNS records is likely to cause unforeseen issues, and I don't believe it's in our best interest to police names to that degree.

Allow underscores in DNS names from DHCP leases

---

src/opnsense/scripts/suricata/metadata/rules/et-open.xml

Update the ruleset urls to match suricata 7.0. Currently there is no difference in the files provided.

Update ET-Open to match Suricata 7.0

---

src/etc/inc/plugins.inc.d/ntpd.inc

From ntp.conf man page:
if you want to use servers from a pool directive and also want to use nopeer by default, you'll want a restrict source ... line as well that does not include the nopeer directive.
This PR reorders ntpd.inc to remove `nopeer` from the `restrict source` line.
[Forum discussion](https://forum.opnsense.org/index.php?topic=35311.0)

ntpd: fix 'Soliciting pool server'

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/dialogUserDefined.xml
src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml
src/opnsense/service/templates/OPNsense/IDS/OPNsense.rules

Ref: #6744
Adds a new input field in `Services: Intrusion Detection: Administration: User defined` which adds `bypass;` keyword to `/usr/local/etc/suricata/opnsense.rules/OPNsense.rules`.
Rules are generated with the template `src/opnsense/service/templates/OPNsense/IDS/OPNsense.rules `and look like this when the checkbox is enabled:
`pass ip   10.0.0.0/8  any ->  10.0.0.0/8  any (msg:"bypass 10.0.0.0/8 to 10.0.0.0/8"; bypass; sid:1; rev:1;)`

"bypass" keyword in suricata user defined rules

---

src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogLocal.xml

Confusing punctation would imply that the field is only relevant for certificate authentication.

Fix misleading help text

---

src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php

When a different CA is specified for client certificate validation than the server certificate's CA, a wrong list of certificates is shown in the Client Export dialog.

OpenVPN Client Export: fix certificate list when CA specified

---

src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogConnection.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml

[#6818](https://github.com/opnsense/core/issues/6818)
I created new dropdown menus in the IPsec Connections Form. 
Users can select between port 500 (default) and port 4500 (NAT-T). I didn't create a free input field since other values have to be actually supported by the backend, and I didn't see the usecase for free choice.
I didn't upgrade the model version since I used the `elseif ((string)$attr == '')` in the Swanctl.php in order to skip the default value. I chose the default value as empty, because I didn't want to add local_port = 500 and remote_port = 500 explicitly to the configuration file, it's not needed since its the default even if its not specified. Thus I could maintain a non required field that won't need a migration since no config changes will be made when its …

Add local_port and remote_port to VPN: IPsec: Connections [new]

---

src/opnsense/scripts/dhcp/prefixes.php

Allows prefix delegation to downstream routers which have an unnumbered WAN interface.
As discussed on the forum: https://forum.opnsense.org/index.php?topic=35724.msg174257#msg174257

dhcpd6: add scope to link-local DHCPv6 static mapping when creating route for delegated prefix

---

src/etc/rc.bootup

During bootup the gateway monitors were started before the firewall rules were finished setting up. Under some circumstances this could lead to incorrect data being reported by `dpinger` instances.
Closes #6862

system: start gateway monitors after firewall rules are in place

---

src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseField.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/BaseListField.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/NetworkAliasField.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/PortField.php
src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/TextField.php

* defaultValidationMessage() provides the field default (because gettext() doesn't work on constants)
* $internalValidationMessage only provides the XML value if given (translated via lang.git)
* getValidationMessage() returns the preferred validation message correctly translated

mvc: improve field validation message handling

---

src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php

OpenVPN configs generated for new instances did not include instructions to call `ovpn-linkup` and `ovpn-linkdown`. Due to this `newip` would not trigger and `rc.newwanip` would not be called. For example this would lead to gateway monitors not starting.
Closes #6868

openvpn: add up and down scripts to vpn instance configs

---

src/opnsense/mvc/app/models/OPNsense/Interfaces/VxLan.php

[#6893](https://github.com/opnsense/core/issues/6893)
That was rather challenging for me. But I think I got it working the way it should.
Here's some screenshots with the results:
Requirement for either Remote address or Multicast group NOT to be empty:
Requirement for both Remote address or Multicast group NOT to be populated at the same time:
Requirement for Device being set when Multicast group is populated:
Requirement for Device being NONE when Remote address is populated:

Update VxLan.php - Add input validations to model

---

src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/scripts/unbound/blocklists/__init__.py
src/opnsense/scripts/unbound/blocklists/default_bl.py
src/opnsense/service/templates/OPNsense/Unbound/core/blocklists.conf

Also add 3 lists that contain wildcard domains. Removed the "exclude non domain entries" regex pattern since all domains are filtered through a larger domain pattern that now includes the wildcard symbol as well.

unbound: add support for wildcard domain lists

---

src/www/widgets/widgets/ipsec.widget.php

https://github.com/opnsense/core/issues/6889
This change attempts to solve the problem of users having multiple IP addresses as leases and being counted per leased IP.
- Only "user" are counted now
- Each "user" can have several "lease"
- Each "lease" can have an individual online or offline status
- A user is online when at least one "lease" is "online = true"
The code can be tested with this sample data. It can be placed in line 46 and populates the variable $ipsec_leases = []
```
$ipsec_leases = array(
array(
'pool' => 'pool-roadwarrior-ipv4',
'address' => '172.16.203.1',
'online' => true,
'user' => 'user1@vpn1'
),
array(
'pool' => 'pool-roadwarrior-ipv4',
'address' => '172.16.203.2',
'online' => false,
'user' => 'user2@vpn1'
),
array(
'pool' => 'pool-roadwarrior-ipv4',
'address' => …
```

Update ipsec.widget.php - Count user in "Overview" Tab and improve "Mobile Users" Tab

---

src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.xml

Hi,
it seems that when leaving the field empty, you have an empty dropdown list in authentication and children, it's a bit weird when you forget to fill in the field it's quite hard to find the error why you cannot link the newly created connection.
Happy if you find an alternative to this PR :)

ipsec: make Description in Connections Required

---

src/etc/inc/plugins.inc.d/wireguard.inc
src/opnsense/scripts/Wireguard/wg-service-control.php

Since we used to allow IP configuration ands VIPs are a possibility we can avoid checking for missing IPs and simply delete the status hash file which will force an eventual reconfiguration.
While here avoid wireguard_prepare() from creating spurious devices when there is no need for it as it happens with manual invoke through "pluginctl -d wgX".  wg-service-control uses the same logic.

wireguard: different approach to bootup handling

---

src/etc/inc/auth.inc

This doesn't check a shifting password for other technical reasons but is more correct and fixes toggling disabled authentication on my end.
PR: https://forum.opnsense.org/index.php?topic=36528.0

system: need to detect a password shift from off <=> on

---

src/opnsense/scripts/suricata/metadata/rules/et-open.xml

doc.emergingthreats.net has its SSL certificate expired for over half a year.
Clicking https://doc.emergingthreats.net/bin/view/Main/EmergingFAQ leads to a browser warning "This is an unsafe connection". So not looking very trustworthy to install IDS rules from :wink: 
I thought of putting subpage https://rules.emergingthreatspro.com/OPEN_download_instructions.html as it targets more specific the instructions page. However, there is no navigation to go back to the top page.
As I user, clicking from OPNsense's "Ruleset details" dialog to get more information what rules I am going to download https://rules.emergingthreatspro.com helps me more.

IDS: Fixed old documentation URL of ruleset "ET open"

---

src/etc/inc/auth.inc
src/etc/inc/authgui.inc
src/opnsense/mvc/app/library/OPNsense/Auth/Local.php
src/www/system_authservers.php

Add a simple compliance option for SHA-512 use and enforce it on login. Only do this for entering compliance. I doubt it's ever going to be switched off (and if it is requiring to manually changing passwords is not a big deal).
Also increase the bcrypt cost to 11 to make it even more attractive from a security perspective.

system: add SHA-512 password hash compliance switch; closes #6966

---

src/etc/inc/console.inc
src/etc/inc/plugins.inc.d/pf.inc
src/www/diag_backup.php

Raising the bar with an official PR ;)
There are two parts:
1. consistent import per section "set" making sure nonexistent entries in the new config are cleared in the old one.
2. bring back "aliases" section to be able to migrate (doesn't work without 1.)

system: extend restore to be able to migrate

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/Api/Dhcpv4Controller.php
src/opnsense/mvc/app/views/OPNsense/Kea/dhcpv4.volt

The device's IP address is missing from the KEA reservations table. See #6971

Kea / Dhcp - DHCPv4 replacement [#6971], Add "IP Address" to KEA reservations Table

---

src/etc/inc/plugins.inc.d/openssh.inc
src/etc/inc/plugins.inc.d/webgui.inc

WebGUI and SSH connections to link-local addresses only work if the listen interfaces are set to "All (recommended)". This PR allows link-local connections for specific listen interfaces, too. While selecting specific interfaces is only recommended for some use cases, explicitly excluding link-local addresses doesn't seem appropriate. Maybe there once was a bug which required this?

webgui + openssh: listen on IPv6 link-local addresses

---

src/etc/inc/console.inc
src/etc/inc/interfaces.inc
src/etc/rc.linkup
src/etc/rc.syshook.d/carp/20-ppp
src/opnsense/scripts/interfaces/ifctl.sh
src/opnsense/scripts/shell/setaddr.php
src/www/interfaces.php
src/www/interfaces_assign.php
src/www/status_interfaces.php

Add new variants interface_suspend() and interface_reset() in order to test the new variants once for rc.linkup and interfaces.php. Temporary file read isn't optimal but it avoids tainting callers with additional arguments that might be wrong...  Later we can switch individual use from interface_bring_down() to the one or the other and refactor again if it is no longer called directly.
I'm entirely unsure about the PPP on demand primer, but in general it would make sense to avoid it when the interface is disabled. The historic way of doing it is priming it for reconfiguration on 'bring-down' so that it can be back up when the line is required.

interfaces: split bring_down into dynamic and static parts #6852

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/log.volt

Hi!
Can we try using built-in event to handle async `selectpicker` init (should be faster and more reliable)?
sorry, i’m also not very clear about class check part. if this is about https://github.com/snapappointments/bootstrap-select/issues/2756 , do we really need to care about the select class if we assign the `selectpicker` not to the class, but to the id?
Thanks!
upd. one moment..

core / log views - use built-in selectpicker event to handle async init

---

src/etc/inc/plugins.inc.d/ntpd.inc

Without the "interface ignore wildcard" directive, the service still listens on wildcard.

Make the GUI interfaces selection actually honored by ntpd

---

src/www/widgets/widgets/interface_statistics.widget.php

Afraid this issue persists even after the revamp from https://github.com/opnsense/core/pull/7019. This is literally illegible mess with large packet counts and multiple dashboard columns otherwise, that `toLocaleString()` does not help either.  
See example screenshots - the last one is after this fix.

Add word break in interface_statistics.widget.php

---

src/www/head.inc

Add meta tags for Android and iOS to allow the WebUI to run in fullscreen/standalone mode on mobile browsers.
I have tested this by accessing my opnsense via ssh and editing /usr/local/www/head.inc to include this.
"App" now opens as a full screen app rather than a tab in the web browser.

Update head.inc to include meta tags for standalone/full-screen on Android & iOS

---

src/opnsense/mvc/app/views/OPNsense/Diagnostics/traffic.volt
src/www/widgets/widgets/traffic_graphs.widget.php

default `brewer.Paired12` color scheme contains pairs very similar colors, so every two interfaces in list look very similar to each other, see image, where dataset1 and dataset2 are blue, dataset3 and dataset4 are green
to increase contrast between interface graphs I suggest to use `tableau.Classic10` which contains 10 very distinctive colors:
This should partially fix: [#6622](https://github.com/opnsense/core/issues/6622)
Another problem is that traffic widget and traffic diagnostic graphs are using different color schemes and indexes for the same interface, which is inconsistent and confusing, it is better to apply the same rules in both sections

update traffic graph colors to be contrast and consistent in widget and traffic diagnostic

---

src/opnsense/mvc/app/views/OPNsense/Firewall/alias_util.volt

Hi!
may close https://github.com/opnsense/plugins/issues/3782 i hope.
'.selectpicker' auto-init may result a too narrow alias choice select. and it not handles well by 'refresh' or 'render' methods.
reproduces quite stable in the Edge browser.
PR inits bs.select after all options have been added so that bs.select knows the required width.
Thanks!

alias_util.volt: make select width more consistent

---

src/www/firewall_rules.php

1. For a floating rule with a single interface group, the interface count and tooltip did not show when viewed from an interface rules page.
2. For a floating rule with an interface group and at least one other interface or interface group, the entire rule did not show when viewed from an interface rules page for which the interface is contained in one of the interface groups.

firewall/rules: fix floating rule display

---

src/opnsense/www/js/opnsense-treeview.js

This fixes some display issues in Firewall: Diagnostics: Statistics where there are more than one instance of > or < in the same line.

core/treeview - replace all &gt; and &lt;

---

src/opnsense/service/conf/actions.d/actions_wireguard.conf

Sometime we need to restart wireguard during the night cause of ISP disruptions.
Can we have description to restart wireguard via cron?

WireGuard: Add description for restart

---

src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogConfigBuilder.xml

"Address" was incorrectly spelt as "adress"

Misspelling of address in wireguard peer generator

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet4.xml
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml

Fixes: #7417
Closes: #7417 
**Describe the bug**
When setting multiple search domains in Kea DHCP subnets, the configuration file /usr/local/etc/kea/kea-dhcp4.conf is written incorrectly.
The configuration file will be written as 
```json
{
"name": "domain-search",
"data": "first.domain;someother.domain"
},
```
This causes Kea to simply not report a search domain at all.
Based on the Kea documentation, I manually updated the file to this and restarted the service, which then behaved as expected.
```json
{
"name": "domain-search",
"data": "first.domain,someother.domain"
},
```
**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Services'
2. Click on 'Kea DHCP [new]'
3. Click on 'Kea DHCPv4'
4. Switch to the 'Subnets' tab
5. Configure a subnet with multiple search domains
6. Save …

fix: :bug: Update field separator for Kea DHCP Subnet Form and Model

---

src/opnsense/scripts/suricata/queryAlertLog.py
src/opnsense/scripts/syslog/queryLog.py

On boot with python 3.11 a new deprecation warning appears:
```
configd.py	[e3c1a4e0-1dec-4667-a300-0ceff7926539] Script action stderr returned "b"/usr/local/opnsense/scripts/syslog/queryLog.py:36: DeprecationWarning: module 'sre_constants' is deprecated\n import sre_constants""
```
It's only used to have an exception class `sre_constants.error` it can be safely replaced with `re.error` since it is also imported from regex compiler there.

src: resolve deprecation warnings for sre_constants

---

src/opnsense/www/css/dashboard.css
src/opnsense/www/js/opnsense_widget_manager.js

When trying out the new dashboard, the save button didn't give me any feedback on successful save. So I have added a page reload.

dashboard: add page reload on successful save

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet4.xml
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.php
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml

This PR aims to add the ``next-server`` (a.k.a. ``siaddr``) option to support PXE network booting with Kea
Fixes: #7189

Add next-server option to Kea

---

src/etc/inc/filter.lib.inc

The origin of the link-local allow rule for DHCPv6 traffic is a bit weird and the rule itself is probably dysfunctional, see https://github.com/pfsense/pfsense/commit/dbcddabcdf7e -- It has never been edited again and remains the same in OPNsense and pfSense today. Typically server client traffic exchanges exclusively over port 546 and 547 so the original one may have been a typo.
Now as witnessed by #7527 the server port could be random, but should always come from link-local so we can merge both rules into one without causing much problems. Works fine locally on my network too.

interfaces: change IPv6 requirements #7527

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt
src/opnsense/mvc/app/views/layout_partials/base_dialog_processing.volt

Aria-hidden attribute makes dialogs inaccessible for screen readers.

MVC: remove aria-hidden from base dialogs

---

src/www/firewall_rules.php

Added aria-label attribute to buttons on firewall rules table. Also removes aria-hidden attribute from modal dialogs. 
Using aria-hidden makes dialogs invisible to screen readers.

firewall rules page accessibility fixes

---

src/opnsense/scripts/interfaces/list_arp.py

Currently the `resolve` parameter for the [getArp](https://docs.opnsense.org/development/api/core/diagnostics.html#id5) API call performs the opposite behavior you'd expect. When the `resolve=yes` parameter is supplied `list_arp.py` _will not_ resolve hostnames, while `resolve=no` (the default) _will_ resolve them. 
If this behavior is intentional, disregard this PR.

API: reverse getArp resolve parameter behavior

---

src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt

Added aria-label attributes to form input field template. This allows screen readers to associate the proper label with the form field.

MVC: add aria-label attributes to form input fields template

---

src/www/firewall_nat.php

Since the commands column is marked as a table header, screen readers will read the buttons every time a user navigates to a cell anywhere in that column. This causes a lot of extra speech output. Adding role="cell" to the commands column will suppress this.

firewall: added cell role to commands column on Nat page

---

src/www/firewall_nat_edit.php

Since this is not a data table, adding role="presentation" to remove extra screen reader announcements.

firewall: added presentation role to table on nat edit page

---

src/www/firewall_rules_edit.php

For tables that are purely used for presentation as opposed to data, using the role="presentation" attribute prevents extra announcements from screen readers. For example, in this table, the Advanced and Show/Hide headers at the end of the table were being read on every cell when navigating with a screen reader.

firewall: added presentation role to edit rules table

---

src/opnsense/scripts/routes/gateway_status.php

While creating a Gateway Prometheus Exporter for OPNSense, I was interested in which IP was being monitored by dping, not just the name of the gateway. This PR exposes that information through the API.

Add monitor IP to API results.

---

src/opnsense/service/templates/OPNsense/IDS/suricata.yaml

Removes deprecated -http and -tls from types/alert, and adds useful default features for output
Example suricata.yaml config used for reference, it is version 7.x:
https://github.com/OISF/suricata/blob/main-7.0.x/suricata.yaml.in
I have successfully tested these (and more) settings, but I was using the /usr/local/etc/suricata/custom.yaml file and restarting the service to see it not error output about the deprecated settings. It is my understanding that the environment replaced the suricata.yaml setting with the custom.yaml setting.
The custom.yaml file does not work completely as expected btw, see here: https://forum.opnsense.org/index.php?topic=40955.msg200771
If that means I did not complete a successful test, please let me know, otherwise this should mean fewer errors and useful logs …

Update suricata.yaml and remove two deprecated settings and add a few useful settings

---

src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml

In the classic, legacy server variant there was an option called "dynamic_ip" which injected the options `persist-remote-ip` and `float` into the generated configuration file. In the modern variant `persist-remote-ip` is already available, but `float` isn't available anymore.
The OpenVPN `float` option is used to allow client to change IP addresses during an ongoing connection to allow roaming e.g. in mobile networks or changes in the client WiFi.
See https://github.com/opnsense/core/blob/d2ef070687d1a4077a818211db4ffd6a5eab69f6/src/etc/inc/plugins.inc.d/openvpn.inc#L872-L875

OpenVPN instances: Add float option to support roaming clients

---

src/opnsense/www/js/widgets/BaseWidget.js

- Remove nested if statements
- always return size+unit (e.g. 0 B, 100 B, 10 KB...)
- implement additional null check. (The OpenVPN api returns null sometimes, compare here: https://github.com/opnsense/core/issues/7701#issuecomment-2264662820 )
Fixes: https://github.com/opnsense/core/issues/7725 https://github.com/opnsense/core/issues/7701

dashboard: BaseWidget - Improve _formatBytes function

---

src/etc/inc/interfaces.inc

Adds `-u` flag to ifconfig check to ensure only interfaces that are UP are reported. Furthermore adds a check for the output of ifconfig to ensure that the interface in question in fact is listed.
Otherwise the check will "approve" an interface that is not yet UP, and subsequent calls to fetch the gateway of that interface might fail if issued to quickly thereafter.
Resolves #7691

interfaces: require PPP interface to be in up state

---

src/etc/inc/plugins.inc.d/webgui.inc

IPv6 addresses might be tentative. lighttpd will fail when trying to bind to a tentative address. This commit skips tentative IPv6 addresses for binding.

Skip tentative IPv6 addresses for binding of webgui. Fixes: #7649

---

src/opnsense/www/js/widgets/Metadata/Core.xml

...so there is no line break that increases the size of the widget.
Fixes: https://github.com/opnsense/core/issues/7734

dashboard: Make titles of Swap and Mbuf shorter 

---

src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/AccessController.php

Captive portal > user unable to logoff via the user form 
I found the issue that actions.d > captive portal > disconnect command is mismatched parameters that is why it is not getting logoff.
either we can modify the actions.d command for captive portal with parameter or as I raised this PR, remove zoneid from the accesscontroller.

Captive portal logoff issue fixed

---

src/opnsense/www/js/opnsense_widget_manager.js

This PR fixes the grouping of the right buttons.

Dashboard: Change widgets menu buttons to a bootstrap group.

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/advanced.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/service/templates/OPNsense/Unbound/core/advanced.conf

Adds support for 'discard-timeout' to Unbound configuration.
This can be useful when using the option to serve expired responses.
The new option is added just below 'Jostle Timeout' within the advanced panel. 
I did consider adding it within the serve-expired section, however it's not strictly as tightly related and has more general applicability (as per unbound docs). I also removed once sentence (for help) which made no sense from the unbound docs, and clarified the exact labels used for related settings in the UI.
I tested with a 'live' install to ensure the panel worked, and the value was then placed into /var/unbound/advanced.conf
Based off master
Fixes #7493

unbound: discard-timeout

---

src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/generalSettings.xml
src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml
src/opnsense/service/templates/OPNsense/IDS/suricata.yaml

Add the appropriate front end controls and backend template for setting up TLS and HTTP monitoring for Suricata's eve-log.

IDS: Support configurating eve-log for HTTP and TLS

---

src/etc/inc/plugins.inc.d/core.inc
src/etc/inc/system.inc
src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Trust/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Trust/forms/settings.xml
src/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/Trust/General.php
src/opnsense/mvc/app/models/OPNsense/Trust/General.xml
src/opnsense/mvc/app/models/OPNsense/Trust/Migrations/M1_0_0.php
src/opnsense/mvc/app/views/OPNsense/Trust/settings.volt
src/opnsense/scripts/system/ssl_ciphers.py
src/opnsense/scripts/system/tls_groups.py
src/opnsense/service/conf/actions.d/actions_system.conf
src/opnsense/service/templates/OPNsense/Trust/openssl.cnf
src/www/system_general.php

This PR offers our Trust settings it's own configuration area, moves `store_intermediate_certs` into it and adds the following functionality:
* Optionally deploy CRL's into their designated place, so the default OpenSSL can make use of them
* Make `legacy_sect` an optional feature, enabled by default to not change current behavior
* Allow configuration constraints for the following parameters when the OpenSSL consumer doesn't offer its own: CipherString, Ciphersuites, groups(Curves), MinProtocol[DTLS]
todo:
* implement 'crl' event for local CRL's
* maybe, optional autofetch CRL's for known CA's

Add System: Trust:  Settings page

---

src/opnsense/www/js/opnsense_widget_manager.js

If there is a syntax error in the widget JS code we will not be able to remove it from the dashboard.  This is only a POC as it doesn't fully work for varying reasons, but details where the problem lies.

system: render header for failed active widgets to allow removal

---

src/opnsense/mvc/app/views/layout_partials/base_tabs_header.volt

This change makes the tabs that use the `base_tabs_header.volt` `layout_partial` more in line with all the other tabs in the GUI that do not use bold text.

mvc: Remove bold text from base_tabs_header.volt

---

src/opnsense/mvc/tests/app/models/OPNsense/Base/Constraints/ComparedToFieldConstraintTest.php

Add unit tests for a specific case as we had [concerns](https://github.com/opnsense/core/pull/7879#discussion_r1770370436) with this specific code when `$other_node_content` is `null` (x-link #7879)
The tests `test_if_it_validates_constraint_if_other_is_null_and_no_error`/`test_if_it_validates_other_node_empty_values_correctly_with_gt_and_no_error` will specifically trigger that case.
/cc @fichtner :pray:

tests: Add a unit test for ComparedToFieldConstraintTest

---

src/opnsense/scripts/syslog/queryLog.py

Recent feature addition to apply time constraint fails in cases where a log line does not contain a timestamp, as in the case of multi-line log entries. This change just moves on when a line contains no timestamp, as we will eventually find the line that contains the start of the log entry (and the timestamp).
fixes #7888

System/Logging - handle lines with no timestamp

---

src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/settings.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml

Fixes: https://github.com/opnsense/core/issues/7776
Since the default for "make_before_break" is "no" without the option set, it is not required and does not provide a default in the model.

ipsec: settings: Add make_before_break option

---

src/etc/inc/plugins.inc.d/vxlan.inc

Changing either vxlanlocal or vxlanremote in the GUI in an existing vxlan entry and applying will lead to no changes because the device silently fails during ifconfig:
```
root@opn-be-01:~ # ifconfig vxlan1 vxlanid 1 vxlanlocal 172.16.88.2 vxlanremote 172.16.88.3 vxlanlocalport 4789 vxlanremoteport 4789
ifconfig: VXLAN_CMD_SET_VNI: Device busy
```
Bringing the device down, applying the change and then bringing it back up will apply these changes.
```
vxlan1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
description: lan_vxlan1 (opt3)
options=80020<JUMBO_MTU,LINKSTATE>
ether 58:9c:fc:00:3a:05
inet6 fe80::5a9c:fcff:fe00:3a05%vxlan1 prefixlen 64 scopeid 0xd
groups: vxlan
vxlan vni 1 local 172.16.99.2:4789 remote 172.16.99.3:4789
media: Ethernet autoselect …
```

vxlan: fix interface being busy when vxlanlocal or vxlanremote is changed

---

src/opnsense/mvc/tests/app/models/OPNsense/Base/Constraints/ComparedToFieldConstraintTest.php

Relates #7883 #7878
@fichtner here are the failing tests (code fix in #7878)
```
root@OPNsense:/usr/local/opnsense/mvc/tests # phpunit --configuration PHPunit.xml
PHPUnit 9.6.20 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.2.23
Configuration: PHPunit.xml
................................FF.............................  63 / 214 ( 29%)
............................................................... 126 / 214 ( 58%)
............................................................... 189 / 214 ( 88%)
.........................                                       214 / 214 (100%)
Time: 00:00.132, Memory: 50.88 MB
There were 2 failures:
1) OPNsense\Base\Constraints\ComparedToFieldConstraintTest::test_if_it_validates_zero_number_ranges_correctly_with_lt_and_error
Failed asserting …
```

tests: Add failing unit tests for ComparedToFieldConstraintTest

---

src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogInstance.xml
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml
src/opnsense/scripts/openvpn/client_connect.php
src/opnsense/scripts/openvpn/user_pass_verify.php

Fixes https://github.com/opnsense/core/issues/7953
`ccd-exclusive` doesn't work in our case, as explained in https://github.com/opnsense/core/issues/4293.
This is logical, as we use our own hook to dynamically generate the CSOs to allow for multiple authentication backends to dictate the contents of the CSO. Therefore, the `ccd-exclusive` option on it's own doesn't make much sense from the perspective of e.g. Radius, as there is no common name to match to and as such the original option would not add as much benefit in terms of security.
This PR matches both `common-name` and `tunnel_network`/`tunnel_networkv6`. In all cases an ipv4/ipv6 network must be provisioned with this option enabled.

OpenVPN: Instances: add Require Client Provisioning option

---

plist
src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/ConnectionsController.php
src/opnsense/mvc/app/views/OPNsense/IPsec/settings.volt
src/opnsense/scripts/ipsec/get_swanctl.py
src/opnsense/service/conf/actions.d/actions_ipsec.conf

Bootstrap dialogue warns user about sensitive file contents. Error scenarios like missing file or API errors are handled gracefully with error messages.
The dialogue only appears once until page is reloaded.
Fixes: https://github.com/opnsense/core/issues/7751

vpn: ipsec: Add swanctl.conf download button to settings.volt view

---

src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/GroupNameField.php

Fixes: https://github.com/opnsense/core/issues/8021
(Also must is better than shall)

firewall: groups: Enhance validation that group name can not start or end with a digit

---

src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/GroupNameField.php

Reverts to shall to keep translation the same.
Use same style for changed validation.

firewall: groups: Fix wording of 9425ca7

---

src/etc/inc/config.inc
src/etc/inc/filter.inc
src/etc/inc/filter.lib.inc
src/opnsense/mvc/app/models/OPNsense/Base/Menu/MenuSystem.php
src/opnsense/mvc/app/models/OPNsense/Firewall/Filter.xml
src/www/firewall_nat_edit.php
src/www/firewall_nat_out_edit.php
src/www/firewall_rules_edit.php

(https://www.openbsd.org/faq/pf/filter.html) and skip lo0 from processing. closes https://github.com/opnsense/core/issues/8009
Since I needed to skim the filter.* files anyway, also add the following minor improvements:
* change array() to []
* skip ipv6 only rules when ipv6 is disabled
* make carp rules conditional

Firewall - adhere to best practices 

---

src/etc/config.xml.sample
src/etc/inc/system.inc

Most cloud providers based on KVM have either a bug or a common misconfiguration in their VirtIO network interface implementation which leads to FreeBSD falsely probing the interface as checksum offload capable while the emulated hardware in fact does not perform the offload.
The root cause of the problem is currently investigated by various developers in the FreeBSD community with support from at least Vultr and possibly Digitalocean last that I heard of the current state.
The simple and effective workaround is to disable checksum offloading globally for vtnet(4) interfaces.
I therefore argue this sysctl value should be the default for OPNsense installations.
See this forum post for more background and links:
https://forum.opnsense.org/index.php?topic=43583.msg216918#msg216918
I can of …

Default checksum offloading for the vtnet(4) driver to disabled

---

src/opnsense/mvc/app/models/OPNsense/Routing/Gateways.php

Before patch:
```
{
"result": "failed",
"validations": {
"gateway_item.": "Invalid IPv4 address"
}
}
```
After this patch:
```
{
"result": "failed",
"validations": {
"gateway_item.gateway": "Invalid IPv4 address"
}
}
```

routing/gateways: Fix ipv4 and ipv6 validation not being displayed in the gateway form

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/generalSettings4.xml
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.php
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml

This adds the ability to configure the DHCP socket type (UDP/Raw) in the Kea DHCP server settings through the web UI.
- Added socket type field to model definition
- Added dropdown in general settings form
- Updated config generation to include socket type setting

feat(dhcp): add dhcp-socket-type option to Kea DHCP server

---

plist
src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CaController.php
src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CertController.php
src/opnsense/mvc/app/views/OPNsense/Trust/ca.volt
src/opnsense/mvc/app/views/OPNsense/Trust/cert.volt
src/opnsense/www/js/widgets/Certificates.js
src/opnsense/www/js/widgets/Metadata/Core.xml

Fixes: https://github.com/opnsense/core/issues/7898
Adds a widget that pulls all CA and Certificates from the trust store API and displays them sorted by expiration date.
- Certificates with more than 14 days show a green lock
- with less than 14 days show yellow lock
- with no days left show red log and expired
An additional self populating dropdown allows to configure the plugin, hiding certificates.
The default is displaying all existing certificates.

dashboard: Add certificate widget that displays CAs and Certs sorted by expiration date

---

src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php
src/opnsense/mvc/app/views/OPNsense/IPsec/sessions.volt
src/opnsense/mvc/app/views/OPNsense/Interface/vip.volt
src/opnsense/mvc/app/views/OPNsense/OpenVPN/status.volt
src/opnsense/mvc/app/views/OPNsense/Routing/configuration.volt
src/opnsense/mvc/app/views/OPNsense/Trust/ca.volt
src/opnsense/mvc/app/views/OPNsense/Trust/cert.volt
src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
src/opnsense/www/js/opnsense_bootgrid_plugin.js
src/opnsense/www/js/opnsense_ui.js
src/opnsense/www/js/widgets/Carp.js
src/opnsense/www/js/widgets/Certificates.js
src/opnsense/www/js/widgets/Gateways.js
src/opnsense/www/js/widgets/IpsecTunnels.js
src/opnsense/www/js/widgets/OpenVPNClients.js
src/opnsense/www/js/widgets/OpenVPNServers.js
src/opnsense/www/js/widgets/Wireguard.js

Fixes: https://github.com/opnsense/core/issues/7895
- Introduces a generalized function to handle "search" and "edit" in url hashes. 
- Can handle changing a tab before firing a search and/or edit.
Implementations:

dashboard: Improved widget links with automatic edit and/or search

---

Makefile

It will become active in 2026.
Signed-off-by: Jagveer Loky (jagveer@cyberstorm.mu)

Update ICANN Trust Anchor to include the new one

---

src/opnsense/service/templates/OPNsense/Monit/monitrc

Currently, if you want to execute command with arguments, you have to create a script somewhere on filesystem, then specify path to it in the Execute parameter.
With this patch, it's possible to pass command line arguments as part of Execute string, e.g. `/sbin/ifconfig wg0 down`.
From [monit documentation](https://mmonit.com/monit/documentation/monit.html#ACTION):
> EXEC can be used to execute an arbitrary program and send an alert. If you choose this action you must state the program to be executed and if the program requires arguments you must enclose the program and its arguments in a quoted string

monit: wrap exec in double quotes to allow arguments

---

src/etc/rc.d/netflow

While testing some changes I ran `configctl service reload all` and got a timeout error.  After doing some digging I found that this relates to netflow data collection and doesn't happen if netflow collection is disabled.
After a bit of poking around it is due to the daemon/samplicate processes keeping a pipe open shared with the reload_all script, which then never termintes.  Adding the `daemon -f` parameter fixes.

configctl service reload all hangs

---

src/opnsense/www/js/widgets/Gateways.js
src/opnsense/www/js/widgets/Metadata/Core.xml

The PR addresses an [issue/feature request 8204](https://github.com/opnsense/core/issues/8204) I have previous opened.
Adds "(active)" beside the gateway name when defaultgw is true in the json returned by `/api/routing/settings/searchGateway`

Feature Request #8204 -- Show "Active" beside the active gateway in the Gateways Widget on the Dashboard

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/OneToOneController.php
src/opnsense/mvc/app/views/OPNsense/Firewall/filter.volt

Fixes: https://github.com/opnsense/core/issues/8235

firewall/nat: Add missing columns in one-to-one nat bootgrid

---

src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.php
src/opnsense/mvc/app/models/OPNsense/Firewall/Alias.xml
src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
src/opnsense/scripts/filter/lib/alias/__init__.py
src/opnsense/scripts/filter/lib/alias/uri.py
src/opnsense/service/templates/OPNsense/Filter/filter_tables.conf

Selectpicker class is omitted from the PR due to single-select dropdown issues.
Note: backend code could be shortened if the the model were to have an additional read-only property that could contain either the bearer token or the base64-encoded version of the username+password, but I doubt the config should be abused as such, so kept it simple here.

aliases: add optional authorization for URL type aliases

---

src/opnsense/mvc/app/controllers/OPNsense/Unbound/forms/dialogDot.xml
src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml
src/opnsense/service/templates/OPNsense/Unbound/core/dot.conf

Description:
- Adds support for 'forward-first' configuration for unbound forwarders (regular & TLS)
Based on/tested on 24.10 (with an in-situ make mount to run master live)
Rationale:
When using TLS, or other, forwarding, if all servers become unavailable, unbound will return SERVFAIL.
By [setting 'forward-first' ](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html)unbound will instead fallback to recursive resolution.
In my case I typically use quad9 (9.9.9.9) but very very occasionally they have a glitch and resolution fails. For example this [happened last week](https://www.reddit.com/r/Quad9/comments/1ieb266/problems_in_uk/) in parts of the UK
Implementation:
- Added new checkbox to UI (controller) when setting up a forwarding server. I did try to set the advanced …

opnsense: Add support for forward-first when configuring forwarders

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet4.xml
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml

Pull requests to expose the Kea option `v6-only-preferred` in the GUI.
I have set the MinimumValue to MIN_V6ONLY_WAIT (300 sec) as defined in https://www.rfc-editor.org/rfc/rfc8925.html#name-constants-and-configuration. I have not set the default value as this would always include the `v6-only-preferred` option in the configuration.
I have tested the config generation using OPNSense 25.1 and can confirm that a working config is generated both with and without value defined.

Expose Kea option v6-only-preferred in the GUI

---

plist
src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Kea/DhcpController.php
src/opnsense/mvc/app/views/OPNsense/Kea/dhcpv4.volt
src/opnsense/mvc/app/views/layout_partials/base_apply_button.volt

Fixes: https://github.com/opnsense/core/issues/8284
Example of generated HTML with the KEA example implementation:
```
<section class="page-content-main">
<div class="content-box">
<div class="col-md-12">
<br>
<div id="change_message_base_form" class="alert alert-info" style="display: none;" role="alert">
After changing settings, please remember to apply them.            </div>
<button class="btn btn-primary" id="reconfigureAct" data-endpoint="/api/kea/service/reconfigure" data-label="Apply" data-error-title="Error reconfiguring service." type="button"><b>Apply</b> <i class="reload_progress"></i></button>
<br><br>
</div>
</div>
</section>
```

mvc/view: Create layout_partials/base_apply_button to centralize design of the standard Apply button

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemController.php

on my system, supermicro X11SCL-iF, PCH temperature is reported and get identified as a CPU.
```
dev.cpu.0.temperature=48.0C
dev.cpu.1.temperature=46.0C
dev.cpu.2.temperature=45.0C
dev.cpu.3.temperature=46.0C
dev.pchtherm.0.temperature=45.0C
hw.acpi.thermal.tz0.temperature=27.9C
```
this PR adds additional parsing to identify this temperature sysctl.

Handle dev.pchtherm temperatures in the thermal dashboard widget

---

src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php
src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServerController.php
src/opnsense/mvc/app/controllers/OPNsense/Wireguard/GeneralController.php
src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt

Requires: https://github.com/opnsense/core/issues/8187
Requires: https://github.com/opnsense/core/issues/8284

vpn/wireguard: Integrate base_bootgrid_table and base_apply_button

---

src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/ClientOverwritesController.php
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/Api/InstancesController.php
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/ClientOverwritesController.php
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/InstancesController.php
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogCSO.xml
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogInstance.xml
src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogStaticKey.xml
src/opnsense/mvc/app/views/OPNsense/OpenVPN/cso.volt
src/opnsense/mvc/app/views/OPNsense/OpenVPN/instances.volt

For: https://github.com/opnsense/core/issues/8318
The whole sequence thing in the grid was unavoidable due to the way the old grid displayed some of its options in a different sequence than its form in the grid.

vpn/openvpn: Implement base_bootgrid_table and base_apply_button

---

src/opnsense/mvc/app/views/layout_partials/base_dialog.volt
src/opnsense/mvc/app/views/layout_partials/base_form.volt

This fixes an issue where introducing headers in forms will botch the alignment of fields because they all spawn their own table. Using relative sizes in the table and colgroup fixes this issue.
This also improves responsiveness of the modal.
Bonus: This also improved how form modals render on mobile devices.

mvc/view: Ensure fields stay aligned relatively to another when headers are used in forms

---

plist
src/etc/inc/plugins.inc.d/ipsec.inc
src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/settings.xml
src/opnsense/mvc/app/library/OPNsense/Auth/Services/IPsec.php
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.php
src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Menu/Menu.xml
src/opnsense/mvc/app/models/OPNsense/IPsec/Migrations/M1_0_4.php
src/opnsense/mvc/app/models/OPNsense/IPsec/Swanctl.php
src/www/vpn_ipsec_mobile.php

closes https://github.com/opnsense/core/issues/8349
Rename previous "advanced settings" to "mobile & advanced settings" to guide people into the right direction, strongswan.conf contains both sets of data. Keep legacy page for settings that are only relevant for the old components.
Since our pam authenticator hooks into the configuration, refactor to use the model as well.
Cleanup code in the model that was only used in the legacy glue.

VPN: IPsec: Mobile Clients - move charon attributes to 

---

src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogInstance.xml
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml

Add support for auth-gen-token renawal time.
Add support for auth-gen-token-secrets to allow failover between servers.
Add support for pushing inactive to clients to have them disconnect after being idle for a set time.
Add support for explicit-exit-notify and for pushing it. This will allow UDP connection to notify peers that they are going away.
Add support for ifconfig-pool-persist, which will allow smoother roaming combined with auth-gen-token since client will keep their ip address.
Add support from compress migrate. This option will conditionally use stub compression for clients announcing they have compression enabled while leaving it of for all other clients.

OpenVPN: Add support for various options

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/SettingsController.php
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
`--dhcp-fqdn`
``To ensure that all names have a domain part, there must be at least --domain without an address specified when --dhcp-fqdn is set.``
Fixes the following error:
```
2025-03-05T15:44:42 | Critical | dnsmasq | FAILED to start up
2025-03-05T15:44:42 | Critical | dnsmasq | there must be a default domain when --dhcp-fqdn is set
```

dnsmasq: When dhcp-fqdn is set, there must be a domain without an address set as default

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

This one makes simple setups simpler since we do not need to create any tags manually if we want to match custom DHCP options with a DHCP range.

dnsmasq: Use interface directly as tag in dhcp options

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDomainOverride.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8399

dnsmasq: Allow domain overrides to be optionally sorted by sequence number to support strict-order

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml

https://github.com/opnsense/core/blob/877b219c64ac0919cec19482c9e7795b0fb3ef7d/src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf#L132

dnsmasq: Add missing hint for lease time default value

---

src/sbin/opnsense-beep

Otherwise one of concurrent calls to `beep' might fail with error message "beep: open of /dev/speaker for writing: Device busy".
Locking is done in `opnsense-beep` and not in `beep` to preserve tune (avoid cacophony).  ${BEEPDIR}/low is used as a lock-file as `low' beep is already a special file: it's default beep.
This might sound like a trivial change, but it might affect system behavior, e.g. when `opnsense-beep' is used in some shell script with errexit enabled.

opnsense-beep: serialize access to /dev/speaker

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8440
The "add-subnet" option would be pretty hard to validate without a custom field type, or splitting the field up into like 2 integer and 2 Network fields (4 fields). Thus only the most probable use-case of adding the IPv4 and IPv6 client addresses was added. Even that would be hard to split up, as the documentation is a little fuzzy about only setting IPv6 for example.
This here is the simplest fix without spending too much time.

dnsmasq: Add add-mac, add-subnet and strip-subnet options

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

From man page:
`IPv6 options are specified using the option6: keyword, followed by the option number or option name. The IPv6 option name space is disjoint from the IPv4 option name space. IPv6 addresses in options must be bracketed with square brackets, eg. --dhcp-option=option6:ntp-server,[1234::56] For IPv6, [::] means "the global address of the machine running dnsmasq", whilst [fd00::] is replaced with the ULA, if it exists, and [fe80::] with the link-local address.`

dnsmasq: Add option6 to support DHCPv6 options

---

src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/AccessController.php
src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/SessionController.php
src/opnsense/mvc/app/library/OPNsense/Auth/Base.php
src/opnsense/mvc/app/library/OPNsense/Auth/IAuthConnector.php
src/opnsense/mvc/app/library/OPNsense/Auth/Radius.php
src/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py
src/opnsense/scripts/OPNsense/CaptivePortal/disconnect.py
src/opnsense/scripts/OPNsense/CaptivePortal/lib/db.py
src/opnsense/scripts/OPNsense/CaptivePortal/lib/pf.py
src/opnsense/scripts/OPNsense/CaptivePortal/process_accounting_messages.php
src/opnsense/service/conf/actions.d/actions_captiveportal.conf
src/www/system_authservers.php

- Adds proper Termination Cause handling, requires addition of `delete_reason` column in the captiveportal sqlite database.
- Implements `Acct-Input|Output-Gigawords` accounting handling (Fixes https://github.com/opnsense/core/issues/6712)
- implements `Called|Calling-Station-Id`. (Fixes https://github.com/opnsense/core/issues/7844)
- `Called-Station-Id` implemented via additional optional input field
- `Calling-Station-Id` requires an extra preauth hook, which in general is useful to handle per-session authentication properties.
- While here, silence output of pf during state kills when client is disconnected
- `NAS-IP-Address` isn't added, RFC2865 states it should be either `NAS-Identifier` of `NAS-IP-Address`.
Since it touches this area, perhaps we can remove the deprecated `$zoneid` …

radius: improved RFC alignment

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPmatch.xml
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/scripts/dns/dnsmasq_dhcp_options.py
src/opnsense/service/conf/actions.d/actions_dnsmasq.conf
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8454
I opted to remove this again: https://github.com/opnsense/core/commit/8b01bd2699973c00cefba9aa3323266e621f592d
Having two visible fields with a validation attached is a better experience.
Template test results:
```
dhcp-option=tag:lo3,6,127.0.0.1
dhcp-option=tag:lo3,option6:23,[::]
dhcp-option=tag:lo4,6,127.0.0.1
dhcp-option-force=tag:68c517cefdf84a11baa3111bbfddd317,tag:c2096cf25b2c46418afe2e1d18c3085c,tag:lo5,option6:23,[::]
```

dnsmasq: Add DHCPv6 options

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml

Right now it reveals group interfaces since they do not have an additional filter set.
Compare to this:
https://github.com/opnsense/core/blob/01f364e1bdbde2ae77dd1f6419c49a3823799466/src/opnsense/mvc/app/models/OPNsense/IDS/IDS.xml#L143-L152

dnsmasq: Adjust filter on interface field so group interfaces are filtered

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/SettingsController.php

While testing I added and deleted tags, and then my configuration became inconsistent because tags are used in model relation fields.
This should prevent inconsistent configuration states as it disallows tags in use from being deleted.

dnsmasq: Add internalModelUseSafeDelete to prevent deletion of currently used tags

---

src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt
src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/www/css/jquery.bootgrid.css
src/opnsense/www/js/jquery.bootgrid.js
src/opnsense/www/themes/opnsense-dark/build/css/jquery.bootgrid.css

Added options:
- `columnSelectForceReload` (default false). Changes current behavior for all bootgrids (currently adding a new column re-fetches the data, which is unnecessary in most cases). Caches response internally, thereby assuming the data for a newly added column is already present.
- `headerFormatters` object. Can be explicitly set via `data-headerFormatter-<identifier>` or implicitly linked via the row id.
- `setColumns` function (`grid.bootgrid("setColumns", ['colA', 'colB' ...])`). Marks passed columns for addition. Requires either a `reload` or `softreload` to apply.
- `unsetColumns` function (`grid.bootgrid("unsetColumns", ['colA', 'colB' ...])`). Marks passed columns for removal. Requires either a `reload` or `softreload` to apply.
- `softreload` function …

bootgrid: improve UX and extend bootgrid behavior

---

src/opnsense/www/js/widgets/OpenVPNClients.js

Due to the re-organisation of code the widget for OpenVPN clients lost the ability to display virtual IPv6 addresses for clients. This patch fixes this issue.

Display OpenVPN virtual IPv6 addresses for OpenVPN clients in dashboard widget

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

There were a few choices how to solve this, but this seemed to be the best in my opinion:
- Constructor is not a requirement for using RA now, as you can also use SLAAC with static IPv6 e.g. ``2003:aaaa:bbbb:cc00::`` without using a constructor, if you do not want to set a GUA on the interface.
- ``Default`` ra_mode with enable_ra does not use custom ra_params, but use implicit global defaults from enable_ra
- When a custom ra_mode is selected, the interface becomes a requirement, but thats how SLAAC works anyway, it must use an interface.
This prevents any new checkboxes or type selectpickers from being introduced.
Validation prevents misconfiguration and style visibility hides options automatically that are not executed in the template for the current choice.
Fixes: …

dnsmasq: Require interface when ra_mode is selected due to ra-param interface requirement.

---

src/opnsense/mvc/app/views/OPNsense/Auth/user.volt

Some dropdowns in dialogUser did not stay in line due to the important width style.
Also, the col-md-* do not exist anymore, they have been replaced with % width in the base dialog.

auth/user: Remove styles conflicting with 387c381

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/SettingsController.php
src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
src/opnsense/www/js/opnsense_ui.js

I really want something like this.
It's a combined selectpicker for interfaces and tags, and you can quickly filter seamlessly through multiple tabs to get a quick overview of the current configuration.
It improves UX quite a bit if the configuration is larger, especially if multiple tags and interfaces are used.
@AdSchellevis It might need some cleanup but the concept works.

dnsmasq: Add filter function for interfaces and tags with multiselect

---

src/etc/inc/plugins.inc.d/dnsmasq.inc
src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8487
Directive:
https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
```
--dhcp-host=[<hwaddr>][,id:<client_id>|*][,set:<tag>][,tag:<tag>][,<ipaddr>][,<hostname>][,<lease_time>][,ignore]
```
This should almost fully satisfy the requirements of the man page regarding this directive.
Test dataset:
```
<hosts uuid="9e5eb2a8-0ab2-4ed9-af5b-0c2787ddbfab">
<host>hostabc</host>
<domain>example.com</domain>
<ip>172.16.1.200,fd12:3456:789a:1::2</ip>
<client_id>*</client_id>
<hwaddr>aa:aa:aa:aa:aa:aa,bb:bb:bb:bb:bb:bb</hwaddr>
<lease_time/>
<ignore>1</ignore>
<set_tag/>
<descr/>
<comments/>
<aliases>abc1.example.com,abc2.example.com</aliases>
</hosts>
<hosts uuid="883bd818-2885-443d-a699-90fb55fe3466">
<host>hostd</host>
<domain>example.com</domain> …
```

dnsmasq: Add full dhcp-host support for IPv4 and IPv6

---

src/opnsense/mvc/app/views/OPNsense/Auth/user.volt

Right now, clicking `Search certificates by username` will redirect to:
`/ui/trust/cert/#user=test-user`
which will get history replaced to:
`/ui/trust/cert/#`
Due to the additional /# this does not exist in the menu.

auth/user: Fix url hash in link so redirection shows the correct menu path

---

src/opnsense/mvc/app/models/OPNsense/Core/repositories/opnsense.xml

After much deliberation, I have decided to shut down my dns-root.de mirror for the opnsense package files.
There are two main reasons for this decision:
1. Less involvement in the development & deployment process, which makes it hard for me to track new releases etc.
2. Still technical issues with the combination of Cloudflare and the mechanism behind pkg.
Unfortunately, I'm not very active in the opnsense community anymore and therefore don't catch problems with the mirror etc. fast enough.
In combination with work & personal projects I don't see my own demand for availability fulfilled.
With this pull request the mirror will be removed from the source, but will be online & supported at least until opnsense 26.1.
Based on the traffic I will decide in early 2026 how to proceed and most …

Sunset mirror dns-root.de

---

src/www/services_router_advertisements.php

Allows to have the same router IP on different interfaces (common for IPv6)
Discussed in #8512 
Fixes: #8512

Fix list of source addresses in router advertisements

---

src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt

- Add button to clear the filter instantly, and show that the current view is filtered by changing the fa-icon and color
- When interfaces and tags are selected, add them on best effort basis in the opened add dialog

dnsmasq: Improve interface/tag selectpicker

---

src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/SystemController.php

This PR implements the feature request in #8556
Additionally to the calculated and formatted uptime, it exposes the systems boot time as Date-Time-String alongside the Current System time. This makes it easier for API consumers to work with the value, instead of having to try to calculate the boot time from the uptime.

Add field boottime to api/system/systemTime

---

plist
src/etc/inc/plugins.inc.d/kea.inc
src/opnsense/mvc/app/controllers/OPNsense/Kea/Api/Dhcpv6Controller.php
src/opnsense/mvc/app/controllers/OPNsense/Kea/Api/ServiceController.php
src/opnsense/mvc/app/controllers/OPNsense/Kea/DhcpController.php
src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogPDPool6.xml
src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogPeer6.xml
src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogReservation6.xml
src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet6.xml
src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/generalSettings6.xml
src/opnsense/mvc/app/models/OPNsense/Kea/ACL/ACL.xml
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv6.php
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv6.xml
src/opnsense/mvc/app/models/OPNsense/Kea/Menu/Menu.xml
src/opnsense/mvc/app/views/OPNsense/Kea/dhcpv6.volt
src/opnsense/service/templates/OPNsense/Kea/keactrl.conf
src/opnsense/service/templates/OPNsense/Kea/rc.conf.d

This contains roughly the same configuration items as our current isc-dhcp6 alternative, with the exception of not trying to implement dynamic ranges based on data received from dhclient6. In terms of target audience, dynamic environments (receiving their "wan" type addressess via dhcp), should logically use dnsmasq for client configuration. Large (enterprise) setups usually are static by nature and may require prefix deligation to routers behind the primary one. In these cases Kea will be the tool of choice.
Both v4 and v6 share the same rc scripts underneath, which means reconfiguration happens per package (eventhough two services are registered). Existing hooks for v4 have been extended with v6 data (firewall rules and staticmaps).
Advanced configurations can still opt out of config …

Services: Kea DHCP: Kea DHCPv6 - add new option based on v4

---

src/etc/inc/plugins.inc.d/dhcpd.inc
src/etc/inc/plugins.inc.d/radvd.inc
src/opnsense/mvc/app/models/OPNsense/Base/Menu/MenuSystem.php
src/www/services_dhcpv6.php
src/www/services_router_advertisements.php

Needed in case someone would like to use dnsmasq or kea instead.
To avoid large changes, we opt for a  minimal set here. In services_dhcpv6.php, we add a separate form and handler in case tracking (without dhcpd6track6allowoverride) is set, which either flushes the unused isc-dhcpv6 server configuration when enabled (default) or writes a small section only including ['enabled' => -1]. For visibility, we show the calculated range as would be set by dhcpd_dhcp6_configure() when tracking is used.
The backend code then double checks the services which er explicitly disabled (-1) and skip processing for these (not enabled).
In order to make people aware of the fact that an isc-dhcpv6 server could be running, make sure the menu system also reflects reality.
Since router advertisements are …

Services: ISC DHCPv6 - show "tracking" interfaces when enabled and offer an explicit disable

---

src/etc/inc/plugins.inc.d/unbound.inc
src/www/services_dhcp_edit.php

Hi OPNsense Team,
This PR resolves Issue #8266, addressing an Unbound startup failure when "Register DHCP Static Mappings" is enabled and an ISC DHCPv4 static mapping specifies a domain name beginning with a dot.
---
The `unbound_add_host_entries` function reads domain values directly from ISC DHCPv4 static mappings in `config.xml` without validation.  
When the domain field begins with a dot (e.g., `.domain.local`), concatenation during FQDN generation (`hostname`.`domain`) produces invalid entries like `hostname..domain.local`.  
This results in invalid `local-data` records written to `/var/unbound/host_entries.conf`, causing Unbound to fail parsing and preventing service startup.
---
This patch introduces targeted sanitation in `unbound_add_host_entries`:
- Leading dots are stripped …

unbound: fix invalid FQDN generation from DHCPv4 static map domains

---

src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml
src/opnsense/service/templates/OPNsense/Shaper/dnctl.conf

Currently, dynamic pipe and queues based on masking don't work (well) for IPv6. IPv6 flows appear to all end up bucketed into single `::/0` flow. This isn't particularly desirable when attempting to use the traffic shaper to implement the "share bandwidth equally among all users" use-case, because there's no way to distinguish between IPv6 flows.
From experimentation, it seems like configuring a mask using `*-ip` specifiers always buckets IPv6 flows into a single bucket, and vice versa for `*-ip6` specifiers.
This patch allows the user to decide which mask specifiers to use. As far as I can tell, this change should be backwards compatible with existing configuration.

Add ability to specify pipe and queue masking using the *-ip6 specifiers.

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogSubnet4.xml

Using semicolons to separate destination–router pairs is a syntax error. Kea expects the `static-routes` option to be a list of IP addresses: https://github.com/isc-projects/kea/blob/60222843a6b2c4e7a6c7d4e63f88d0dcfa0d5b97/doc/examples/kea4/all-options.json#L415-L430

Fix help message for Kea static routes

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php

Fixes: https://github.com/opnsense/core/issues/8641
I had already prepared it in the template and the configuration seems valid for dhcpv6 and ra.

dnsmasq: Allow static on IPv6 ranges

---

src/etc/inc/plugins.inc.d/dnsmasq.inc

Not sure what the roadmap/plans for this are but I noticed this after migrating from KEA to dnsmasq for my DHCP usage today (especially since I use 0 for the DNS port to disable it, which makes the service name/label of `Dnsmasq DNS` even more confusing for me). I figured it would be easier to open a PR instead of an issue for such a small thing...

Adjust a few instances of dnsmasq labeling/description primarily for the services widget display

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8624
Since any dhcp_boot parameter is optional, there is no additional validation needed.
I tested it in most combinations, even all empty container, and it did not cause dnsmasq to fail.

dnsmasq: Add missing dhcp_boot to template

---

src/etc/config.xml.sample
src/opnsense/mvc/app/controllers/OPNsense/Core/forms/wizard_general_info.xml
src/www/system_general.php

as current domain is blocked by DNSSEC validating clients
This PR changes the domain, updates the help and also adds it to the new setup wizard. And don't just suggest the name as in #5898, update the default as previously suggested in #7193.
systemd-resolved has `internal` on its DNSSEC negative trust anchor list since 2016, where `home.arpa` was added later:
https://github.com/systemd/systemd/commit/30c778094b90a637c6691c462a66df81eeb865b5#diff-23206c93f79c419c8a911a58d533e3ca9a6103ff215a5fcc887aaecb59021276R155
**.internal history**
Internal was first mentioned in RFC 6762 (2013) within multicast DNS:
https://datatracker.ietf.org/doc/html/rfc6762#appendix-G
IANA assessment (2024-01):
https://itp.cdn.icann.org/en/files/root-system/identification-tld-private-use-24-01-2024-en.pdf
ICANN …

Change default DHCP domain to `internal`

---

src/opnsense/scripts/dhcp/get_dnsmasq_leases.py

For: https://github.com/opnsense/core/issues/8643
In most cases the DUID can be used to extract the MAC address to show vendor information for IPv6 leases just like IPv4 leases.

dnsmasq: Extract MAC from DUID in most cases to allow vendor information

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8690

dnsmasq: Allow multiple tags per dhcp-boot, fix tag rendering by removing "-" like in other parts of template

---

src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/AccessController.php
src/opnsense/scripts/OPNsense/CaptivePortal/cp-background-process.py

The voucher system (specifically, voucher validity) currently wasn't reflected in the timeout calculation, include it here.
While here, added a small note about the intent of `drop_reason`.

captive portal: align accounting session timeout with captive portal API

---

src/opnsense/service/templates/OPNsense/Shaper/dnctl.conf

Using the same format for both IPv4 and IPv6 mask specifications makes the template easier to understand at a glance.

Use CIDR notation for specifying masks to dnctl.

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8708

dnsmasq: Add no-resolv option to prevent use of system defined dns servers

---

src/opnsense/scripts/shaper/lib/__init__.py

When using the *-ip6 mask specifiers introduced in #8581, dnctl produces output that dummynet_stats.py fails to correctly parse.
The line in particular is:
```
mask: proto: 0x00, flow_id: 0x00000000,  ::/0x0000 -> ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/0x0000
```
The line above is currently incorrectly parsed as an IPv6 flow, rather than being ignored. This PR improves the flow parsing by explicitly rejecting lines that describes a mask.

Improve dummynet_stats.py parsing of mask descriptor lines.

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

to prevent queries to upstream servers, this makes dnsmasq solely responsible for them. Otherwise it could accidentally ask its upstream servers if it acts as a resolver at the same time.
```
-S, --local, --server=[/[<domain>]/[domain/]][<server>[#<port>]][@<interface>][@<source-ip>[#<port>]]
Also permitted is a -S flag which gives a domain but no IP address; this tells dnsmasq that a domain is local and it may answer queries from /etc/hosts or DHCP but should never forward queries on that domain to any upstream servers. --local is a synonym for --server to make configuration files clearer in this case.
```
Log file example:
```
2025-05-22T07:05:26Informationaldnsmasqusing only locally-known addresses for ad.pischem.com
2025-05-22T07:05:26Informationaldnsmasqusing only locally-known …
```

dnsmasq: When dhcp-fqdn is active, set all dhcp domains as local

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml

It is not needed in most cases, so it is sensible to hide it in advanced mode to indirectly imply it is not that important for most usecases.
https://github.com/opnsense/core/issues/8707#issuecomment-2900338317
For: https://github.com/opnsense/core/issues/8707

dnsmasq: Hide static mode in dhcp-range in advanced mode

---

src/etc/inc/plugins.inc.d/dnsmasq.inc
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8703
Please take a good look at the validation.
Please improve it if necessary, and test it.
I have tested it, and generated the correct configuration file with a wide range of inputs, but this feels like a delicate change that needs some thoughts, also if we want it.

dnsmasq: Allow either empty IP or empty hostname for dhcp-host entries.

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8740

dnsmasq: Set default to empty lease time for dhcp-host which results in auto calculated defaults

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml

This should be self-explanatory — I was confused with how tags would work, I somehow assumed any of the selected tags would match, but that's not the case, as all tags must match if more than one is selected, per dnsmasq documentation: 
```
Each configuration line containing one or more tag:<tag> constructs applies when all its tags exist on the request. That is:
Configuration tag:A applies to a request set:tagged A.
Configuration tag:B applies to a request set:tagged B.
Configuration tag:A+B doesn't apply to a request set:tagged A.
Configuration tag:A+B doesn't apply to a request set:tagged B.
Configurations tag:A+B, tag:A, tag:B apply to a request set:tagged A+B.
```

dnsmasq: Update help on multiple tags usage (all tags must match)

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/generalSettings6.xml

Wrong filename used in kea dhcp6 Manual config file help.

Fix filename in kea dhcp6 manual help.

---

src/opnsense/scripts/interfaces/rtsold_resolvconf.sh

This reduces system churn (e.g. resolv.conf rewrites and dnsmasq reloads) from WAN RAs.
Fixes #8759

interfaces: drop redundant updates in rtsold_resolvconf.sh

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Fixes: https://github.com/opnsense/core/issues/8797
It works in my test, now A and AAAA records for the same DHCPv4 and DHCPv6 client are finally appearing under their respective dhcp domain. PTR works as well for both.
The type is "Interface" per default, as its the most sane default. "Range" is more for edge cases.
Nothing has to be deduplicated, dnsmasq doesnt care if a domain entry exists twice with the same data.
Everything else is validated via the model.

dnsmasq: Implement domain_type to select between adding domain to range or interface

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml

This prevents changing existing setups with a new (unexpected) default.
For: https://github.com/opnsense/core/pull/8814

dnsmasq: Change domain_type default to range to retain current default logic

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/CategoryController.php
src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/categoryEdit.xml
src/opnsense/mvc/app/views/OPNsense/Firewall/category.volt
src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
src/opnsense/www/js/opnsense.js

Just as an idea since the javascript dependency looks unmaintained.
This lets the browser render the color input.
It gets appended to body which is nice.
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/color
Chrome on Macbook:
Link: https://github.com/opnsense/core/pull/8858

firewall/category: Add HTML based standardized color input to form

---

src/opnsense/mvc/app/views/OPNsense/Auth/user.volt
src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
src/opnsense/mvc/app/views/OPNsense/Kea/dhcpv4.volt
src/opnsense/mvc/app/views/layout_partials/base_bootgrid_table.volt
src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/www/js/opnsense_bootgrid.js

Since the rendering of the table is now asynchronous, and because of general backwards incompatibility, custom buttons that were injected after UIBootgrid initialization don't show up anymore in with the new wrapper.
This commit attempts to generalize the problem by moving custom grid commands to the `base_bootgrid_table` partial, while keeping the responsibility of interaction local to the page at hand.
Because constructs such as `SimpleFileUploadDlg` cannot be delegated, move this into an event handler that fires when we know the UI has rendered.
In the long term it would make more sense to move this logic to the tabulator wrapper instead, but this requires the UI to be fully decoupled from the template.

mvc: extend base_bootgrid_table with grid_commands

---

src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CaController.php
src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CertController.php
src/opnsense/mvc/app/views/OPNsense/Trust/cert.volt

Although you can create a CSR in the OPNsense web UI, you cannot download one. User @Zewwy from IRC was trying and getting silent failures because the UI doesn't have an option for it. You can choose the following options
- Certificate (silent failure, the CSR has no certificate body)
- PKCS12 (silent failure, the CSR has no certificate body)
- Private key (works fine, the private key is generated alongside the CSR)
This PR adds the "Certificate Signing Request" option into the download box, and when this option is used the API serves up the CSR payload
Fixes: #8834, #8835

#8834/#8835: allow CSR to be downloaded from Sytem/Trust/Certificates

---

src/opnsense/mvc/app/controllers/OPNsense/Kea/forms/dialogReservation4.xml
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.php
src/opnsense/mvc/app/models/OPNsense/Kea/KeaDhcpv4.xml

Added DNS field to Kea DHCP4 Reservations.
Utilizes masking instead of tokeniation for UI consistency.
Tested on 25.1.9_2
Kea reference for options: https://kea.readthedocs.io/en/kea-2.0.0/arm/dhcp4-srv.html#dhcp4-std-options

Add DNS field to Kea DHCP4 Reservations

---

src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt

Since we call functions to repopulate the selectpickers during the reconfigureAct they triggered the changed events to reload the bootgrid and change the url hash. A new variable was introduced that tracks the reconfigureActInProgress and prevents spurious reloads during it. After the selectpickers have been repopulated with their preserved values, a promise is returned which sets the reconfigureActInProgress to false, unlocking the normal change event behavior during selecpicker usage.
Essentially this prevents the grid reloading and the url hash resetting, each apply would boot the user back to Floating rules with resetted selectpickers.
Refines this: https://github.com/opnsense/core/pull/8898

automation/filter: Do not reload the grid during reconfigureAct

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

It is more useful than expected:
- Services that are IPv6 only, use DHCPv6 via dynamic partial IPv6 addresses can only have alternative names with CNAMEs
- Services that are dynamic IPv4, have a dhcp-host without IPv4 address set, can only have an alias with CNAMEs
Hosting virtual hosts on a webserver with dynamic IPv6 addresses need CNAMEs.
Fixes: https://github.com/opnsense/core/issues/8821
known error states (crash):
```
1.
cname=example4.com
dnsmasq: bad CNAME at line 12 of /usr/local/etc/dnsmasq.conf
2.
cname=example2.com,example.com
cname=example2.com,example.com
dnsmasq: duplicate CNAME at line 11 of /usr/local/etc/dnsmasq.conf
3.
cname=example3.com,example.com
cname=example.com,example3.com
dnsmasq: CNAME loop involving example.com
```
Allowed (no crash):
```
1. …
```

dnsmasq: Add CNAME configuration option to host overrides

---

src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php
src/opnsense/www/js/opnsense_bootgrid.js

This allows us to include keyable data that is unaffected by translations, making sure that we can format grid cells properly based on the actual value.
Builds on https://github.com/opnsense/core/commit/23c09fc4d
fwiw, `$` as a prefix may not be optimal so leaving this open for discussion

mvc: use getNodeContent to gather grid data

---

src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt

Updated strings to be translateable...
The string "Starting from " is still not translateable. I don't know how to do it, because it is dynamically loading after volt templating.

lang: Make more strings translateable

---

src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php
src/opnsense/mvc/app/controllers/OPNsense/Kea/DhcpController.php
src/opnsense/mvc/app/library/OPNsense/Base/UIModelGrid.php
src/opnsense/www/js/opnsense_bootgrid.js

Continuation of https://github.com/opnsense/core/commit/a0bc7adda95876937ea0ba9c3d5542bfb741ffdb and https://github.com/opnsense/core/commit/66b0488a99a6dc6bf763cb440c65b5d37c847c27.
Because https://github.com/opnsense/core/blob/66b0488a99a6dc6bf763cb440c65b5d37c847c27/src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php#L260 always picks the last key regardless of depth, and because our model does not allow nested ArrayFields, this should be safe to do.

ui: flatten nested containers for grid inclusion

---

src/opnsense/mvc/app/models/OPNsense/Wireguard/ACL/ACL.xml

Fixes: https://github.com/opnsense/core/issues/8960
There is a little overlap between the config and diagnostics ACL in UI paths.
That could be tweaked as well by limiting the ui path to `ui/wireguard/general/*` but it would change current behavior of the `page-wireguard-config` ACL.

vpn/wireguard: Add diagnostics and log file ACL

---

src/opnsense/mvc/app/views/OPNsense/IDS/index.volt

Fixes: https://github.com/opnsense/core/issues/8992

ids: Turn interface converter into formatter in grid-alerts

---

src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogInstance.xml
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml

A mix of dynamic and cso enabled clients can cause IP duplication in the pool. With nopool, only CSO will manage all addresses, clients without a CSO will not receive an IP address.
Fixes: https://github.com/opnsense/core/issues/8857

vpn/openvpn: Add nopool directive

---

src/www/system_general.php
src/www/system_usermanager_passwordmg.php

Language selection in system_general.php and system_usermanager_passwordmg.php is broken for low vertical resolution screens, very common on laptops.
This PR fixes it without causing issues on bigger screens.
Before:
After:

ui: fix language selection for low vertical resolution screens

---

src/opnsense/mvc/app/controllers/OPNsense/Core/forms/snapshot.xml

Fixes: https://github.com/opnsense/core/issues/9059

core/snapshot: Add missing timestamp formatter

---

src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

If dnsmasq is the first DNS server in line, and you do not want to use a unique DHCP domain, forcing the DHCP domain to be local breaks all upstream queries for it. This might be wanted if you forward from Unbound to dnsmasq since it fixes DNS loops, but if dnsmasq is your primary forwarding resolver, it knows what to forward and what to answer.
Mostly from reddit and opnsense forum feedback, it caught more than one user offguard.
Most recent example: https://www.reddit.com/r/opnsense/comments/1mk16y1/dnsmasq_not_forwarding_local_domain_queries/

dnsmasq: Allow disabling local for DHCP domains

---

src/opnsense/mvc/app/models/OPNsense/IPsec/IPsec.xml

Fixes: https://github.com/opnsense/core/issues/9078

vpn/ipsec: Add default value to make_before_break that retains original behavior before strongswan 6.0.0

---

src/opnsense/www/js/opnsense_bootgrid.js

Small fix for: https://github.com/opnsense/core/commit/e2ed3138a5ad3d2f207501954a9193b1ce061fa2

bootgrid: Fix expandGroupBy() call to use correct context

---

src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/dialogFilterRule.xml
src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt

- Tooltips are always body so data placement can be removed.
- Make categories column smaller, remove header text.
- Fix sequence of some columns.

firewall/automation: Tweak the grid headers

---

src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt

Prevents all instances of this warning:
``DataLoader.js:57 Data Load Response Blocked - An active data load request was blocked by an attempt to change table data while the request was being made``
- Safeguard Category selectpicker on initial page load
- Fast path for URL hash, read and consume it once on page load without going through the interface selectpicker first
This improves performance.
Fixes: https://github.com/opnsense/core/issues/9148

firewall/automation: Prevent multiple grid reloads on initial page load

---

src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt

- Remove rowSelect from internal rules
- Remove rowSelect from dataTree headers and from the grid header if Tree is active
- Remove orphaned color code in category rowFormatter
- Add a tabulator rowFormatter and remove all "onRendered" logic from cell formatters
Fixes: https://github.com/opnsense/core/issues/9152

firewall/automation: Remove rowselect from internal and dataTree

---

src/opnsense/mvc/app/views/layouts/default.volt
src/opnsense/www/js/opnsense_ui.js

Closes: https://github.com/opnsense/core/issues/9084
This would be useful both in no mouse situations and in boosting productivity, enabling users to toggle quickly between states.
"a" = advanced mode
"h" = full help

gui: keyboard shortcuts for advanced and help

---

src/opnsense/mvc/app/controllers/OPNsense/Interfaces/Api/OverviewController.php

interfaces/overview: Fix flags in interface details, do not show hex code but parsed flags

---

src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
src/opnsense/scripts/wireguard/wg-service-control.php
src/opnsense/service/templates/OPNsense/Syslog/local/wireguard.conf
src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf

Fixes: https://github.com/opnsense/core/issues/9234

vpn/wireguard: Add debug flag to instances, can be set without restarting service, send logs to wireguard log

---

src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf

Closes: https://github.com/opnsense/core/issues/9263
- domain in domainoverrides is changed to the strict HostnameField introduced in 2d2781c to disallow the use of "#" which would add all resolved domains to an ipset alias. The overall strictness of the field now matches hosts.
Fixes: https://github.com/opnsense/core/issues/9262
- dnsmasq.conf template does not render server and rebind-domain-ok for entries anymore which are just a domain and the Firewall alias (ipset). Before this change, it would generate a server with an empty IP, which means blocking forwarding. Firewall alias (ipset) needs forwarding to function, otherwise it fails for the chosen domain.
Unrelated to the above tickets, but fixed regardless:
- ipset ModelRelationField got a name filter adjustment, to exclude all …

dnsmasq: Improve Firewall alias (ipset) validations
